import type { BootcampModule } from '../types.js';

export const module09: BootcampModule = {
  id: 'module-09',
  number: 9,
  title: 'Network Design & Troubleshooting',
  description: 'Design principles, hierarchical network architecture, IP address planning, and systematic troubleshooting methodology.',
  color: '#8888ff',
  tier: 'platinum',
  prerequisites: ['module-08'],
  labIds: ['lab-08-troubleshooting', 'lab-05-server-network', 'lab-16-nas-file-server'],
  lessons: [
    {
      id: 'm09-l01',
      title: 'Network Design Principles',
      order: 1,
      type: 'theory',
      estimatedMinutes: 12,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'Network Design Principles' },
          { type: 'analogy', text: 'Designing a network is like designing a highway system. You need fast interstate highways (core), regional junctions (distribution), and local streets (access). Each level has a different purpose, and good design keeps traffic flowing smoothly at every level.' },
          { type: 'paragraph', text: 'A well-designed network is scalable, resilient, and manageable. Enterprise networks follow a hierarchical model that separates functions into distinct layers, making it easier to grow, troubleshoot, and secure the network.' },
          { type: 'heading', level: 2, text: 'The Three-Tier Hierarchical Model' },
          { type: 'paragraph', text: 'Cisco\'s classic three-tier model divides the network into three functional layers. Each layer has specific responsibilities and design considerations.' },
          { type: 'key-term', term: 'Core Layer', definition: 'The backbone of the network. Its only job is to move data as fast as possible between distribution layers. High-speed switching with no packet manipulation (no ACLs, no NAT). Uses redundant high-bandwidth links (10G, 40G, or 100G). Think of it as the interstate highway.' },
          { type: 'key-term', term: 'Distribution Layer', definition: 'The policy layer. Connects access layers to the core. Applies routing, filtering (ACLs), QoS, and summarization. Aggregates traffic from multiple access switches. Contains the "intelligence" of the network.' },
          { type: 'key-term', term: 'Access Layer', definition: 'Where end devices connect — PCs, phones, printers, wireless APs. Provides port security, VLAN assignment, PoE (Power over Ethernet), and spanning tree edge ports. The local streets of the network.' },
          { type: 'comparison-table', headers: ['Layer', 'Primary Function', 'Typical Devices', 'Key Features'], rows: [
            ['Core', 'High-speed transport', 'L3 switches, high-end routers', 'Redundancy, fast convergence, no filtering'],
            ['Distribution', 'Policy and aggregation', 'L3 switches, routers', 'ACLs, routing, VLAN routing, summarization'],
            ['Access', 'User connectivity', 'L2 switches, wireless APs', 'Port security, VLANs, PoE, STP edge'],
          ] },
          { type: 'callout', variant: 'info', text: 'Small to medium networks often collapse the core and distribution into a single "collapsed core" — two layers instead of three. This is called the two-tier or collapsed core design.' },
          { type: 'heading', level: 2, text: 'Redundancy' },
          { type: 'paragraph', text: 'A network without redundancy has single points of failure. If one link or device fails, everything behind it goes down. Good design eliminates single points of failure at every layer.' },
          { type: 'bullet-list', items: [
            'Redundant links: At least two uplinks from each access switch to distribution',
            'Redundant devices: Dual core switches, dual distribution switches',
            'Redundant paths: Spanning Tree Protocol (STP) or L3 ECMP prevents loops while providing failover',
            'Redundant power: Dual power supplies, UPS systems, generator backup',
            'First Hop Redundancy: HSRP or VRRP provides a virtual default gateway shared between two routers',
          ] },
          { type: 'callout', variant: 'key-concept', text: 'The rule of thumb: every critical component should have a backup. No single point of failure should be able to take down the entire network or a major segment of it.' },
          { type: 'heading', level: 2, text: 'Additional Design Principles' },
          { type: 'bullet-list', items: [
            'Modularity: Design in blocks (campus, WAN, data center, DMZ) so changes in one area do not affect others',
            'Scalability: Plan for growth — leave room for additional VLANs, IP ranges, switch ports, and bandwidth',
            'Security: Defense in depth — firewalls, ACLs, port security, 802.1X authentication at every layer',
            'Documentation: Maintain network diagrams, IP address spreadsheets, cable labels, and change logs',
            'Standardization: Use consistent naming conventions, configurations, and equipment across the network',
          ] },
        ],
      },
    },
    {
      id: 'm09-l02',
      title: 'IP Address Planning',
      order: 2,
      type: 'theory',
      estimatedMinutes: 10,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'IP Address Planning' },
          { type: 'paragraph', text: 'A well-planned IP addressing scheme makes the network easier to manage, troubleshoot, and scale. Poor planning leads to address conflicts, wasted space, and routing nightmares.' },
          { type: 'heading', level: 2, text: 'Subnetting for Departments' },
          { type: 'paragraph', text: 'Assign each department or functional group its own subnet. This provides broadcast domain isolation, security boundaries (via ACLs), and easier troubleshooting.' },
          { type: 'code-block', code: 'Company network: 10.10.0.0/16\n\nDepartment Subnets:\n  Engineering:   10.10.10.0/24  (254 hosts)  VLAN 10\n  Sales:         10.10.20.0/24  (254 hosts)  VLAN 20\n  HR:            10.10.30.0/24  (254 hosts)  VLAN 30\n  Management:    10.10.40.0/24  (254 hosts)  VLAN 40\n  Servers:       10.10.100.0/24 (254 hosts)  VLAN 100\n  Printers:      10.10.200.0/28 (14 hosts)   VLAN 200\n  Guest Wi-Fi:   10.10.250.0/24 (254 hosts)  VLAN 250\n\nPoint-to-point links (router-to-router):\n  R1-R2:  10.10.0.0/30\n  R1-R3:  10.10.0.4/30\n  R2-R3:  10.10.0.8/30' },
          { type: 'callout', variant: 'tip', text: 'Use a logical numbering scheme: VLAN 10 → 10.10.10.0/24, VLAN 20 → 10.10.20.0/24. This makes it easy to identify which subnet belongs to which VLAN at a glance.' },
          { type: 'heading', level: 2, text: 'VLSM — Variable Length Subnet Masking' },
          { type: 'paragraph', text: 'VLSM allows you to use different subnet masks within the same network. This avoids wasting addresses by sizing each subnet to fit its actual needs.' },
          { type: 'key-term', term: 'VLSM (Variable Length Subnet Masking)', definition: 'Using different prefix lengths for different subnets within the same address space. A department with 200 users gets a /24 (254 hosts), while a point-to-point link between two routers gets a /30 (2 hosts).' },
          { type: 'code-block', code: 'Without VLSM (wasteful):\n  Every subnet gets /24 — even router links with only 2 devices\n  Router link: 10.10.1.0/24 → 252 addresses wasted!\n\nWith VLSM (efficient):\n  Large department: 10.10.10.0/24 (254 usable)\n  Small department: 10.10.50.0/26 (62 usable)\n  Server farm:      10.10.100.0/27 (30 usable)\n  Router link:      10.10.0.0/30 (2 usable)\n  Loopback:         10.10.255.1/32 (1 address)' },
          { type: 'callout', variant: 'key-concept', text: 'Always right-size your subnets. Use /30 for point-to-point links, /32 for loopbacks, and appropriately sized subnets for user groups. Plan for roughly 50% growth headroom.' },
          { type: 'heading', level: 2, text: 'IP Planning Best Practices' },
          { type: 'numbered-list', items: [
            'Start with a summarizable block (e.g., 10.10.0.0/16 for the whole campus)',
            'Assign subnets by function: users, servers, management, IoT, guest',
            'Reserve addresses: .1 for default gateway, .2-.10 for infrastructure (switches, APs)',
            'Use DHCP for end devices, static IPs for servers and network equipment',
            'Document everything in a spreadsheet: subnet, VLAN, gateway, DHCP range, description',
            'Leave gaps between allocations for future growth',
          ] },
          { type: 'heading', level: 2, text: 'Route Summarization' },
          { type: 'paragraph', text: 'If you plan subnets carefully, you can summarize multiple subnets into a single route advertisement. This shrinks routing tables and speeds up convergence.' },
          { type: 'code-block', code: 'Building A subnets:\n  10.10.10.0/24\n  10.10.11.0/24\n  10.10.12.0/24\n  10.10.13.0/24\n\nSummary route: 10.10.10.0/22 (covers .10.0 through .13.255)\nOne route instead of four!' },
        ],
      },
    },
    {
      id: 'm09-l03',
      title: 'Troubleshooting Methodology',
      order: 3,
      type: 'theory',
      estimatedMinutes: 12,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'Troubleshooting Methodology' },
          { type: 'paragraph', text: 'When something breaks, the worst thing you can do is randomly change configurations. Professional network engineers follow a systematic approach to identify and resolve problems quickly.' },
          { type: 'analogy', text: 'Troubleshooting is like being a detective. You gather clues (symptoms), form a theory (hypothesis), test it (verify), and either solve the case or form a new theory. Random guessing is like arresting people at random — it wastes time and creates new problems.' },
          { type: 'heading', level: 2, text: 'The Three Approaches' },
          { type: 'key-term', term: 'Bottom-Up Approach', definition: 'Start at Layer 1 (Physical) and work up. Check cables, link lights, interface status, then IP addressing, then routing, then application. Best when you suspect a physical or connectivity issue.' },
          { type: 'key-term', term: 'Top-Down Approach', definition: 'Start at Layer 7 (Application) and work down. Check if the application works, then DNS, then routing, then IP config, then physical. Best when users report "the app is broken" but the network seems fine.' },
          { type: 'key-term', term: 'Divide-and-Conquer Approach', definition: 'Start at the middle (Layer 3/4). Ping and traceroute first. If Layer 3 works, the problem is above — check application/DNS. If it fails, the problem is below — check L1/L2. Most experienced engineers start here.' },
          { type: 'comparison-table', headers: ['Approach', 'Start', 'Direction', 'Best When'], rows: [
            ['Bottom-Up', 'Layer 1 (Physical)', 'Up through layers', 'New installation, cable/hardware suspected'],
            ['Top-Down', 'Layer 7 (Application)', 'Down through layers', 'Specific app failure, user complaint'],
            ['Divide-and-Conquer', 'Layer 3 (Network)', 'Up or down based on results', 'General troubleshooting, fastest for experienced engineers'],
          ] },
          { type: 'callout', variant: 'key-concept', text: 'Divide-and-conquer is the most efficient method. Start with ping/traceroute. If you can ping the destination, the problem is above Layer 3. If you cannot, work downward through L2 and L1.' },
          { type: 'heading', level: 2, text: 'Systematic Troubleshooting Steps' },
          { type: 'numbered-list', items: [
            'Identify the problem: Gather symptoms. What exactly is failing? Who is affected? When did it start?',
            'Establish a theory: Based on symptoms, hypothesize which layer and component is at fault',
            'Test the theory: Use show commands, ping, traceroute to confirm or deny your hypothesis',
            'Establish a plan: Once the root cause is identified, plan the fix and consider the impact of changes',
            'Implement the fix: Make ONE change at a time so you know what resolved the issue',
            'Verify: Confirm the fix works and has not caused new problems',
            'Document: Record the problem, root cause, and solution for future reference',
          ] },
          { type: 'callout', variant: 'warning', text: 'Never make multiple changes at once. If you change three things and the problem is fixed, you do not know which change actually fixed it — and the other changes may cause new problems later.' },
          { type: 'heading', level: 2, text: 'Layer-by-Layer Checklist' },
          { type: 'comparison-table', headers: ['Layer', 'What to Check', 'Commands/Tools'], rows: [
            ['L1 Physical', 'Cable plugged in? Link light? Speed/duplex?', 'show ip interface brief, show interfaces, visual inspection'],
            ['L2 Data Link', 'MAC learning? VLAN correct? STP blocking?', 'show mac address-table, show vlan brief, show spanning-tree'],
            ['L3 Network', 'IP correct? Subnet match? Route exists? ACL blocking?', 'show ip route, ping, traceroute, show access-lists'],
            ['L4+ Transport/App', 'Port open? Service running? DNS resolving?', 'telnet <ip> <port>, nslookup, show ip nat translations'],
          ] },
          { type: 'callout', variant: 'tip', text: 'Always start by asking: "What changed?" Most network problems are caused by recent changes — a new configuration, a firmware update, a cable that was moved, or a device that was rebooted.' },
        ],
      },
    },
    {
      id: 'm09-l04',
      title: 'Essential Show Commands',
      order: 4,
      type: 'theory',
      estimatedMinutes: 10,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'Essential Show Commands for Troubleshooting' },
          { type: 'paragraph', text: 'These are the commands you will use daily as a network engineer. Master these and you can diagnose almost any problem.' },
          { type: 'heading', level: 2, text: 'show ip interface brief' },
          { type: 'paragraph', text: 'Your number one go-to command. Shows every interface, its IP address, and whether it is up or down in a compact table.' },
          { type: 'code-block', code: 'Router# show ip interface brief\nInterface              IP-Address      OK? Method Status                Protocol\nGigabitEthernet0/0     10.10.10.1      YES manual up                    up\nGigabitEthernet0/1     10.10.20.1      YES manual up                    up\nGigabitEthernet0/2     unassigned      YES unset  administratively down down\nSerial0/0/0            10.10.0.1       YES manual up                    up\n\nKey status combinations:\n  up / up          = Working perfectly\n  up / down        = Physical OK, protocol problem (encapsulation, keepalive)\n  admin down / down = Interface disabled (need "no shutdown")\n  down / down      = Cable problem or no connection on remote end' },
          { type: 'heading', level: 2, text: 'show running-config' },
          { type: 'paragraph', text: 'Shows the current active configuration of the device. Use this to verify any configuration you have applied.' },
          { type: 'code-block', code: 'Router# show running-config\n\n! Too long? Filter it:\nRouter# show running-config | section ospf\n  router ospf 1\n   router-id 1.1.1.1\n   network 10.10.10.0 0.0.0.255 area 0\n\nRouter# show running-config | include ip address\n  ip address 10.10.10.1 255.255.255.0\n  ip address 10.10.20.1 255.255.255.0\n  ip address 10.10.0.1 255.255.255.252\n\nRouter# show running-config interface GigabitEthernet0/0\n  interface GigabitEthernet0/0\n   ip address 10.10.10.1 255.255.255.0\n   no shutdown' },
          { type: 'callout', variant: 'tip', text: 'Use the pipe (|) to filter output: "| include <keyword>" shows matching lines, "| section <keyword>" shows entire config sections, "| begin <keyword>" starts from a matching line.' },
          { type: 'heading', level: 2, text: 'show vlan brief' },
          { type: 'paragraph', text: 'Shows all VLANs on a switch and which ports are assigned to each. Essential for verifying VLAN configuration.' },
          { type: 'code-block', code: 'Switch# show vlan brief\n\nVLAN Name                             Status    Ports\n---- -------------------------------- --------- ----------------------------\n1    default                          active    Gi0/3\n10   Engineering                      active    Gi0/0, Gi0/1\n20   Sales                            active    Gi0/2\n100  Servers                          active\n999  Unused                           active\n\n! If a port is missing from a VLAN, it might be:\n! - Assigned to the wrong VLAN\n! - Configured as a trunk port (trunks do not show here)\n! - Shut down' },
          { type: 'heading', level: 2, text: 'show cdp neighbors' },
          { type: 'paragraph', text: 'Cisco Discovery Protocol reveals directly connected Cisco devices. Shows the neighbor device name, the local interface, and the remote interface.' },
          { type: 'code-block', code: 'Router# show cdp neighbors\n\nDevice ID        Local Intrfce     Holdtme    Capability  Platform  Port ID\nSwitch1          Gig 0/0           170             S       WS-C2960  Gig 0/1\nRouter2          Ser 0/0/0         155             R       ISR4321   Ser 0/0/0\nAP-Floor2        Gig 0/1           140             T       AIR-AP    Gig 0\n\n! Show detailed info for a specific neighbor:\nRouter# show cdp neighbors detail\n\n! Capability codes: R=Router, S=Switch, T=Trans Bridge,\n! B=Source Route Bridge, H=Host, I=IGMP, r=Repeater' },
          { type: 'callout', variant: 'info', text: 'CDP is Cisco-proprietary. For multi-vendor environments, use LLDP (Link Layer Discovery Protocol) which works across all brands.' },
          { type: 'heading', level: 2, text: 'Other Essential Commands' },
          { type: 'comparison-table', headers: ['Command', 'What It Shows', 'When to Use'], rows: [
            ['show ip route', 'Full routing table', 'Verify routes exist, check next-hop'],
            ['show interfaces', 'Detailed interface stats (errors, CRC, drops)', 'Suspected physical layer problems'],
            ['show ip ospf neighbor', 'OSPF neighbor states', 'Verify OSPF adjacencies'],
            ['show access-lists', 'ACL rules and match counts', 'Verify ACLs, check if traffic is being filtered'],
            ['show ip nat translations', 'Active NAT translation table', 'Verify NAT is working'],
            ['show mac address-table', 'Switch MAC address to port mapping', 'Find where a device is connected'],
            ['show spanning-tree', 'STP topology, blocked ports, root bridge', 'Loop issues, convergence problems'],
            ['ping / traceroute', 'Reachability and path to destination', 'First troubleshooting step always'],
          ] },
          { type: 'callout', variant: 'key-concept', text: 'Memorize this troubleshooting flow: (1) show ip int brief (is it up?), (2) ping default gateway (L3 ok?), (3) show ip route (route exists?), (4) traceroute (where does it fail?), (5) show run (config correct?).' },
        ],
      },
    },
    {
      id: 'm09-l05',
      title: 'Lab: Troubleshooting Challenge',
      order: 5,
      type: 'lab',
      labId: 'lab-08-troubleshooting',
      estimatedMinutes: 20,
    },
    {
      id: 'm09-l06',
      title: 'Lab: Server Network',
      order: 6,
      type: 'lab',
      labId: 'lab-05-server-network',
      estimatedMinutes: 20,
    },
    {
      id: 'm09-lab3',
      title: 'Lab: NAS File Server Setup',
      order: 7,
      type: 'lab',
      labId: 'lab-16-nas-file-server',
      estimatedMinutes: 15,
    },
  ],
  quiz: {
    id: 'quiz-module-09',
    moduleId: 'module-09',
    passingScore: 70,
    questions: [
      {
        id: 'q09-01', text: 'What are the three layers of the hierarchical network model?',
        options: [
          { id: 'a', text: 'Physical, Data Link, Network', correct: false },
          { id: 'b', text: 'Core, Distribution, Access', correct: true },
          { id: 'c', text: 'Internet, Transport, Application', correct: false },
          { id: 'd', text: 'LAN, MAN, WAN', correct: false },
        ],
        explanation: 'The Cisco hierarchical model has three layers: Core (high-speed backbone), Distribution (policy and aggregation), and Access (end-user connectivity).',
      },
      {
        id: 'q09-02', text: 'Which layer of the hierarchical model is responsible for applying ACLs, routing, and QoS policies?',
        options: [
          { id: 'a', text: 'Core', correct: false },
          { id: 'b', text: 'Distribution', correct: true },
          { id: 'c', text: 'Access', correct: false },
          { id: 'd', text: 'Transport', correct: false },
        ],
        explanation: 'The distribution layer is the policy layer. It handles routing between VLANs, applies ACLs for security, manages QoS, and aggregates traffic from access switches before sending it to the core.',
      },
      {
        id: 'q09-03', text: 'What subnet mask should be used for a point-to-point link between two routers?',
        options: [
          { id: 'a', text: '/24 (255.255.255.0)', correct: false },
          { id: 'b', text: '/28 (255.255.255.240)', correct: false },
          { id: 'c', text: '/30 (255.255.255.252)', correct: true },
          { id: 'd', text: '/16 (255.255.0.0)', correct: false },
        ],
        explanation: '/30 provides exactly 2 usable host addresses — perfect for a point-to-point link. Using a /24 would waste 252 addresses.',
      },
      {
        id: 'q09-04', text: 'What does VLSM allow you to do?',
        options: [
          { id: 'a', text: 'Use the same subnet mask everywhere', correct: false },
          { id: 'b', text: 'Use different subnet masks within the same network', correct: true },
          { id: 'c', text: 'Eliminate the need for subnetting', correct: false },
          { id: 'd', text: 'Assign MAC addresses dynamically', correct: false },
        ],
        explanation: 'VLSM (Variable Length Subnet Masking) lets you use different prefix lengths for different subnets. A user VLAN might get a /24 while a router link gets a /30.',
      },
      {
        id: 'q09-05', text: 'In the divide-and-conquer troubleshooting approach, which layer do you start at?',
        options: [
          { id: 'a', text: 'Layer 1 (Physical)', correct: false },
          { id: 'b', text: 'Layer 7 (Application)', correct: false },
          { id: 'c', text: 'Layer 3 (Network)', correct: true },
          { id: 'd', text: 'Layer 2 (Data Link)', correct: false },
        ],
        explanation: 'Divide-and-conquer starts at Layer 3 with ping and traceroute. If Layer 3 works, look upward (application issues). If it fails, look downward (physical/data link issues).',
      },
      {
        id: 'q09-06', text: 'A network engineer changes three things simultaneously and the problem is fixed. What is wrong with this approach?',
        options: [
          { id: 'a', text: 'Nothing — it fixed the problem faster', correct: false },
          { id: 'b', text: 'You cannot determine which change actually fixed the issue', correct: true },
          { id: 'c', text: 'Three changes are not enough', correct: false },
          { id: 'd', text: 'Changes should only be made on weekends', correct: false },
        ],
        explanation: 'Always make one change at a time. If you make multiple changes, you do not know which one resolved the issue, and the unnecessary changes may cause new problems.',
      },
      {
        id: 'q09-07', text: 'What does "show cdp neighbors" display?',
        options: [
          { id: 'a', text: 'All devices on the network', correct: false },
          { id: 'b', text: 'Directly connected Cisco devices and their interfaces', correct: true },
          { id: 'c', text: 'OSPF neighbor table', correct: false },
          { id: 'd', text: 'ARP cache entries', correct: false },
        ],
        explanation: 'CDP (Cisco Discovery Protocol) shows directly connected Cisco devices, including their hostname, the local and remote interface, and platform type.',
      },
      {
        id: 'q09-08', text: 'An interface shows status "up" and protocol "down." What does this indicate?',
        options: [
          { id: 'a', text: 'The interface is working perfectly', correct: false },
          { id: 'b', text: 'The interface is administratively disabled', correct: false },
          { id: 'c', text: 'Physical layer is OK but there is a Layer 2 protocol problem', correct: true },
          { id: 'd', text: 'The cable is unplugged', correct: false },
        ],
        explanation: 'Up/down means Layer 1 is fine (cable connected, signals detected) but Layer 2 has an issue — typically encapsulation mismatch, keepalive failure, or clock rate not set on serial links.',
      },
      {
        id: 'q09-09', text: 'What is the primary purpose of the core layer in network design?',
        options: [
          { id: 'a', text: 'Apply security policies and ACLs', correct: false },
          { id: 'b', text: 'Connect end-user devices', correct: false },
          { id: 'c', text: 'Provide high-speed transport with no packet manipulation', correct: true },
          { id: 'd', text: 'Assign IP addresses via DHCP', correct: false },
        ],
        explanation: 'The core layer is the backbone — its only job is to switch packets as fast as possible. No ACLs, no NAT, no complex policy. Keep it fast and simple.',
      },
      {
        id: 'q09-10', text: 'Which command filters "show running-config" to display only the OSPF section?',
        options: [
          { id: 'a', text: 'show running-config | include ospf', correct: false },
          { id: 'b', text: 'show running-config | section ospf', correct: true },
          { id: 'c', text: 'show running-config ospf', correct: false },
          { id: 'd', text: 'show ospf running-config', correct: false },
        ],
        explanation: '"| section ospf" shows the entire OSPF configuration block. "| include ospf" would only show individual lines containing the word "ospf," missing indented sub-commands.',
      },
    ],
  },
  badge: {
    id: 'badge-module-09',
    name: 'Network Engineer',
    description: 'Completed Module 9: Network Design & Troubleshooting. You can design hierarchical networks and systematically troubleshoot issues.',
    icon: '🔧',
    color: '#8888ff',
    tier: 'platinum',
  },
};
