import type { BootcampModule } from '../types.js';

export const module07: BootcampModule = {
  id: 'module-07',
  number: 7,
  title: 'NAT & Internet Access',
  description: 'Why NAT exists, static NAT, dynamic NAT, PAT (overload), configuration commands, and verification.',
  color: '#ffaa00',
  tier: 'gold',
  prerequisites: ['module-06'],
  labIds: ['lab-10-nat-concepts'],
  lessons: [
    {
      id: 'm07-l01',
      title: 'Why NAT Exists',
      order: 1,
      type: 'theory',
      estimatedMinutes: 10,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'Why NAT Exists' },
          { type: 'analogy', text: 'Imagine a large company where every employee has an internal extension number (like 4-digit extensions: 1001, 1002, etc.) but there is only one main phone number for the whole building. When an employee calls outside, the phone system translates their internal extension to the main number. When someone calls back, the system translates the main number back to the right extension. That is exactly what NAT does with IP addresses.' },
          { type: 'paragraph', text: 'Network Address Translation (NAT) is the process of modifying IP addresses in packet headers as they pass through a router or firewall. NAT was invented to solve a critical problem: the internet was running out of IPv4 addresses.' },
          { type: 'heading', level: 2, text: 'The IPv4 Exhaustion Problem' },
          { type: 'paragraph', text: 'IPv4 provides approximately 4.3 billion addresses (2^32). That sounds like a lot, but with billions of devices connected to the internet — phones, laptops, IoT devices, servers — the supply ran out. IANA (the Internet Assigned Numbers Authority) allocated the last blocks of IPv4 addresses in 2011.' },
          { type: 'bullet-list', items: [
            'IPv4 has ~4.3 billion addresses total',
            'Many addresses are reserved (private, loopback, multicast)',
            'The world has far more than 4.3 billion connected devices',
            'IPv6 (128-bit) is the long-term solution, but adoption is slow',
            'NAT is the short-term solution that has kept IPv4 working for decades',
          ] },
          { type: 'heading', level: 2, text: 'How NAT Solves the Problem' },
          { type: 'paragraph', text: 'NAT allows thousands of devices with private IP addresses (192.168.x.x, 10.x.x.x, 172.16-31.x.x) to share a single public IP address. Your entire home or office network appears as ONE address to the internet.' },
          { type: 'key-term', term: 'Inside Local', definition: 'The private IP address assigned to a device on your internal network. Example: 192.168.1.10. This address is NOT routable on the internet.' },
          { type: 'key-term', term: 'Inside Global', definition: 'The public IP address that represents the internal device to the outside world. This is the translated address that appears in packets on the internet. Example: 203.0.113.1.' },
          { type: 'key-term', term: 'Outside Global', definition: 'The real IP address of the destination on the internet. Example: 8.8.8.8 (Google DNS). This is the address as it appears on the public internet.' },
          { type: 'callout', variant: 'key-concept', text: 'NAT translates private (non-routable) addresses to public (routable) addresses. This lets millions of devices share a small pool of public IPs. Without NAT, the internet would have run out of addresses long ago.' },
          { type: 'comparison-table', headers: ['NAT Term', 'Meaning', 'Example'], rows: [
            ['Inside Local', 'Private IP on your LAN', '192.168.1.10'],
            ['Inside Global', 'Public IP representing your device', '203.0.113.1'],
            ['Outside Local', 'How you see the remote destination (usually same as Outside Global)', '8.8.8.8'],
            ['Outside Global', 'Actual IP of the remote destination', '8.8.8.8'],
          ] },
        ],
      },
    },
    {
      id: 'm07-l02',
      title: 'Types of NAT',
      order: 2,
      type: 'theory',
      estimatedMinutes: 12,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'Types of NAT' },
          { type: 'paragraph', text: 'There are three main types of NAT, each suited for different scenarios. Understanding when to use each type is essential for designing networks that connect to the internet.' },
          { type: 'heading', level: 2, text: 'Static NAT (One-to-One)' },
          { type: 'key-term', term: 'Static NAT', definition: 'A permanent, one-to-one mapping between a private IP and a public IP. One private address always translates to the same public address. Used for servers that need to be reachable from the internet (web servers, mail servers).' },
          { type: 'paragraph', text: 'Static NAT is bidirectional — internet users can initiate connections TO the internal server using the public IP. This is necessary for any service that must be accessible from outside.' },
          { type: 'code-block', code: '  Internal server: 192.168.1.100  ←→  Public IP: 203.0.113.10\n\n  Every packet FROM 192.168.1.100 goes out as 203.0.113.10\n  Every packet TO   203.0.113.10 is forwarded to 192.168.1.100\n\n  Use case: Web server, mail server, any public-facing service' },
          { type: 'heading', level: 2, text: 'Dynamic NAT (Many-to-Pool)' },
          { type: 'key-term', term: 'Dynamic NAT', definition: 'Maps private IPs to public IPs from a pool on a first-come, first-served basis. Each internal host gets a temporary public IP from the pool. If the pool is exhausted, new connections are blocked until an address is returned.' },
          { type: 'code-block', code: '  Pool: 203.0.113.10 - 203.0.113.14 (5 public addresses)\n\n  192.168.1.10 → 203.0.113.10 (first available)\n  192.168.1.11 → 203.0.113.11\n  192.168.1.12 → 203.0.113.12\n  ...\n  If all 5 are in use, the 6th host CANNOT get a translation' },
          { type: 'callout', variant: 'info', text: 'Dynamic NAT is rarely used today because it still requires one public IP per active connection. PAT (overload) is far more efficient and has largely replaced dynamic NAT.' },
          { type: 'heading', level: 2, text: 'PAT — Port Address Translation (NAT Overload)' },
          { type: 'key-term', term: 'PAT (Port Address Translation)', definition: 'Also called NAT overload. Maps MANY private IPs to a SINGLE public IP by using unique port numbers to distinguish connections. This is how your home router works — all your devices share one public IP.' },
          { type: 'paragraph', text: 'PAT is the most common form of NAT. It works by appending a unique source port number to each translation. Since port numbers range from 0 to 65535, a single public IP can support thousands of simultaneous connections.' },
          { type: 'code-block', code: '  192.168.1.10:51234 → 203.0.113.1:51234\n  192.168.1.11:49876 → 203.0.113.1:49876\n  192.168.1.12:60100 → 203.0.113.1:60100\n\n  All three devices share ONE public IP (203.0.113.1)\n  The router tracks which port belongs to which internal host' },
          { type: 'comparison-table', headers: ['NAT Type', 'Mapping', 'Public IPs Needed', 'Initiator', 'Use Case'], rows: [
            ['Static NAT', 'One-to-one (permanent)', '1 per server', 'Both directions', 'Public-facing servers'],
            ['Dynamic NAT', 'Many-to-pool (temporary)', '1 per active host', 'Inside only', 'Rarely used today'],
            ['PAT (Overload)', 'Many-to-one (port-based)', '1 for all hosts', 'Inside only', 'Internet access for entire LAN'],
          ] },
          { type: 'callout', variant: 'key-concept', text: 'PAT (NAT overload) is by far the most important type. It allows your entire network to share a single public IP address. Every home router, every corporate edge router, and every cloud NAT gateway uses PAT.' },
        ],
      },
    },
    {
      id: 'm07-l03',
      title: 'NAT Configuration',
      order: 3,
      type: 'theory',
      estimatedMinutes: 12,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'NAT Configuration on Cisco Routers' },
          { type: 'paragraph', text: 'Configuring NAT requires three steps: (1) define which interfaces are inside and outside, (2) define the translation rules, and (3) verify the configuration. This lesson covers all three types.' },
          { type: 'heading', level: 2, text: 'Step 1: Define Inside and Outside Interfaces' },
          { type: 'code-block', code: '! Mark the LAN-facing interface as "inside"\nRouter(config)# interface gi0/0\nRouter(config-if)# ip nat inside\nRouter(config-if)# exit\n\n! Mark the internet-facing interface as "outside"\nRouter(config)# interface gi0/1\nRouter(config-if)# ip nat outside\nRouter(config-if)# exit' },
          { type: 'callout', variant: 'key-concept', text: 'Every NAT configuration starts by labeling interfaces. "ip nat inside" goes on interfaces connected to your private network. "ip nat outside" goes on interfaces connected to the internet or ISP.' },
          { type: 'heading', level: 2, text: 'Static NAT Configuration' },
          { type: 'code-block', code: '! Map internal server 192.168.1.100 to public IP 203.0.113.10\nRouter(config)# ip nat inside source static 192.168.1.100 203.0.113.10\n\n! That is it! One command per static mapping.\n! Now internet users can reach 203.0.113.10 and it forwards to 192.168.1.100' },
          { type: 'heading', level: 2, text: 'Dynamic NAT Configuration' },
          { type: 'code-block', code: '! Step 1: Define the pool of public addresses\nRouter(config)# ip nat pool MY-POOL 203.0.113.10 203.0.113.14 netmask 255.255.255.240\n\n! Step 2: Create an ACL to define which internal hosts can use NAT\nRouter(config)# access-list 1 permit 192.168.1.0 0.0.0.255\n\n! Step 3: Bind the ACL to the pool\nRouter(config)# ip nat inside source list 1 pool MY-POOL' },
          { type: 'heading', level: 2, text: 'PAT (Overload) Configuration' },
          { type: 'paragraph', text: 'PAT is the most common configuration. It lets all internal hosts share the router\'s public IP address.' },
          { type: 'code-block', code: '! Method 1: Overload using the outside interface address\nRouter(config)# access-list 1 permit 192.168.1.0 0.0.0.255\nRouter(config)# ip nat inside source list 1 interface gi0/1 overload\n\n! Method 2: Overload using a pool (with overload keyword)\nRouter(config)# ip nat pool PAT-POOL 203.0.113.1 203.0.113.1 netmask 255.255.255.252\nRouter(config)# ip nat inside source list 1 pool PAT-POOL overload' },
          { type: 'callout', variant: 'tip', text: 'The keyword "overload" is what makes it PAT instead of dynamic NAT. Without "overload," each host gets its own public IP (dynamic NAT). With "overload," all hosts share one public IP using port numbers.' },
          { type: 'heading', level: 2, text: 'Complete PAT Example' },
          { type: 'code-block', code: '! Full configuration for internet access via PAT:\nRouter(config)# interface gi0/0\nRouter(config-if)# ip address 192.168.1.1 255.255.255.0\nRouter(config-if)# ip nat inside\nRouter(config-if)# no shutdown\nRouter(config-if)# exit\n\nRouter(config)# interface gi0/1\nRouter(config-if)# ip address 203.0.113.1 255.255.255.252\nRouter(config-if)# ip nat outside\nRouter(config-if)# no shutdown\nRouter(config-if)# exit\n\nRouter(config)# access-list 1 permit 192.168.1.0 0.0.0.255\nRouter(config)# ip nat inside source list 1 interface gi0/1 overload\nRouter(config)# ip route 0.0.0.0 0.0.0.0 203.0.113.2' },
          { type: 'callout', variant: 'info', text: 'Notice the default route at the end. NAT translates addresses, but you still need a route to the internet. The default route (0.0.0.0/0) sends all internet-bound traffic to the ISP.' },
        ],
      },
    },
    {
      id: 'm07-l04',
      title: 'Verifying NAT',
      order: 4,
      type: 'theory',
      estimatedMinutes: 8,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'Verifying NAT — Show Commands and Troubleshooting' },
          { type: 'paragraph', text: 'After configuring NAT, you must verify it is working correctly. Cisco IOS provides several commands to view active translations, statistics, and troubleshoot issues.' },
          { type: 'heading', level: 2, text: 'show ip nat translations' },
          { type: 'key-term', term: 'NAT Translation Table', definition: 'A table in the router\'s memory that shows all active NAT mappings. Static entries are permanent. Dynamic and PAT entries are created on demand and time out after a period of inactivity.' },
          { type: 'code-block', code: 'Router# show ip nat translations\nPro  Inside global      Inside local       Outside local      Outside global\n---  203.0.113.10       192.168.1.100      ---                ---\ntcp  203.0.113.1:51234  192.168.1.10:51234 8.8.8.8:53         8.8.8.8:53\ntcp  203.0.113.1:49876  192.168.1.11:49876 142.250.80.46:443  142.250.80.46:443\ntcp  203.0.113.1:60100  192.168.1.12:60100 151.101.1.69:80    151.101.1.69:80\n\n! First entry: Static NAT (no protocol, no ports — permanent mapping)\n! Other entries: PAT translations (with protocol and port numbers)' },
          { type: 'heading', level: 2, text: 'show ip nat statistics' },
          { type: 'code-block', code: 'Router# show ip nat statistics\nTotal active translations: 4 (1 static, 3 dynamic)\nOutside interfaces:\n  GigabitEthernet0/1\nInside interfaces:\n  GigabitEthernet0/0\nHits: 15832  Misses: 3\nExpired translations: 127\nDynamic mappings:\n-- Inside Source\n[Id: 1] access-list 1 interface GigabitEthernet0/1 refcount 3' },
          { type: 'heading', level: 2, text: 'Troubleshooting NAT' },
          { type: 'paragraph', text: 'When NAT is not working, follow this systematic troubleshooting approach:' },
          { type: 'numbered-list', items: [
            'Check that interfaces are correctly marked as "ip nat inside" and "ip nat outside"',
            'Verify the ACL matches the correct source addresses (check wildcard mask)',
            'Confirm the NAT statement is correct (static mapping, pool, or overload)',
            'Check "show ip nat translations" — are entries being created?',
            'Check "show ip nat statistics" — are there hits or only misses?',
            'Verify the default route exists to send traffic to the ISP',
            'Use "debug ip nat" to watch translations in real time (use sparingly in production)',
          ] },
          { type: 'callout', variant: 'warning', text: 'Common NAT mistakes: (1) Forgetting "ip nat inside" or "ip nat outside" on interfaces, (2) ACL not matching the correct internal addresses, (3) Missing the "overload" keyword for PAT, (4) No default route to the ISP.' },
          { type: 'heading', level: 2, text: 'Clearing NAT Translations' },
          { type: 'code-block', code: '! Clear all dynamic NAT translations (does not affect static entries)\nRouter# clear ip nat translation *\n\n! Clear a specific translation\nRouter# clear ip nat translation inside 192.168.1.10 outside 8.8.8.8\n\n! Useful when troubleshooting — forces new translations to be created' },
          { type: 'comparison-table', headers: ['Command', 'Purpose'], rows: [
            ['show ip nat translations', 'Display all active NAT mappings (inside/outside pairs)'],
            ['show ip nat statistics', 'Show hit/miss counts, active translations, and interface assignments'],
            ['clear ip nat translation *', 'Remove all dynamic translations (forces re-creation)'],
            ['debug ip nat', 'Real-time view of NAT operations (use carefully — high CPU)'],
          ] },
          { type: 'callout', variant: 'tip', text: '"show ip nat translations" is the single most important NAT verification command. If you see entries appearing, NAT is working. If the table is empty (except static entries), traffic is not being matched by your ACL.' },
        ],
      },
    },
    {
      id: 'm07-l05',
      title: 'Lab: NAT Concepts',
      order: 5,
      type: 'lab',
      labId: 'lab-10-nat-concepts',
      estimatedMinutes: 15,
    },
  ],
  quiz: {
    id: 'quiz-module-07',
    moduleId: 'module-07',
    passingScore: 70,
    questions: [
      {
        id: 'q07-01', text: 'Why was NAT invented?',
        options: [
          { id: 'a', text: 'To encrypt network traffic', correct: false },
          { id: 'b', text: 'To solve IPv4 address exhaustion', correct: true },
          { id: 'c', text: 'To replace DNS', correct: false },
          { id: 'd', text: 'To speed up routing', correct: false },
        ],
        explanation: 'NAT was invented because IPv4 has only ~4.3 billion addresses, which is not enough for all the world\'s devices. NAT lets many private addresses share a few public addresses.',
      },
      {
        id: 'q07-02', text: 'What type of NAT maps many private IPs to one public IP using port numbers?',
        options: [
          { id: 'a', text: 'Static NAT', correct: false },
          { id: 'b', text: 'Dynamic NAT', correct: false },
          { id: 'c', text: 'PAT (Port Address Translation)', correct: true },
          { id: 'd', text: 'Reverse NAT', correct: false },
        ],
        explanation: 'PAT (also called NAT overload) uses unique port numbers to map thousands of private IPs to a single public IP. This is the most common type of NAT.',
      },
      {
        id: 'q07-03', text: 'Which NAT type should you use for a web server that must be reachable from the internet?',
        options: [
          { id: 'a', text: 'PAT', correct: false },
          { id: 'b', text: 'Static NAT', correct: true },
          { id: 'c', text: 'Dynamic NAT', correct: false },
          { id: 'd', text: 'No NAT needed', correct: false },
        ],
        explanation: 'Static NAT creates a permanent one-to-one mapping. Internet users can always reach the server via its public IP, and the router translates it to the private IP. PAT only works for outbound connections.',
      },
      {
        id: 'q07-04', text: 'What does "Inside Local" mean in NAT terminology?',
        options: [
          { id: 'a', text: 'The public IP assigned by the ISP', correct: false },
          { id: 'b', text: 'The private IP address of the internal device', correct: true },
          { id: 'c', text: 'The IP address of the remote server', correct: false },
          { id: 'd', text: 'The loopback address', correct: false },
        ],
        explanation: 'Inside Local is the private IP address on your internal network (e.g., 192.168.1.10). Inside Global is the public IP that represents it on the internet.',
      },
      {
        id: 'q07-05', text: 'Which command marks a router interface as the internal (LAN) side for NAT?',
        options: [
          { id: 'a', text: 'ip nat outside', correct: false },
          { id: 'b', text: 'ip nat enable', correct: false },
          { id: 'c', text: 'ip nat inside', correct: true },
          { id: 'd', text: 'nat interface inside', correct: false },
        ],
        explanation: '"ip nat inside" is configured on the LAN-facing interface. "ip nat outside" goes on the internet-facing interface. Both must be configured for NAT to work.',
      },
      {
        id: 'q07-06', text: 'What keyword makes dynamic NAT become PAT?',
        options: [
          { id: 'a', text: 'pat', correct: false },
          { id: 'b', text: 'port-translate', correct: false },
          { id: 'c', text: 'overload', correct: true },
          { id: 'd', text: 'share', correct: false },
        ],
        explanation: 'The "overload" keyword at the end of "ip nat inside source list ... overload" enables PAT. Without it, the command configures dynamic NAT (one-to-one from a pool).',
      },
      {
        id: 'q07-07', text: 'Which command shows all active NAT mappings on a Cisco router?',
        options: [
          { id: 'a', text: 'show ip nat statistics', correct: false },
          { id: 'b', text: 'show ip nat translations', correct: true },
          { id: 'c', text: 'show nat table', correct: false },
          { id: 'd', text: 'show ip route nat', correct: false },
        ],
        explanation: '"show ip nat translations" displays the NAT translation table showing all inside local/global and outside local/global address pairs.',
      },
      {
        id: 'q07-08', text: 'A router has NAT configured but "show ip nat translations" shows no entries. What is the most likely cause?',
        options: [
          { id: 'a', text: 'NAT is working fine — the table is always empty', correct: false },
          { id: 'b', text: 'The ACL is not matching the source addresses', correct: true },
          { id: 'c', text: 'The router needs to be rebooted', correct: false },
          { id: 'd', text: 'NAT only works with IPv6', correct: false },
        ],
        explanation: 'If the NAT translation table is empty, traffic is not being matched. The most common cause is an ACL that does not match the internal source addresses (wrong network, wrong wildcard mask).',
      },
    ],
  },
  badge: {
    id: 'badge-module-07',
    name: 'Internet Gatekeeper',
    description: 'Completed Module 7: NAT & Internet Access. You understand how private networks connect to the internet through Network Address Translation.',
    icon: '🌍',
    color: '#ffaa00',
    tier: 'gold',
  },
};
