import type { BootcampModule } from '../types.js';

export const module05: BootcampModule = {
  id: 'module-05',
  number: 5,
  title: 'Routing Fundamentals',
  description: 'How routers make forwarding decisions, static routes, routing tables, and the default gateway.',
  color: '#ff8844',
  tier: 'silver',
  prerequisites: ['module-04'],
  labIds: ['lab-07-static-routing'],
  lessons: [
    {
      id: 'm05-l01',
      title: 'What Routers Do',
      order: 1,
      type: 'theory',
      estimatedMinutes: 10,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'What Routers Do' },
          { type: 'analogy', text: 'A router is like a post office at a city border. When a letter arrives, the post office checks the destination zip code. If the destination is local, it delivers it. If the destination is in another city, it forwards the letter to the next post office along the route. Routers do the same thing with IP packets.' },
          { type: 'paragraph', text: 'Routers operate at Layer 3 (Network) and connect different networks together. While switches forward frames within a single network using MAC addresses, routers forward packets between networks using IP addresses. Every time traffic crosses a network boundary, a router is involved.' },
          { type: 'diagram', diagram: { type: 'network-topology', data: { devices: [{ label: 'PC1', x: 60, y: 80, type: 'pc' }, { label: 'Switch1', x: 170, y: 80, type: 'switch' }, { label: 'Router', x: 290, y: 80, type: 'router' }, { label: 'Switch2', x: 400, y: 80, type: 'switch' }, { label: 'PC2', x: 500, y: 80, type: 'pc' }], links: [[0, 1], [1, 2], [2, 3], [3, 4]] }, caption: 'Router connects two separate networks — PC1 (192.168.1.0/24) and PC2 (10.0.0.0/24) can communicate through the Router' } },
          { type: 'heading', level: 2, text: 'The Routing Table' },
          { type: 'key-term', term: 'Routing Table', definition: 'A database stored in a router\'s memory that lists all known destination networks and how to reach them. Every packet is looked up against this table to determine the next hop.' },
          { type: 'paragraph', text: 'The routing table contains entries for each known network. Each entry tells the router: "To reach network X, send the packet to next-hop Y via interface Z."' },
          { type: 'code-block', code: 'Router# show ip route\nCodes: C - connected, S - static, R - RIP, O - OSPF\n\nGateway of last resort is not set\n\nC    192.168.1.0/24 is directly connected, GigabitEthernet0/0\nC    192.168.2.0/24 is directly connected, GigabitEthernet0/1\nS    10.0.0.0/8 [1/0] via 192.168.2.2' },
          { type: 'heading', level: 2, text: 'How Routes Get Into the Table' },
          { type: 'comparison-table', headers: ['Route Type', 'Code', 'How It Works'], rows: [
            ['Connected', 'C', 'Automatically added when you configure an IP on an interface and it goes "up/up"'],
            ['Static', 'S', 'Manually configured by an administrator using the "ip route" command'],
            ['Dynamic', 'O, R, D', 'Learned automatically from other routers via routing protocols (OSPF, RIP, EIGRP)'],
          ] },
          { type: 'callout', variant: 'key-concept', text: 'Connected routes appear automatically. Static routes are manually configured. Dynamic routes are learned from other routers. In this module, we focus on connected and static routes.' },
          { type: 'heading', level: 2, text: 'Routers Break Up Broadcast Domains' },
          { type: 'paragraph', text: 'A broadcast sent on one router interface does NOT cross to the other side. Each router interface is a separate broadcast domain. This is why routers are used between VLANs and between network segments — they contain broadcasts and improve performance.' },
          { type: 'bullet-list', items: [
            'Each router interface connects to a different network',
            'Each interface has its own IP address in that network\'s subnet',
            'Broadcasts stop at the router — they do not cross interfaces',
            'This is fundamentally different from a switch, where broadcasts go everywhere',
          ] },
        ],
      },
    },
    {
      id: 'm05-l02',
      title: 'Static Routes',
      order: 2,
      type: 'theory',
      estimatedMinutes: 10,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'Static Routes — Manual Routing' },
          { type: 'paragraph', text: 'A static route is a manually configured entry in the routing table. You tell the router: "To reach this destination network, send the packet to this next-hop address." Static routes are simple, predictable, and perfect for small networks.' },
          { type: 'heading', level: 2, text: 'The ip route Command' },
          { type: 'code-block', code: 'Router(config)# ip route <destination-network> <subnet-mask> <next-hop-ip>\n\n! Example: To reach 10.0.0.0/24, send to 192.168.1.2\nRouter(config)# ip route 10.0.0.0 255.255.255.0 192.168.1.2\n\n! You can also specify the exit interface instead of a next-hop\nRouter(config)# ip route 10.0.0.0 255.255.255.0 GigabitEthernet0/1' },
          { type: 'key-term', term: 'Next-Hop Address', definition: 'The IP address of the next router in the path toward the destination. Your router does not need to know the entire path — just the next step.' },
          { type: 'key-term', term: 'Exit Interface', definition: 'The local router interface to send the packet out of. Alternative to specifying a next-hop IP. Used on point-to-point links.' },
          { type: 'heading', level: 2, text: 'Static Route Example' },
          { type: 'paragraph', text: 'Consider two routers: R1 connects to 192.168.1.0/24 and R2 connects to 192.168.2.0/24. They share a link on 10.0.0.0/30.' },
          { type: 'code-block', code: '  [PC1] --- 192.168.1.0/24 --- [R1] ---10.0.0.0/30--- [R2] --- 192.168.2.0/24 --- [PC2]\n       .10                .1     .1              .2     .1                      .10\n\n! On R1: to reach 192.168.2.0, go to R2\nR1(config)# ip route 192.168.2.0 255.255.255.0 10.0.0.2\n\n! On R2: to reach 192.168.1.0, go to R1\nR2(config)# ip route 192.168.1.0 255.255.255.0 10.0.0.1\n\n! Verify:\nR1# show ip route\nC    192.168.1.0/24 is directly connected, Gi0/0\nC    10.0.0.0/30 is directly connected, Gi0/1\nS    192.168.2.0/24 [1/0] via 10.0.0.2' },
          { type: 'callout', variant: 'warning', text: 'Static routes are ONE-DIRECTIONAL. If R1 has a route to R2\'s network, R2 also needs a route back to R1\'s network. Otherwise, packets go one way but replies cannot return. Always configure routes in both directions.' },
          { type: 'heading', level: 2, text: 'When to Use Static Routes' },
          { type: 'bullet-list', items: [
            'Small networks with only 2-3 routers',
            'Stub networks with only one exit point',
            'Default routes (route of last resort) to an ISP',
            'When you need full control over the routing path',
            'For backup routes in case a dynamic route fails',
          ] },
          { type: 'callout', variant: 'info', text: 'Static routes have an administrative distance of 1, making them highly trusted. Connected routes have AD 0 (most trusted). Dynamic protocols like OSPF have AD 110.' },
        ],
      },
    },
    {
      id: 'm05-l03',
      title: 'How Routing Decisions Work',
      order: 3,
      type: 'theory',
      estimatedMinutes: 10,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'How Routing Decisions Work' },
          { type: 'paragraph', text: 'When a router receives a packet, it must decide where to send it. This process happens for every single packet and must be extremely fast — modern routers handle millions of packets per second.' },
          { type: 'heading', level: 2, text: 'The Routing Decision Process' },
          { type: 'numbered-list', items: [
            'Packet arrives on an interface',
            'Router reads the destination IP address from the packet header',
            'Router looks up the destination IP in the routing table',
            'Router finds the best matching route (longest prefix match)',
            'Router forwards the packet to the next-hop or exit interface',
            'If no matching route is found, the packet is DROPPED',
          ] },
          { type: 'heading', level: 2, text: 'Longest Prefix Match' },
          { type: 'key-term', term: 'Longest Prefix Match', definition: 'When multiple routes match a destination, the router picks the route with the longest (most specific) subnet mask. A /28 is preferred over a /24, which is preferred over a /16. More specific = better match.' },
          { type: 'paragraph', text: 'This is the single most important routing concept. The router always prefers the most specific route.' },
          { type: 'code-block', code: '! Routing table has these entries:\nS    10.0.0.0/8 [1/0] via 192.168.1.1        (matches 10.anything)\nS    10.1.0.0/16 [1/0] via 192.168.1.2       (matches 10.1.anything)\nS    10.1.1.0/24 [1/0] via 192.168.1.3       (matches 10.1.1.anything)\n\n! Packet destined for 10.1.1.50:\n!   Matches 10.0.0.0/8?      YES (8-bit match)\n!   Matches 10.1.0.0/16?     YES (16-bit match)\n!   Matches 10.1.1.0/24?     YES (24-bit match)  ← WINNER (longest match)\n!\n! Router forwards packet via 192.168.1.3' },
          { type: 'callout', variant: 'key-concept', text: 'Longest prefix match: The route with the most matching bits wins. /24 beats /16 beats /8. This is how routers handle overlapping routes — more specific always wins.' },
          { type: 'heading', level: 2, text: 'Connected Routes' },
          { type: 'paragraph', text: 'When you configure an IP address on a router interface and bring it up, the router automatically adds a "connected" route for that subnet. Connected routes are the most trusted (administrative distance 0) and require no manual configuration.' },
          { type: 'code-block', code: 'Router(config)# interface gi0/0\nRouter(config-if)# ip address 192.168.1.1 255.255.255.0\nRouter(config-if)# no shutdown\n\n! This automatically creates:\n! C    192.168.1.0/24 is directly connected, GigabitEthernet0/0\n! Router now knows: "To reach 192.168.1.x, use Gi0/0"' },
          { type: 'callout', variant: 'tip', text: 'If a packet has no matching route at all, the router drops it and may send an ICMP "destination unreachable" message back to the sender. This is why default routes are so important.' },
        ],
      },
    },
    {
      id: 'm05-l04',
      title: 'Default Gateway',
      order: 4,
      type: 'theory',
      estimatedMinutes: 8,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'The Default Gateway' },
          { type: 'analogy', text: 'The default gateway is like the front door of your house. Every time you need to go somewhere outside your neighborhood (subnet), you walk to the front door first. The default gateway is the router interface that PCs use to send traffic outside their local network.' },
          { type: 'paragraph', text: 'End devices like PCs and servers do not have routing tables like routers do. They only know one thing: "If the destination is not on my local subnet, send the packet to my default gateway." The default gateway is always a router interface on the same subnet as the PC.' },
          { type: 'heading', level: 2, text: 'How It Works' },
          { type: 'numbered-list', items: [
            'PC wants to reach 8.8.8.8 (Google DNS)',
            'PC checks: "Is 8.8.8.8 on my subnet (192.168.1.0/24)?" — No.',
            'PC sends the packet to its default gateway (192.168.1.1)',
            'The router at 192.168.1.1 receives the packet and routes it forward',
            'The packet hops from router to router until it reaches 8.8.8.8',
          ] },
          { type: 'heading', level: 2, text: 'Configuring the Default Gateway' },
          { type: 'code-block', code: '! On a Cisco router (this becomes the gateway for the LAN):\nRouter(config)# interface gi0/0\nRouter(config-if)# ip address 192.168.1.1 255.255.255.0\nRouter(config-if)# no shutdown\n\n! On a PC (static configuration):\n! IP Address:      192.168.1.10\n! Subnet Mask:     255.255.255.0\n! Default Gateway: 192.168.1.1   ← points to the router\n\n! On the router, configure a default route to the ISP:\nRouter(config)# ip route 0.0.0.0 0.0.0.0 203.0.113.1' },
          { type: 'heading', level: 2, text: 'Default Route on the Router' },
          { type: 'key-term', term: 'Default Route', definition: 'A static route that matches ALL destinations: ip route 0.0.0.0 0.0.0.0 <next-hop>. It is the "route of last resort." If no other route matches, the router uses the default route.' },
          { type: 'key-term', term: 'Gateway of Last Resort', definition: 'The next-hop defined in the default route. Shown in "show ip route" output. If this is "not set," the router has no default route and will drop packets with no matching entry.' },
          { type: 'callout', variant: 'key-concept', text: 'PCs use a default gateway (the nearest router). Routers use a default route (0.0.0.0/0 pointing to the ISP). Together, these ensure traffic can always find its way out of the network to the internet.' },
          { type: 'comparison-table', headers: ['Term', 'Used By', 'Configuration'], rows: [
            ['Default Gateway', 'End devices (PCs, servers)', 'IP setting on the device — points to the local router'],
            ['Default Route', 'Routers', 'ip route 0.0.0.0 0.0.0.0 <next-hop> — the route of last resort'],
          ] },
          { type: 'callout', variant: 'warning', text: 'If a PC has the wrong default gateway (or none at all), it can only communicate with devices on its own subnet. This is one of the most common connectivity issues — always check the gateway first.' },
        ],
      },
    },
    {
      id: 'm05-l05',
      title: 'Lab: Static Routing',
      order: 5,
      type: 'lab',
      labId: 'lab-07-static-routing',
      estimatedMinutes: 15,
    },
  ],
  quiz: {
    id: 'quiz-module-05',
    moduleId: 'module-05',
    passingScore: 70,
    questions: [
      {
        id: 'q05-01', text: 'At which OSI layer do routers operate?',
        options: [
          { id: 'a', text: 'Layer 1 (Physical)', correct: false },
          { id: 'b', text: 'Layer 2 (Data Link)', correct: false },
          { id: 'c', text: 'Layer 3 (Network)', correct: true },
          { id: 'd', text: 'Layer 4 (Transport)', correct: false },
        ],
        explanation: 'Routers operate at Layer 3 (Network) and make forwarding decisions based on IP addresses. Switches operate at Layer 2 using MAC addresses.',
      },
      {
        id: 'q05-02', text: 'What command configures a static route to 10.0.0.0/24 via next-hop 192.168.1.2?',
        options: [
          { id: 'a', text: 'ip route 10.0.0.0 255.255.255.0 192.168.1.2', correct: true },
          { id: 'b', text: 'route add 10.0.0.0/24 192.168.1.2', correct: false },
          { id: 'c', text: 'static-route 10.0.0.0 192.168.1.2', correct: false },
          { id: 'd', text: 'ip route 10.0.0.0 /24 192.168.1.2', correct: false },
        ],
        explanation: 'The Cisco IOS syntax is "ip route <network> <mask> <next-hop>". The subnet mask uses dotted decimal (255.255.255.0), not CIDR notation (/24).',
      },
      {
        id: 'q05-03', text: 'A routing table has entries for 10.0.0.0/8, 10.1.0.0/16, and 10.1.1.0/24. A packet is destined for 10.1.1.50. Which route is used?',
        options: [
          { id: 'a', text: '10.0.0.0/8', correct: false },
          { id: 'b', text: '10.1.0.0/16', correct: false },
          { id: 'c', text: '10.1.1.0/24', correct: true },
          { id: 'd', text: 'The packet is dropped', correct: false },
        ],
        explanation: 'Longest prefix match: /24 is the most specific match (24 bits match). It wins over /16 (16 bits) and /8 (8 bits). The router always prefers the most specific route.',
      },
      {
        id: 'q05-04', text: 'What type of route is automatically added when you configure an IP on a router interface?',
        options: [
          { id: 'a', text: 'Static route', correct: false },
          { id: 'b', text: 'Connected route', correct: true },
          { id: 'c', text: 'Dynamic route', correct: false },
          { id: 'd', text: 'Default route', correct: false },
        ],
        explanation: 'Connected routes (marked "C" in the routing table) are automatically created when an interface has an IP address and is in "up/up" state. No manual configuration is needed.',
      },
      {
        id: 'q05-05', text: 'What happens when a router receives a packet with no matching route in its routing table?',
        options: [
          { id: 'a', text: 'It broadcasts the packet to all interfaces', correct: false },
          { id: 'b', text: 'It sends the packet back to the source', correct: false },
          { id: 'c', text: 'It drops the packet', correct: true },
          { id: 'd', text: 'It stores the packet until a route is learned', correct: false },
        ],
        explanation: 'If no route matches (and there is no default route), the router drops the packet. It may send an ICMP "destination unreachable" message back to the source.',
      },
      {
        id: 'q05-06', text: 'What is the default route in Cisco IOS?',
        options: [
          { id: 'a', text: 'ip route 255.255.255.255 0.0.0.0 <next-hop>', correct: false },
          { id: 'b', text: 'ip route 0.0.0.0 0.0.0.0 <next-hop>', correct: true },
          { id: 'c', text: 'ip default-route <next-hop>', correct: false },
          { id: 'd', text: 'ip route default <next-hop>', correct: false },
        ],
        explanation: 'The default route is "ip route 0.0.0.0 0.0.0.0 <next-hop>". Network 0.0.0.0 with mask 0.0.0.0 matches ALL destinations. It is the route of last resort.',
      },
      {
        id: 'q05-07', text: 'A PC has IP 192.168.1.10/24. What should its default gateway be?',
        options: [
          { id: 'a', text: 'Any IP address on the internet', correct: false },
          { id: 'b', text: 'A router interface IP on the 192.168.1.0/24 subnet', correct: true },
          { id: 'c', text: 'The broadcast address 192.168.1.255', correct: false },
          { id: 'd', text: 'The IP of the nearest switch', correct: false },
        ],
        explanation: 'The default gateway must be a router interface on the same subnet as the PC. The PC sends all non-local traffic to this gateway. Commonly this is 192.168.1.1.',
      },
      {
        id: 'q05-08', text: 'Why must static routes be configured in both directions?',
        options: [
          { id: 'a', text: 'Because routers only have one interface', correct: false },
          { id: 'b', text: 'Because packets need a path forward AND replies need a path back', correct: true },
          { id: 'c', text: 'Because static routes expire after 60 seconds', correct: false },
          { id: 'd', text: 'Because Cisco requires it for security', correct: false },
        ],
        explanation: 'Communication is bidirectional. If Router A knows how to reach Router B\'s network but Router B does not know how to reach Router A\'s network, reply packets will be dropped.',
      },
    ],
  },
  badge: {
    id: 'badge-module-05',
    name: 'Routing Apprentice',
    description: 'Completed Module 5: Routing Fundamentals. You understand how routers make forwarding decisions and can configure static routes.',
    icon: '🛤️',
    color: '#ff8844',
    tier: 'silver',
  },
};
