import type { BootcampModule } from '../types.js';

export const module08: BootcampModule = {
  id: 'module-08',
  number: 8,
  title: 'Dynamic Routing — OSPF',
  description: 'Link-state routing, OSPF areas, neighbor discovery, adjacency formation, and automatic route calculation.',
  color: '#00cc99',
  tier: 'gold',
  prerequisites: ['module-07'],
  labIds: ['lab-11-ospf-routing'],
  lessons: [
    {
      id: 'm08-l01',
      title: 'Why Dynamic Routing?',
      order: 1,
      type: 'theory',
      estimatedMinutes: 8,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'Why Dynamic Routing?' },
          { type: 'analogy', text: 'Imagine you are a delivery driver who has memorized every route in a small town (static routing). Now your company expands to 50 cities. Memorizing every street is impossible — you need a GPS that automatically discovers and updates routes. That GPS is dynamic routing.' },
          { type: 'paragraph', text: 'In previous modules you configured static routes by hand. That works fine for small networks with a few routers. But what happens when your network grows to 20, 50, or 500 routers?' },
          { type: 'heading', level: 2, text: 'Limitations of Static Routing at Scale' },
          { type: 'bullet-list', items: [
            'Every route must be manually configured on every router',
            'If a link goes down, static routes do not adapt — traffic is dropped until an engineer fixes it',
            'Adding a new subnet means updating every router in the network',
            'Human error increases as the number of routes grows',
            'No load balancing across multiple equal-cost paths',
          ] },
          { type: 'callout', variant: 'key-concept', text: 'Static routing does not scale. Dynamic routing protocols let routers discover networks automatically, adapt when links fail, and choose the best path in real time.' },
          { type: 'heading', level: 2, text: 'Types of Dynamic Routing Protocols' },
          { type: 'comparison-table', headers: ['Type', 'How It Works', 'Examples', 'Best For'], rows: [
            ['Distance Vector', 'Routers share their routing tables with neighbors periodically', 'RIP, EIGRP', 'Small networks, simple setup'],
            ['Link-State', 'Routers share the state of their links; each builds a full map of the network', 'OSPF, IS-IS', 'Medium to large networks'],
            ['Path Vector', 'Shares path attributes between autonomous systems', 'BGP', 'Internet backbone, ISP peering'],
          ] },
          { type: 'callout', variant: 'info', text: 'This module focuses on OSPF (Open Shortest Path First) — the most widely used interior routing protocol in enterprise networks. It is also a major topic on the CCNA exam.' },
          { type: 'heading', level: 2, text: 'Dynamic vs Static: When to Use Each' },
          { type: 'bullet-list', items: [
            'Static routes: stub networks, default routes to ISP, very small networks',
            'Dynamic routing: anything with more than a handful of routers or where redundancy matters',
            'Many networks use BOTH — dynamic for the core, static for edges',
          ] },
        ],
      },
    },
    {
      id: 'm08-l02',
      title: 'OSPF Concepts',
      order: 2,
      type: 'theory',
      estimatedMinutes: 15,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'OSPF — Open Shortest Path First' },
          { type: 'paragraph', text: 'OSPF is a link-state routing protocol defined in RFC 2328. Every OSPF router builds a complete map (topology) of the network and then uses Dijkstra\'s Shortest Path First (SPF) algorithm to calculate the best route to every destination.' },
          { type: 'heading', level: 2, text: 'Link-State Fundamentals' },
          { type: 'analogy', text: 'Think of link-state routing like a group of friends mapping a city. Each person explores their own neighborhood and shares a detailed report with everyone else. Once everyone has all the reports, they each independently build the same complete city map and can find the shortest route anywhere.' },
          { type: 'numbered-list', items: [
            'Each router discovers its directly connected neighbors',
            'Each router builds a Link-State Advertisement (LSA) describing its links',
            'LSAs are flooded to all routers in the area',
            'Every router builds an identical Link-State Database (LSDB)',
            'Each router independently runs the SPF algorithm to build the routing table',
          ] },
          { type: 'callout', variant: 'key-concept', text: 'In OSPF, every router in an area has the SAME link-state database. Each router calculates its own best paths independently using the SPF algorithm.' },
          { type: 'heading', level: 2, text: 'OSPF Areas' },
          { type: 'paragraph', text: 'Large OSPF networks are divided into areas to reduce the size of the link-state database and limit the scope of SPF calculations. Area 0 (the backbone) is required and all other areas must connect to it.' },
          { type: 'key-term', term: 'Area 0 (Backbone Area)', definition: 'The central area that all other areas must connect to. All inter-area traffic passes through Area 0. Every OSPF network must have one.' },
          { type: 'key-term', term: 'Area Border Router (ABR)', definition: 'A router that has interfaces in two or more areas. It connects non-backbone areas to the backbone and summarizes routes between them.' },
          { type: 'key-term', term: 'Autonomous System Boundary Router (ASBR)', definition: 'A router that connects the OSPF domain to an external network (like the internet or a different routing protocol).' },
          { type: 'callout', variant: 'tip', text: 'For small to medium networks, you can put everything in Area 0. Multi-area OSPF is for larger deployments with hundreds of routers.' },
          { type: 'heading', level: 2, text: 'Hello Packets and Neighbor Discovery' },
          { type: 'paragraph', text: 'OSPF routers find each other by sending Hello packets on each OSPF-enabled interface. Hello packets are sent to the multicast address 224.0.0.5 (AllSPFRouters) every 10 seconds on broadcast networks.' },
          { type: 'bullet-list', items: [
            'Hello packets carry the router ID, area ID, hello/dead timers, network mask, and authentication info',
            'Two routers become neighbors when their hello/dead timers, area ID, subnet mask, and authentication match',
            'Default hello timer: 10 seconds on broadcast networks, 30 seconds on NBMA',
            'Default dead timer: 4x the hello timer (40 seconds on broadcast)',
          ] },
          { type: 'heading', level: 2, text: 'Adjacency Formation' },
          { type: 'paragraph', text: 'After discovering a neighbor, routers go through a series of states to form a full adjacency and synchronize their databases:' },
          { type: 'numbered-list', items: [
            'Down — No hellos received from this neighbor yet',
            'Init — Hello received, but two-way communication not confirmed',
            'Two-Way — Both routers see each other in hello packets; DR/BDR election happens here',
            'ExStart — Routers negotiate who starts the database exchange (master/slave)',
            'Exchange — Routers send Database Description (DBD) packets summarizing their LSDB',
            'Loading — Routers request missing LSAs from each other using LSR/LSU packets',
            'Full — Databases are synchronized; adjacency is fully formed',
          ] },
          { type: 'callout', variant: 'warning', text: 'If neighbors are stuck in ExStart or Exchange state, it usually means an MTU mismatch between the two interfaces. Check "show ip ospf interface" to verify.' },
          { type: 'heading', level: 2, text: 'DR and BDR Election' },
          { type: 'paragraph', text: 'On multi-access networks (like Ethernet), OSPF elects a Designated Router (DR) and Backup Designated Router (BDR) to reduce the number of adjacencies and LSA flooding.' },
          { type: 'key-term', term: 'DR (Designated Router)', definition: 'The central point for LSA distribution on a multi-access segment. All other routers form adjacencies with the DR instead of with each other. Reduces O(n^2) adjacencies to O(n).' },
          { type: 'key-term', term: 'BDR (Backup Designated Router)', definition: 'Takes over if the DR fails. Also forms full adjacencies with all routers on the segment. Provides redundancy.' },
          { type: 'bullet-list', items: [
            'Highest OSPF priority wins (default priority = 1, range 0-255)',
            'Priority 0 means "never become DR/BDR"',
            'If priority is tied, highest Router ID wins',
            'DR election is NOT preemptive — a new router with higher priority does not take over',
          ] },
          { type: 'heading', level: 2, text: 'OSPF Cost Metric' },
          { type: 'paragraph', text: 'OSPF uses cost as its metric. Cost is calculated as: Reference Bandwidth / Interface Bandwidth. The default reference bandwidth is 100 Mbps.' },
          { type: 'code-block', code: 'OSPF Cost = Reference BW / Interface BW\n\nDefault Reference Bandwidth: 100 Mbps\n\nFastEthernet (100 Mbps):  100 / 100   = 1\nGigabitEthernet (1 Gbps): 100 / 1000  = 1  (same as FastEthernet!)\n10G Ethernet:             100 / 10000 = 1  (still 1!)\n\nFix: Change reference bandwidth to 10000 (10 Gbps)\nRouter(config-router)# auto-cost reference-bandwidth 10000\n\nNow:\nFastEthernet:  10000 / 100   = 100\nGigabitEthernet: 10000 / 1000 = 10\n10G Ethernet:  10000 / 10000 = 1' },
          { type: 'callout', variant: 'warning', text: 'The default reference bandwidth of 100 Mbps makes all links GigabitEthernet and above have a cost of 1. Always set "auto-cost reference-bandwidth" consistently on ALL routers in the OSPF domain.' },
        ],
      },
    },
    {
      id: 'm08-l03',
      title: 'OSPF Configuration',
      order: 3,
      type: 'theory',
      estimatedMinutes: 12,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'Configuring OSPF on Cisco Routers' },
          { type: 'paragraph', text: 'OSPF configuration involves three key steps: enabling the OSPF process, advertising networks with wildcard masks, and optionally setting the router ID.' },
          { type: 'heading', level: 2, text: 'Step 1: Enable OSPF' },
          { type: 'code-block', code: 'Router(config)# router ospf 1\n\n! The number (1) is the PROCESS ID — local to this router only.\n! It does NOT need to match between routers.\n! You can run multiple OSPF processes (rare).' },
          { type: 'callout', variant: 'info', text: 'The OSPF process ID is locally significant. Router A can use "router ospf 1" and Router B can use "router ospf 99" — they will still form a neighbor relationship.' },
          { type: 'heading', level: 2, text: 'Step 2: Advertise Networks' },
          { type: 'paragraph', text: 'The "network" command tells OSPF which interfaces to enable and which area they belong to. It uses a wildcard mask (inverse of subnet mask).' },
          { type: 'code-block', code: 'Router(config-router)# network 192.168.1.0 0.0.0.255 area 0\nRouter(config-router)# network 10.0.0.0 0.0.0.3 area 0\n\n! Wildcard mask = inverse of subnet mask\n! 255.255.255.0 subnet → 0.0.0.255 wildcard\n! 255.255.255.252 subnet → 0.0.0.3 wildcard\n\n! This enables OSPF on any interface whose IP falls within\n! the network + wildcard range, and assigns it to the area.' },
          { type: 'heading', level: 2, text: 'Understanding Wildcard Masks' },
          { type: 'key-term', term: 'Wildcard Mask', definition: 'The inverse of a subnet mask. Where the subnet mask has 1s, the wildcard has 0s, and vice versa. A 0 means "must match exactly" and a 1 means "don\'t care." Subtract each octet from 255 to convert.' },
          { type: 'comparison-table', headers: ['Subnet Mask', 'Wildcard Mask', 'Matches'], rows: [
            ['255.255.255.0', '0.0.0.255', 'Any host in a /24 network'],
            ['255.255.255.252', '0.0.0.3', 'Any host in a /30 network'],
            ['255.255.255.255', '0.0.0.0', 'Exact single host match'],
            ['255.255.0.0', '0.0.255.255', 'Any host in a /16 network'],
          ] },
          { type: 'callout', variant: 'tip', text: 'Shortcut: 255 - subnet_octet = wildcard_octet. For 255.255.255.192: 255-255=0, 255-255=0, 255-255=0, 255-192=63 → wildcard is 0.0.0.63.' },
          { type: 'heading', level: 2, text: 'Step 3: Set Router ID' },
          { type: 'paragraph', text: 'The Router ID (RID) uniquely identifies each OSPF router. It is chosen in this order: (1) manually configured, (2) highest loopback IP, (3) highest active physical IP.' },
          { type: 'code-block', code: '! Best practice: always set the Router ID manually\nRouter(config-router)# router-id 1.1.1.1\n\n! Or create a loopback interface (stays up even if physical links fail)\nRouter(config)# interface loopback 0\nRouter(config-if)# ip address 1.1.1.1 255.255.255.255\n\n! If you change the router-id, reload OSPF:\nRouter# clear ip ospf process' },
          { type: 'callout', variant: 'key-concept', text: 'Always set a stable Router ID. If you rely on physical interfaces and one goes down, the RID can change and disrupt all OSPF adjacencies.' },
          { type: 'heading', level: 2, text: 'Optional: Passive Interfaces' },
          { type: 'paragraph', text: 'Interfaces facing end users (like LAN segments with PCs) should not send OSPF hello packets. Use passive-interface to advertise the network without forming adjacencies.' },
          { type: 'code-block', code: 'Router(config-router)# passive-interface GigabitEthernet0/1\n\n! The subnet on Gi0/1 is still advertised into OSPF,\n! but no hello packets are sent out that interface.\n! Use this on LAN segments, management VLANs, etc.' },
          { type: 'heading', level: 2, text: 'Full Configuration Example' },
          { type: 'code-block', code: 'Router(config)# interface loopback 0\nRouter(config-if)# ip address 1.1.1.1 255.255.255.255\nRouter(config-if)# exit\n\nRouter(config)# router ospf 1\nRouter(config-router)# router-id 1.1.1.1\nRouter(config-router)# network 192.168.1.0 0.0.0.255 area 0\nRouter(config-router)# network 10.0.0.0 0.0.0.3 area 0\nRouter(config-router)# passive-interface GigabitEthernet0/1\nRouter(config-router)# auto-cost reference-bandwidth 10000\nRouter(config-router)# exit' },
        ],
      },
    },
    {
      id: 'm08-l04',
      title: 'Verifying OSPF',
      order: 4,
      type: 'theory',
      estimatedMinutes: 10,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'Verifying and Troubleshooting OSPF' },
          { type: 'paragraph', text: 'After configuring OSPF, you need to verify that neighbors are forming, routes are being learned, and the link-state database is consistent. Cisco IOS provides several powerful show commands for this.' },
          { type: 'heading', level: 2, text: 'show ip ospf neighbor' },
          { type: 'paragraph', text: 'The most important OSPF verification command. Shows all OSPF neighbors, their state, and the interface connecting to them.' },
          { type: 'code-block', code: 'Router# show ip ospf neighbor\n\nNeighbor ID     Pri   State           Dead Time   Address         Interface\n2.2.2.2           1   FULL/DR         00:00:35    10.0.0.2        Gi0/0\n3.3.3.3           1   FULL/BDR        00:00:31    10.0.0.3        Gi0/0\n4.4.4.4           1   FULL/  -        00:00:37    10.0.1.2        Gi0/1' },
          { type: 'bullet-list', items: [
            'FULL state = adjacency is complete, databases are synchronized',
            'TWO-WAY state = neighbors see each other but have not exchanged databases (normal for DROther routers)',
            'If a neighbor is stuck in INIT or EXSTART, there is a configuration problem',
            'Dead Time counts down from 40 seconds; resets each time a hello is received',
          ] },
          { type: 'heading', level: 2, text: 'show ip ospf' },
          { type: 'paragraph', text: 'Shows the OSPF process details including Router ID, areas, SPF statistics, and timers.' },
          { type: 'code-block', code: 'Router# show ip ospf\n\nRouting Process "ospf 1" with ID 1.1.1.1\n  Supports only single TOS(TOS0) routes\n  Number of areas in this router is 1. 1 normal  0 stub  0 nssa\n  Reference bandwidth unit is 10000 mbps\n  Area BACKBONE(0)\n    Number of interfaces in this area is 3\n    SPF algorithm last executed 00:05:22.456 ago\n    SPF algorithm executed 4 times' },
          { type: 'heading', level: 2, text: 'show ip route ospf' },
          { type: 'paragraph', text: 'Filters the routing table to show only routes learned via OSPF. OSPF routes are marked with "O" in the routing table.' },
          { type: 'code-block', code: 'Router# show ip route ospf\n\n      10.0.0.0/8 is variably subnetted, 4 subnets, 2 masks\nO        10.0.1.0/30 [110/10] via 10.0.0.2, 00:15:32, GigabitEthernet0/0\nO        10.0.2.0/30 [110/20] via 10.0.0.2, 00:15:32, GigabitEthernet0/0\n      192.168.0.0/24 is subnetted, 3 subnets\nO        192.168.2.0 [110/10] via 10.0.0.2, 00:15:32, GigabitEthernet0/0\nO        192.168.3.0 [110/20] via 10.0.0.2, 00:15:32, GigabitEthernet0/0\n\n! [110/10] means: AD 110 (OSPF default) / Cost 10' },
          { type: 'key-term', term: 'Administrative Distance (AD)', definition: 'A trustworthiness rating for routing protocols. OSPF has AD of 110. Connected = 0, Static = 1, EIGRP = 90, OSPF = 110, RIP = 120. Lower is more trusted.' },
          { type: 'heading', level: 2, text: 'show ip ospf interface' },
          { type: 'paragraph', text: 'Shows OSPF details for a specific interface — cost, hello/dead timers, DR/BDR, network type, and neighbor count.' },
          { type: 'code-block', code: 'Router# show ip ospf interface GigabitEthernet0/0\n\nGigabitEthernet0/0 is up, line protocol is up\n  Internet Address 10.0.0.1/30, Area 0\n  Process ID 1, Router ID 1.1.1.1, Network Type BROADCAST, Cost: 10\n  Transmit Delay is 1 sec, State BDR, Priority 1\n  Designated Router (ID) 2.2.2.2, Interface address 10.0.0.2\n  Backup Designated Router (ID) 1.1.1.1, Interface address 10.0.0.1\n  Timer intervals configured, Hello 10, Dead 40, Wait 40, Retransmit 5\n  Neighbor Count is 1, Adjacent neighbor count is 1' },
          { type: 'heading', level: 2, text: 'Common OSPF Troubleshooting' },
          { type: 'comparison-table', headers: ['Symptom', 'Likely Cause', 'Fix'], rows: [
            ['No neighbor shown', 'Hello/dead timers mismatch, area mismatch, or ACL blocking multicast', 'Check timers, area IDs, and ACLs on both sides'],
            ['Stuck in INIT', 'One-way communication — hellos sent but not received back', 'Check interface status, cable, and firewall rules'],
            ['Stuck in EXSTART/EXCHANGE', 'MTU mismatch between neighbors', 'Set matching MTU on both interfaces'],
            ['Routes missing', 'Network not advertised, passive-interface on wrong port, or area mismatch', 'Verify network statements and passive interfaces'],
            ['Suboptimal path', 'Cost not adjusted for high-speed links', 'Set auto-cost reference-bandwidth on ALL routers'],
          ] },
          { type: 'callout', variant: 'tip', text: 'Troubleshooting checklist: (1) Are neighbors forming? show ip ospf neighbor. (2) Are routes in the table? show ip route ospf. (3) Is the correct interface in OSPF? show ip ospf interface. (4) Is the LSDB consistent? show ip ospf database.' },
        ],
      },
    },
    {
      id: 'm08-l05',
      title: 'Lab: OSPF Routing',
      order: 5,
      type: 'lab',
      labId: 'lab-11-ospf-routing',
      estimatedMinutes: 20,
    },
  ],
  quiz: {
    id: 'quiz-module-08',
    moduleId: 'module-08',
    passingScore: 70,
    questions: [
      {
        id: 'q08-01', text: 'What type of routing protocol is OSPF?',
        options: [
          { id: 'a', text: 'Distance vector', correct: false },
          { id: 'b', text: 'Link-state', correct: true },
          { id: 'c', text: 'Path vector', correct: false },
          { id: 'd', text: 'Hybrid', correct: false },
        ],
        explanation: 'OSPF is a link-state protocol. Each router builds a complete map of the network topology and runs the SPF algorithm to calculate best paths.',
      },
      {
        id: 'q08-02', text: 'What is the default OSPF hello timer on a broadcast network?',
        options: [
          { id: 'a', text: '5 seconds', correct: false },
          { id: 'b', text: '10 seconds', correct: true },
          { id: 'c', text: '30 seconds', correct: false },
          { id: 'd', text: '60 seconds', correct: false },
        ],
        explanation: 'OSPF sends hello packets every 10 seconds on broadcast and point-to-point networks. The dead timer is 4x that (40 seconds).',
      },
      {
        id: 'q08-03', text: 'What multicast address do OSPF hello packets use?',
        options: [
          { id: 'a', text: '224.0.0.9', correct: false },
          { id: 'b', text: '224.0.0.5', correct: true },
          { id: 'c', text: '255.255.255.255', correct: false },
          { id: 'd', text: '224.0.0.1', correct: false },
        ],
        explanation: '224.0.0.5 is the AllSPFRouters multicast address. All OSPF routers listen on this address. 224.0.0.6 is AllDRouters (for DR/BDR communication).',
      },
      {
        id: 'q08-04', text: 'Which OSPF area must exist in every OSPF network?',
        options: [
          { id: 'a', text: 'Area 1', correct: false },
          { id: 'b', text: 'Area 51', correct: false },
          { id: 'c', text: 'Area 0 (backbone)', correct: true },
          { id: 'd', text: 'Area 255', correct: false },
        ],
        explanation: 'Area 0 is the backbone area. It is mandatory in every OSPF network. All other areas must connect to Area 0 either directly or via a virtual link.',
      },
      {
        id: 'q08-05', text: 'What is the wildcard mask for the subnet 255.255.255.0?',
        options: [
          { id: 'a', text: '0.0.0.0', correct: false },
          { id: 'b', text: '0.0.0.255', correct: true },
          { id: 'c', text: '255.255.255.0', correct: false },
          { id: 'd', text: '0.0.0.1', correct: false },
        ],
        explanation: 'Wildcard = inverse of subnet mask. 255-255=0, 255-255=0, 255-255=0, 255-0=255. So 0.0.0.255.',
      },
      {
        id: 'q08-06', text: 'What determines the OSPF DR election on a multi-access network?',
        options: [
          { id: 'a', text: 'Lowest Router ID wins', correct: false },
          { id: 'b', text: 'Highest OSPF priority, then highest Router ID', correct: true },
          { id: 'c', text: 'First router to boot wins', correct: false },
          { id: 'd', text: 'Lowest IP address wins', correct: false },
        ],
        explanation: 'The router with the highest OSPF priority becomes DR. If priorities are equal, the highest Router ID breaks the tie. Priority 0 means the router cannot become DR/BDR.',
      },
      {
        id: 'q08-07', text: 'What is the default Administrative Distance of OSPF?',
        options: [
          { id: 'a', text: '90', correct: false },
          { id: 'b', text: '100', correct: false },
          { id: 'c', text: '110', correct: true },
          { id: 'd', text: '120', correct: false },
        ],
        explanation: 'OSPF AD = 110. For comparison: Connected = 0, Static = 1, EIGRP = 90, OSPF = 110, RIP = 120. Lower AD is preferred.',
      },
      {
        id: 'q08-08', text: 'An OSPF neighbor is stuck in EXSTART state. What is the most likely cause?',
        options: [
          { id: 'a', text: 'Hello timer mismatch', correct: false },
          { id: 'b', text: 'Area ID mismatch', correct: false },
          { id: 'c', text: 'MTU mismatch', correct: true },
          { id: 'd', text: 'Wrong Router ID', correct: false },
        ],
        explanation: 'Neighbors stuck in EXSTART or EXCHANGE state almost always indicate an MTU mismatch between the two interfaces. Hello/area mismatches prevent adjacency from reaching EXSTART in the first place.',
      },
    ],
  },
  badge: {
    id: 'badge-module-08',
    name: 'Routing Pro',
    description: 'Completed Module 8: Dynamic Routing — OSPF. You can configure and troubleshoot OSPF in enterprise networks.',
    icon: '🏗️',
    color: '#00cc99',
    tier: 'gold',
  },
};
