import type { BootcampModule } from '../types.js';

export const module06: BootcampModule = {
  id: 'module-06',
  number: 6,
  title: 'ACLs & Security',
  description: 'Network security fundamentals, access control lists (standard and extended), wildcard masks, firewalls, and DMZ architecture.',
  color: '#ff4466',
  tier: 'gold',
  prerequisites: ['module-05'],
  labIds: ['lab-09-acl-basics', 'lab-12-firewall-dmz', 'lab-13-pfsense-firewall', 'lab-14-tplink-home-network'],
  lessons: [
    {
      id: 'm06-l01',
      title: 'Network Security Fundamentals',
      order: 1,
      type: 'theory',
      estimatedMinutes: 10,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'Network Security Fundamentals' },
          { type: 'paragraph', text: 'Security is not optional — it is a core requirement of every network. Without proper security, your network is exposed to unauthorized access, data theft, and service disruption. This lesson covers the foundational concepts that underpin all network security.' },
          { type: 'heading', level: 2, text: 'The CIA Triad' },
          { type: 'analogy', text: 'Think of the CIA triad like protecting a safe. Confidentiality means only authorized people can open it. Integrity means no one can tamper with the contents without you knowing. Availability means you can always access the safe when you need to.' },
          { type: 'key-term', term: 'Confidentiality', definition: 'Only authorized users can access the data. Achieved through encryption, access control lists, authentication, and VPNs. Prevents eavesdropping and unauthorized disclosure.' },
          { type: 'key-term', term: 'Integrity', definition: 'Data is not altered in transit or at rest. Achieved through hashing (MD5, SHA), digital signatures, and checksums. You can detect if someone tampered with the data.' },
          { type: 'key-term', term: 'Availability', definition: 'The network and its services are accessible when needed. Achieved through redundancy, fault tolerance, load balancing, and DDoS protection. Downtime = lost productivity and revenue.' },
          { type: 'callout', variant: 'key-concept', text: 'The CIA triad — Confidentiality, Integrity, Availability — is the foundation of all security decisions. Every security control you implement addresses one or more of these three pillars.' },
          { type: 'heading', level: 2, text: 'Defense in Depth' },
          { type: 'paragraph', text: 'No single security measure is enough. Defense in depth means layering multiple security controls so that if one fails, others still protect the network.' },
          { type: 'bullet-list', items: [
            'Physical security: Lock the server room, secure cabling',
            'Network security: Firewalls, ACLs, IDS/IPS, VPNs',
            'Host security: Antivirus, patching, endpoint protection',
            'Application security: Input validation, authentication, encryption',
            'User security: Strong passwords, multi-factor authentication, training',
          ] },
          { type: 'callout', variant: 'info', text: 'In this module, we focus on NETWORK security — specifically ACLs and firewalls. These are the controls that routers and firewalls use to filter traffic at Layers 3 and 4.' },
          { type: 'heading', level: 2, text: 'Common Threats' },
          { type: 'comparison-table', headers: ['Threat', 'Description', 'Mitigation'], rows: [
            ['Unauthorized access', 'Attacker gains access to network resources', 'ACLs, authentication, firewalls'],
            ['DoS / DDoS', 'Flooding a service to make it unavailable', 'Rate limiting, IPS, cloud mitigation'],
            ['Man-in-the-Middle', 'Attacker intercepts traffic between two parties', 'Encryption (TLS/VPN), certificate validation'],
            ['VLAN hopping', 'Attacker escapes their VLAN to access other VLANs', 'Disable DTP, prune VLANs, change native VLAN'],
            ['MAC flooding', 'Overflow switch MAC table to force broadcast mode', 'Port security, limit MAC addresses per port'],
          ] },
        ],
      },
    },
    {
      id: 'm06-l02',
      title: 'ACLs Explained',
      order: 2,
      type: 'theory',
      estimatedMinutes: 12,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'Access Control Lists (ACLs) Explained' },
          { type: 'analogy', text: 'An ACL is like a bouncer at a nightclub with a checklist. The bouncer checks each person against the list from top to bottom. If a rule says "allow," they get in. If a rule says "deny," they are turned away. If no rule matches, the bouncer denies entry by default (implicit deny).' },
          { type: 'paragraph', text: 'An ACL is an ordered list of permit or deny statements that filter network traffic. ACLs are applied to router interfaces and evaluate each packet against the rules from top to bottom. The first matching rule wins.' },
          { type: 'heading', level: 2, text: 'Standard vs Extended ACLs' },
          { type: 'comparison-table', headers: ['Feature', 'Standard ACL', 'Extended ACL'], rows: [
            ['Number range', '1 – 99 (or 1300 – 1999)', '100 – 199 (or 2000 – 2699)'],
            ['Filters on', 'Source IP address ONLY', 'Source IP, destination IP, protocol, port number'],
            ['Placement', 'Close to the DESTINATION', 'Close to the SOURCE'],
            ['Granularity', 'Low — can only match source', 'High — can match specific traffic flows'],
            ['Use case', 'Simple "block this network" rules', 'Precise "block HTTP from X to Y" rules'],
          ] },
          { type: 'heading', level: 2, text: 'How ACLs Process Traffic' },
          { type: 'numbered-list', items: [
            'Packet arrives at the router interface where the ACL is applied',
            'Router evaluates the packet against ACL rules, starting at the TOP',
            'The FIRST matching rule is applied (permit or deny) — evaluation stops',
            'If NO rule matches, the implicit deny at the end drops the packet',
          ] },
          { type: 'callout', variant: 'warning', text: 'Every ACL has an invisible "deny any" at the end — the IMPLICIT DENY. If you create an ACL with only deny statements, ALL traffic will be blocked because nothing matches a permit. Always include at least one permit statement.' },
          { type: 'key-term', term: 'Implicit Deny', definition: 'An invisible "deny all" rule at the end of every ACL. Any traffic that does not match an explicit permit or deny statement is automatically dropped. This is the #1 cause of unexpected ACL problems.' },
          { type: 'heading', level: 2, text: 'ACL Direction: Inbound vs Outbound' },
          { type: 'key-term', term: 'Inbound ACL', definition: 'Filters packets as they ENTER the interface. The packet is evaluated before the routing decision. More efficient because denied packets are dropped immediately.' },
          { type: 'key-term', term: 'Outbound ACL', definition: 'Filters packets as they LEAVE the interface. The packet is evaluated after the routing decision. The router does the work of routing before checking the ACL.' },
          { type: 'callout', variant: 'tip', text: 'Standard ACLs: place CLOSE to the destination (because they can only match the source IP — placing them at the source would block traffic to ALL destinations). Extended ACLs: place CLOSE to the source (to drop unwanted traffic as early as possible).' },
        ],
      },
    },
    {
      id: 'm06-l03',
      title: 'ACL Configuration',
      order: 3,
      type: 'theory',
      estimatedMinutes: 12,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'ACL Configuration Commands' },
          { type: 'paragraph', text: 'Now that you understand what ACLs do, it is time to configure them. This lesson covers the exact commands for standard and extended ACLs, wildcard masks, and applying ACLs to interfaces.' },
          { type: 'heading', level: 2, text: 'Wildcard Masks' },
          { type: 'key-term', term: 'Wildcard Mask', definition: 'The inverse of a subnet mask. 0 means "must match," 1 means "don\'t care." Used in ACLs and OSPF. To calculate: subtract the subnet mask from 255.255.255.255.' },
          { type: 'code-block', code: '  Subnet mask:    255.255.255.0\n  Wildcard mask:   0.0.0.255       (255.255.255.255 - 255.255.255.0)\n\n  Subnet mask:    255.255.255.192\n  Wildcard mask:   0.0.0.63        (255.255.255.255 - 255.255.255.192)\n\n  Subnet mask:    255.255.0.0\n  Wildcard mask:   0.0.255.255\n\n  Match a single host: wildcard 0.0.0.0 (or use keyword "host")\n  Match everything:    wildcard 255.255.255.255 (or use keyword "any")' },
          { type: 'callout', variant: 'key-concept', text: 'Wildcard masks are the INVERSE of subnet masks. In a wildcard mask, 0 = "must match this bit" and 1 = "ignore this bit." To get the wildcard mask, subtract the subnet mask from 255.255.255.255.' },
          { type: 'heading', level: 2, text: 'Standard ACL Configuration' },
          { type: 'code-block', code: '! Standard ACL: Filters on source IP only\n! Block traffic FROM 192.168.1.0/24\nRouter(config)# access-list 10 deny 192.168.1.0 0.0.0.255\nRouter(config)# access-list 10 permit any\n\n! Apply to an interface (outbound)\nRouter(config)# interface gi0/1\nRouter(config-if)# ip access-group 10 out\n\n! Named standard ACL (preferred):\nRouter(config)# ip access-list standard BLOCK-SALES\nRouter(config-std-nacl)# deny 192.168.20.0 0.0.0.255\nRouter(config-std-nacl)# permit any\nRouter(config-std-nacl)# exit\nRouter(config)# interface gi0/1\nRouter(config-if)# ip access-group BLOCK-SALES out' },
          { type: 'heading', level: 2, text: 'Extended ACL Configuration' },
          { type: 'code-block', code: '! Extended ACL: Filters on source, destination, protocol, port\n! Block HTTP (port 80) from 192.168.1.0/24 to server 10.0.0.100\nRouter(config)# access-list 100 deny tcp 192.168.1.0 0.0.0.255 host 10.0.0.100 eq 80\nRouter(config)# access-list 100 permit ip any any\n\n! Apply CLOSE to the source (inbound)\nRouter(config)# interface gi0/0\nRouter(config-if)# ip access-group 100 in\n\n! Named extended ACL:\nRouter(config)# ip access-list extended RESTRICT-WEB\nRouter(config-ext-nacl)# deny tcp 192.168.1.0 0.0.0.255 host 10.0.0.100 eq 80\nRouter(config-ext-nacl)# deny tcp 192.168.1.0 0.0.0.255 host 10.0.0.100 eq 443\nRouter(config-ext-nacl)# permit ip any any\nRouter(config-ext-nacl)# exit' },
          { type: 'heading', level: 2, text: 'Verification Commands' },
          { type: 'code-block', code: 'Router# show access-lists\nStandard IP access list 10\n    10 deny   192.168.1.0, wildcard bits 0.0.0.255 (25 matches)\n    20 permit any (1042 matches)\n\nExtended IP access list 100\n    10 deny   tcp 192.168.1.0 0.0.0.255 host 10.0.0.100 eq www (12 matches)\n    20 permit ip any any (5830 matches)\n\nRouter# show ip interface gi0/0\n  Ingoing access list is 100\n  Outgoing access list is not set' },
          { type: 'callout', variant: 'tip', text: 'Use named ACLs instead of numbered ACLs whenever possible. Named ACLs are easier to read, and you can insert or delete individual lines without re-creating the entire ACL.' },
        ],
      },
    },
    {
      id: 'm06-l04',
      title: 'Firewalls and Zones',
      order: 4,
      type: 'theory',
      estimatedMinutes: 10,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'Firewalls and Security Zones' },
          { type: 'paragraph', text: 'While ACLs on routers provide basic filtering, dedicated firewalls offer much more sophisticated security. Firewalls sit at the boundary between trusted and untrusted networks, inspecting and filtering all traffic that passes through them.' },
          { type: 'heading', level: 2, text: 'Types of Firewalls' },
          { type: 'key-term', term: 'Packet-Filtering Firewall', definition: 'The simplest type. Examines packet headers (source/destination IP, port, protocol) and applies rules — similar to router ACLs. Stateless — each packet is evaluated independently.' },
          { type: 'key-term', term: 'Stateful Firewall', definition: 'Tracks the state of network connections. If an internal host initiates a connection to the internet, the firewall automatically allows the reply traffic back in. Much more secure than stateless filtering.' },
          { type: 'key-term', term: 'Next-Generation Firewall (NGFW)', definition: 'Combines stateful inspection with deep packet inspection (DPI), intrusion prevention (IPS), application awareness, and threat intelligence. Can identify and block specific applications (e.g., block BitTorrent but allow Zoom).' },
          { type: 'comparison-table', headers: ['Firewall Type', 'Inspects', 'State Tracking', 'Example'], rows: [
            ['Packet filter', 'Headers only (L3/L4)', 'No', 'Router ACL'],
            ['Stateful', 'Headers + connection state', 'Yes', 'Cisco ASA, iptables'],
            ['NGFW', 'Headers + payload + apps', 'Yes', 'Palo Alto, Cisco Firepower'],
          ] },
          { type: 'heading', level: 2, text: 'Security Zones' },
          { type: 'paragraph', text: 'Firewalls divide the network into security zones. Each zone has a trust level, and the firewall enforces rules for traffic moving between zones.' },
          { type: 'key-term', term: 'Inside Zone', definition: 'The trusted internal network. Contains your users, servers, and workstations. Highest trust level. Traffic from inside is generally permitted to go out.' },
          { type: 'key-term', term: 'Outside Zone', definition: 'The untrusted external network (the internet). Lowest trust level. Traffic from outside is generally denied from coming in, unless it is a reply to an internal request.' },
          { type: 'key-term', term: 'DMZ (Demilitarized Zone)', definition: 'A semi-trusted zone between inside and outside. Hosts public-facing servers (web servers, mail servers, DNS). Internet users can reach DMZ services, but the DMZ cannot initiate connections to the inside network. If a DMZ server is compromised, the attacker still cannot reach internal resources.' },
          { type: 'callout', variant: 'key-concept', text: 'The DMZ protects your internal network. Public servers go in the DMZ. If an attacker compromises a web server in the DMZ, they are STILL blocked from reaching your internal network by the firewall.' },
          { type: 'heading', level: 2, text: 'Traffic Flow Rules' },
          { type: 'numbered-list', items: [
            'Inside → Outside: Generally ALLOWED (users browsing the internet)',
            'Outside → Inside: Generally DENIED (block hackers from reaching internal hosts)',
            'Outside → DMZ: ALLOWED for specific services only (HTTP port 80, HTTPS port 443)',
            'DMZ → Inside: Generally DENIED (compromised DMZ server cannot attack internal network)',
            'Inside → DMZ: Generally ALLOWED (admin access to DMZ servers)',
          ] },
          { type: 'callout', variant: 'tip', text: 'A common architecture: Firewall with three interfaces — one to the inside LAN, one to the outside internet, and one to the DMZ. The firewall is the single chokepoint that controls all inter-zone traffic.' },
        ],
      },
    },
    {
      id: 'm06-l05',
      title: 'pfSense — Open Source Firewall (Web GUI)',
      order: 5,
      type: 'theory',
      estimatedMinutes: 10,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'pfSense — The Open Source Firewall' },
          { type: 'paragraph', text: 'Not everything in networking uses Cisco CLI. pfSense is one of the most popular open-source firewalls in the world, used by thousands of businesses. Instead of typing commands, you configure it through a web browser — a Web GUI.' },
          { type: 'callout', variant: 'info', text: 'In our simulator, double-click a pfSense device to open its Web GUI — just like you would open a browser and go to 192.168.1.1 in real life.' },

          { type: 'heading', level: 2, text: 'pfSense vs Cisco ASA' },
          { type: 'comparison-table', headers: ['Feature', 'pfSense', 'Cisco ASA'], rows: [
            ['Interface', 'Web GUI (browser)', 'CLI (command line)'],
            ['Cost', 'Free / open source', '$500 - $50,000+'],
            ['Configuration', 'Click dropdowns, fill forms', 'Type commands one by one'],
            ['Firewall Rules', 'Visual table — add/edit/delete', 'access-list commands'],
            ['NAT', 'Point-and-click port forwards', 'ip nat commands'],
            ['DHCP', 'Toggle on/off, set range', 'ip dhcp pool commands'],
            ['Best For', 'Small-medium business, home labs', 'Enterprise, data centers'],
          ] },

          { type: 'heading', level: 2, text: 'pfSense Interfaces' },
          { type: 'paragraph', text: 'pfSense uses zone-based security with named interfaces:' },
          { type: 'key-term', term: 'WAN (Red)', definition: 'The untrusted side — connects to the internet or upstream router. External traffic enters here.' },
          { type: 'key-term', term: 'LAN (Green)', definition: 'The trusted side — your internal network. Devices here are protected by the firewall.' },
          { type: 'key-term', term: 'OPT1 / DMZ (Orange)', definition: 'Optional interface for a DMZ (demilitarized zone). Hosts public servers that need internet access but are isolated from internal LAN.' },

          { type: 'heading', level: 2, text: 'Configuring pfSense Firewall Rules' },
          { type: 'paragraph', text: 'Firewall rules in pfSense work top-to-bottom. The FIRST rule that matches wins. If no rule matches, traffic is BLOCKED (implicit deny). This is the same concept as Cisco ACLs, just with a visual interface.' },
          { type: 'numbered-list', items: [
            'Open pfSense Web GUI (double-click the device)',
            'Go to the Firewall Rules tab',
            'Click "+ Add Pass Rule" or "+ Add Block Rule"',
            'Set the Action (Pass or Block)',
            'Set the Interface (WAN, LAN, OPT1)',
            'Set Source IP (specific IP like 10.0.0.20, a network like 192.168.1.0/24, or "any")',
            'Set Destination IP',
            'Add a description so you remember why this rule exists',
            'Rules are applied immediately — test with ping!',
          ] },

          { type: 'heading', level: 2, text: 'pfSense NAT / Port Forwarding' },
          { type: 'paragraph', text: 'Port forwarding allows external traffic to reach internal servers. For example, if you have a web server at 192.168.1.100 and want the internet to reach it:' },
          { type: 'code-block', code: '  Port Forward Rule:\n  Interface: WAN\n  External Port: 80 (HTTP)\n  Internal IP: 192.168.1.100\n  Internal Port: 80\n\n  Result: Anyone accessing your WAN IP on port 80\n  gets forwarded to 192.168.1.100:80 (your web server)' },

          { type: 'heading', level: 2, text: 'pfSense DHCP Server' },
          { type: 'paragraph', text: 'pfSense can automatically assign IP addresses to devices on the LAN — just like a home router. Enable it in the DHCP tab, set a range (e.g., 192.168.1.100 - 192.168.1.200), and any device that connects will get an IP automatically.' },
          { type: 'callout', variant: 'tip', text: 'After configuring DHCP on pfSense, go to a PC connected to it and type "ipconfig /renew" — it will get an IP from the pfSense DHCP pool.' },

          { type: 'callout', variant: 'key-concept', text: 'The networking concepts (firewall rules, NAT, DHCP) are IDENTICAL to Cisco. Only the interface is different. Learn the concepts once → apply them on any vendor.' },
        ],
      },
    },
    {
      id: 'm06-l06',
      title: 'Home Routers — TP-Link Web GUI',
      order: 6,
      type: 'theory',
      estimatedMinutes: 8,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'Home Routers — TP-Link Configuration' },
          { type: 'paragraph', text: 'Every home and small office has a router — usually a consumer brand like TP-Link, Netgear, or Linksys. These use a simple web GUI designed for non-technical users. Understanding how they work connects classroom networking to the real world.' },

          { type: 'heading', level: 2, text: 'What a Home Router Actually Does' },
          { type: 'paragraph', text: 'A single TP-Link device combines FOUR functions that are separate devices in enterprise networking:' },
          { type: 'comparison-table', headers: ['Function', 'Enterprise Equivalent', 'TP-Link Setting'], rows: [
            ['Routing', 'Cisco Router', 'Internet (WAN) settings'],
            ['Switching', 'Cisco Switch (4 LAN ports)', 'Built-in — LAN ports'],
            ['Wireless AP', 'Cisco AP', 'Wireless settings (SSID, password)'],
            ['Firewall', 'Cisco ASA / pfSense', 'Security tab (SPI firewall)'],
            ['DHCP Server', 'Router DHCP pool', 'LAN / DHCP settings'],
            ['NAT', 'ip nat overload', 'Automatic — all LAN traffic NATed to WAN'],
          ] },

          { type: 'callout', variant: 'key-concept', text: 'A $40 TP-Link does the same job as $10,000+ of enterprise gear — just for fewer users and with fewer features. The concepts are identical.' },

          { type: 'heading', level: 2, text: 'TP-Link Configuration Walkthrough' },
          { type: 'numbered-list', items: [
            'Double-click the TP-Link device in the simulator',
            'Internet tab: Set WAN IP, subnet mask, gateway, DNS (this is what your ISP gives you)',
            'Wireless tab: Set SSID (WiFi name) and password',
            'LAN/DHCP tab: Set router LAN IP (default 192.168.0.1) and DHCP range',
            'Forwarding tab: Add port forwards for game servers, web servers, etc.',
            'Security tab: Enable SPI firewall, toggle ping from WAN',
          ] },

          { type: 'heading', level: 2, text: 'Common Home Network Setup' },
          { type: 'code-block', code: '  ISP Modem → TP-Link WAN port\n  TP-Link LAN ports → PCs, Smart TV, Game Console\n  TP-Link WiFi → Phones, Laptops, Tablets\n\n  TP-Link WAN IP: assigned by ISP (e.g., 203.0.113.50)\n  TP-Link LAN IP: 192.168.0.1 (your gateway)\n  DHCP Range: 192.168.0.100 - 192.168.0.200\n  All devices get 192.168.0.X automatically via DHCP' },

          { type: 'heading', level: 2, text: 'Port Forwarding — Why Gamers Need It' },
          { type: 'paragraph', text: 'NAT hides all your internal devices behind one public IP. But what if you run a Minecraft server at home? External players can\'t reach it because NAT blocks incoming traffic by default.' },
          { type: 'paragraph', text: 'Solution: Port forward. Tell the router "anything coming to port 25565 should go to my PC at 192.168.0.50." Now external players connect to your public IP:25565 and it reaches your Minecraft server.' },

          { type: 'callout', variant: 'tip', text: 'When someone says "open your ports" for gaming or servers, they mean: go to your router\'s Port Forwarding settings and create a rule.' },
        ],
      },
    },
    {
      id: 'm06-l07',
      title: 'Lab: ACL Basics (Cisco CLI)',
      order: 7,
      type: 'lab',
      labId: 'lab-09-acl-basics',
      estimatedMinutes: 15,
    },
    {
      id: 'm06-l08',
      title: 'Lab: Firewall & DMZ',
      order: 8,
      type: 'lab',
      labId: 'lab-12-firewall-dmz',
      estimatedMinutes: 15,
    },
    {
      id: 'm06-l09',
      title: 'Lab: pfSense Firewall Setup',
      order: 9,
      type: 'lab',
      labId: 'lab-13-pfsense-firewall',
      estimatedMinutes: 20,
    },
    {
      id: 'm06-l10',
      title: 'Lab: Home Network with TP-Link',
      order: 10,
      type: 'lab',
      labId: 'lab-14-tplink-home-network',
      estimatedMinutes: 15,
    },
  ],
  quiz: {
    id: 'quiz-module-06',
    moduleId: 'module-06',
    passingScore: 70,
    questions: [
      {
        id: 'q06-01', text: 'What does the "C" in the CIA triad stand for?',
        options: [
          { id: 'a', text: 'Connectivity', correct: false },
          { id: 'b', text: 'Confidentiality', correct: true },
          { id: 'c', text: 'Compliance', correct: false },
          { id: 'd', text: 'Configuration', correct: false },
        ],
        explanation: 'CIA = Confidentiality, Integrity, Availability. Confidentiality ensures only authorized users can access data.',
      },
      {
        id: 'q06-02', text: 'What is the implicit deny in an ACL?',
        options: [
          { id: 'a', text: 'A rule you must type manually at the end', correct: false },
          { id: 'b', text: 'An invisible "deny all" at the end of every ACL', correct: true },
          { id: 'c', text: 'A rule that denies VLAN traffic', correct: false },
          { id: 'd', text: 'A warning message shown to the administrator', correct: false },
        ],
        explanation: 'Every ACL has an invisible "deny any" at the bottom. If a packet does not match any explicit rule, it is dropped by the implicit deny.',
      },
      {
        id: 'q06-03', text: 'Standard ACLs filter based on what?',
        options: [
          { id: 'a', text: 'Source and destination IP', correct: false },
          { id: 'b', text: 'Source IP address only', correct: true },
          { id: 'c', text: 'Port numbers only', correct: false },
          { id: 'd', text: 'MAC addresses', correct: false },
        ],
        explanation: 'Standard ACLs (numbered 1-99) can only filter based on the source IP address. Extended ACLs can filter on source IP, destination IP, protocol, and port.',
      },
      {
        id: 'q06-04', text: 'What is the wildcard mask for subnet 255.255.255.0?',
        options: [
          { id: 'a', text: '0.0.0.0', correct: false },
          { id: 'b', text: '255.255.255.0', correct: false },
          { id: 'c', text: '0.0.0.255', correct: true },
          { id: 'd', text: '0.0.255.255', correct: false },
        ],
        explanation: 'Wildcard = 255.255.255.255 minus subnet mask. 255.255.255.255 - 255.255.255.0 = 0.0.0.255. In the wildcard, 0 = must match, 1 = ignore.',
      },
      {
        id: 'q06-05', text: 'Where should you place a standard ACL?',
        options: [
          { id: 'a', text: 'Close to the source', correct: false },
          { id: 'b', text: 'Close to the destination', correct: true },
          { id: 'c', text: 'On every router in the path', correct: false },
          { id: 'd', text: 'On the switch', correct: false },
        ],
        explanation: 'Standard ACLs only match source IP. Placing them close to the source would block traffic to ALL destinations. Place them close to the destination so only specific traffic flows are affected.',
      },
      {
        id: 'q06-06', text: 'What is a DMZ in network security?',
        options: [
          { id: 'a', text: 'A type of encryption protocol', correct: false },
          { id: 'b', text: 'A semi-trusted zone for public-facing servers', correct: true },
          { id: 'c', text: 'A VLAN used for management', correct: false },
          { id: 'd', text: 'A VPN tunnel between two routers', correct: false },
        ],
        explanation: 'The DMZ (Demilitarized Zone) is a semi-trusted network segment that hosts public-facing services. It sits between the inside (trusted) and outside (untrusted) networks.',
      },
      {
        id: 'q06-07', text: 'Which command applies ACL 100 inbound on interface GigabitEthernet0/0?',
        options: [
          { id: 'a', text: 'access-list 100 in', correct: false },
          { id: 'b', text: 'ip access-group 100 in', correct: true },
          { id: 'c', text: 'ip access-list 100 inbound', correct: false },
          { id: 'd', text: 'apply acl 100 in', correct: false },
        ],
        explanation: 'The command "ip access-group <number> in|out" is used in interface configuration mode to apply an ACL. "access-list" creates the ACL; "ip access-group" applies it.',
      },
      {
        id: 'q06-08', text: 'A stateful firewall differs from a packet filter because it ___.',
        options: [
          { id: 'a', text: 'Inspects only Layer 2 headers', correct: false },
          { id: 'b', text: 'Cannot block any traffic', correct: false },
          { id: 'c', text: 'Tracks the state of connections and allows return traffic', correct: true },
          { id: 'd', text: 'Only works with wireless networks', correct: false },
        ],
        explanation: 'A stateful firewall remembers outgoing connections and automatically permits the associated return traffic. A packet filter evaluates each packet independently with no connection awareness.',
      },
      {
        id: 'q06-09', text: 'pfSense is configured through which type of interface?',
        options: [
          { id: 'a', text: 'Command line (CLI)', correct: false },
          { id: 'b', text: 'Web browser GUI', correct: true },
          { id: 'c', text: 'Mobile app only', correct: false },
          { id: 'd', text: 'Telnet only', correct: false },
        ],
        explanation: 'pfSense uses a Web GUI — you open a browser and navigate to the pfSense IP address (e.g., 192.168.1.1). Cisco devices use CLI.',
      },
      {
        id: 'q06-10', text: 'What does "port forwarding" on a home router do?',
        options: [
          { id: 'a', text: 'Makes your WiFi faster', correct: false },
          { id: 'b', text: 'Blocks all incoming traffic', correct: false },
          { id: 'c', text: 'Redirects incoming traffic on a specific port to an internal device', correct: true },
          { id: 'd', text: 'Changes your public IP address', correct: false },
        ],
        explanation: 'Port forwarding tells the router: "traffic coming to my public IP on port X should be sent to internal device Y on port Z." Used for game servers, web servers, etc.',
      },
      {
        id: 'q06-11', text: 'A TP-Link home router combines which enterprise functions into one device?',
        options: [
          { id: 'a', text: 'Only routing', correct: false },
          { id: 'b', text: 'Router + Switch + Wireless AP + Firewall + DHCP', correct: true },
          { id: 'c', text: 'Only wireless access point', correct: false },
          { id: 'd', text: 'Only firewall and NAT', correct: false },
        ],
        explanation: 'A consumer router is actually 5 devices in one: router (WAN↔LAN), switch (4 LAN ports), wireless AP (WiFi), firewall (SPI), and DHCP server (auto IP assignment).',
      },
    ],
  },
  badge: {
    id: 'badge-module-06',
    name: 'Security Guardian',
    description: 'Completed Module 6: ACLs & Security. You can configure access control lists and understand firewall zone architecture.',
    icon: '🛡️',
    color: '#ff4466',
    tier: 'gold',
  },
};
