import type { BootcampModule } from '../types.js';

export const module04: BootcampModule = {
  id: 'module-04',
  number: 4,
  title: 'Switching & VLANs',
  description: 'How switches forward frames, MAC address tables, broadcast domains, VLANs, and trunk ports.',
  color: '#aa44ff',
  tier: 'silver',
  prerequisites: ['module-03'],
  labIds: ['lab-04-multi-device', 'lab-06-vlans'],
  lessons: [
    {
      id: 'm04-l01',
      title: 'How Switches Work',
      order: 1,
      type: 'theory',
      estimatedMinutes: 10,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'How Switches Work' },
          { type: 'analogy', text: 'A switch is like a smart receptionist in an office building. When someone arrives with a letter, the receptionist looks at the name on the envelope, checks the directory (MAC address table), and sends the visitor directly to the right office — instead of shouting the name to every room like a hub would.' },
          { type: 'paragraph', text: 'Switches are the backbone of every modern LAN. They operate at Layer 2 (Data Link) and make forwarding decisions based on MAC addresses. Unlike hubs, which blindly broadcast every frame to every port, switches learn which devices are on which ports and send frames only where they need to go.' },
          { type: 'heading', level: 2, text: 'The MAC Address Table' },
          { type: 'paragraph', text: 'Every switch maintains a MAC address table (also called a CAM table). This table maps MAC addresses to switch ports. The switch builds this table dynamically by examining the SOURCE MAC address of every frame it receives.' },
          { type: 'key-term', term: 'MAC Address Table (CAM Table)', definition: 'A lookup table stored in switch memory that maps MAC addresses to physical port numbers. The switch uses this table to make forwarding decisions.' },
          { type: 'numbered-list', items: [
            'A frame arrives on port Fa0/1 with source MAC AA:AA:AA:AA:AA:AA',
            'The switch records: "MAC AA:AA:AA:AA:AA:AA is on port Fa0/1"',
            'The switch looks at the destination MAC address in the frame',
            'If the destination MAC is in the table, the switch forwards the frame to ONLY that port (unicast)',
            'If the destination MAC is NOT in the table, the switch floods the frame to ALL ports except the source port (unknown unicast flood)',
          ] },
          { type: 'code-block', code: 'Switch# show mac address-table\n          Mac Address Table\n-------------------------------------------\nVlan    Mac Address       Type        Ports\n----    -----------       --------    -----\n   1    aa:aa:aa:aa:aa:aa DYNAMIC     Fa0/1\n   1    bb:bb:bb:bb:bb:bb DYNAMIC     Fa0/2\n   1    cc:cc:cc:cc:cc:cc DYNAMIC     Fa0/3' },
          { type: 'callout', variant: 'key-concept', text: 'Switches LEARN from source addresses and FORWARD based on destination addresses. If the destination is unknown, they FLOOD to all ports. If the destination is known, they send to only one port.' },
          { type: 'heading', level: 2, text: 'Broadcast Domains' },
          { type: 'key-term', term: 'Broadcast Domain', definition: 'The set of devices that receive a broadcast frame. By default, all ports on a switch are in the same broadcast domain. Routers and VLANs break up broadcast domains.' },
          { type: 'paragraph', text: 'When a device sends a broadcast (destination MAC FF:FF:FF:FF:FF:FF), the switch forwards it to every port. In a large flat network with hundreds of devices on one switch, this means every device processes every broadcast. This wastes bandwidth and CPU — a problem called a broadcast storm.' },
          { type: 'callout', variant: 'warning', text: 'A single large broadcast domain is dangerous. If one device misbehaves and sends excessive broadcasts, EVERY device on the switch is affected. VLANs solve this problem by segmenting the switch into smaller broadcast domains.' },
        ],
      },
    },
    {
      id: 'm04-l02',
      title: 'VLANs — Virtual LANs',
      order: 2,
      type: 'theory',
      estimatedMinutes: 10,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'VLANs — Virtual LANs' },
          { type: 'analogy', text: 'Imagine a large apartment building where everyone shares one intercom system. Every time someone buzzes, ALL apartments hear it. VLANs are like dividing the building into wings — Wing A has its own intercom, Wing B has its own. A buzz in Wing A does not bother Wing B.' },
          { type: 'paragraph', text: 'A VLAN (Virtual Local Area Network) logically segments a single physical switch into multiple separate broadcast domains. Devices in different VLANs cannot communicate without a router, even if they are plugged into the same switch.' },
          { type: 'heading', level: 2, text: 'Why Use VLANs?' },
          { type: 'bullet-list', items: [
            'Security: Separate sensitive departments (HR, Finance) from general traffic',
            'Performance: Smaller broadcast domains mean less wasted bandwidth',
            'Organization: Group users by function, not physical location',
            'Flexibility: Move users between VLANs without re-cabling',
            'Cost savings: One physical switch can act like multiple logical switches',
          ] },
          { type: 'heading', level: 2, text: 'VLAN IDs and Ranges' },
          { type: 'key-term', term: 'VLAN ID', definition: 'A number from 1 to 4094 that identifies a VLAN. VLAN 1 is the default VLAN — all ports start in VLAN 1. VLANs 2-1001 are the normal range. VLANs 1002-1005 are reserved for legacy protocols.' },
          { type: 'comparison-table', headers: ['VLAN Range', 'Name', 'Details'], rows: [
            ['1', 'Default VLAN', 'All ports belong here by default. Cannot be deleted.'],
            ['2 – 1001', 'Normal range', 'Standard VLANs you create for your network.'],
            ['1002 – 1005', 'Reserved', 'Legacy Token Ring / FDDI. Do not use.'],
            ['1006 – 4094', 'Extended range', 'Available with VTP transparent mode.'],
          ] },
          { type: 'heading', level: 2, text: 'Access Ports' },
          { type: 'key-term', term: 'Access Port', definition: 'A switch port that belongs to exactly one VLAN. End devices (PCs, printers, servers) connect to access ports. The device has no idea it is on a VLAN — the switch handles everything.' },
          { type: 'code-block', code: 'Switch(config)# vlan 10\nSwitch(config-vlan)# name Engineering\nSwitch(config-vlan)# exit\nSwitch(config)# vlan 20\nSwitch(config-vlan)# name Sales\nSwitch(config-vlan)# exit\nSwitch(config)# interface fa0/1\nSwitch(config-if)# switchport mode access\nSwitch(config-if)# switchport access vlan 10\nSwitch(config-if)# exit\nSwitch(config)# interface fa0/2\nSwitch(config-if)# switchport mode access\nSwitch(config-if)# switchport access vlan 20' },
          { type: 'callout', variant: 'key-concept', text: 'A device on VLAN 10 CANNOT talk to a device on VLAN 20 without a router (inter-VLAN routing). VLANs create hard boundaries between networks at Layer 2.' },
        ],
      },
    },
    {
      id: 'm04-l03',
      title: 'Trunk Ports & 802.1Q',
      order: 3,
      type: 'theory',
      estimatedMinutes: 10,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'Trunk Ports & 802.1Q Tagging' },
          { type: 'paragraph', text: 'Access ports carry traffic for a single VLAN. But what happens when you need to carry multiple VLANs between two switches, or between a switch and a router? That is where trunk ports come in.' },
          { type: 'analogy', text: 'Imagine a highway with multiple lanes. Each lane represents a different VLAN. A trunk port is like a multi-lane highway — it carries traffic from many VLANs simultaneously over a single cable. Each car (frame) has a colored tag on it so the receiving switch knows which lane (VLAN) it belongs to.' },
          { type: 'heading', level: 2, text: 'What is a Trunk?' },
          { type: 'key-term', term: 'Trunk Port', definition: 'A switch port that carries traffic for MULTIPLE VLANs simultaneously. Used for switch-to-switch and switch-to-router connections. Frames are tagged with a VLAN ID so the receiving device knows which VLAN they belong to.' },
          { type: 'heading', level: 2, text: '802.1Q Tagging' },
          { type: 'paragraph', text: '802.1Q is the IEEE standard for VLAN tagging. When a frame travels across a trunk, the switch inserts a 4-byte tag into the Ethernet frame header. This tag contains the VLAN ID so the receiving switch knows which VLAN the frame belongs to.' },
          { type: 'key-term', term: '802.1Q Tag', definition: 'A 4-byte field inserted into the Ethernet frame between the source MAC address and the EtherType. Contains the VLAN ID (12 bits, supporting VLANs 0-4095) and priority bits (3 bits for QoS).' },
          { type: 'key-term', term: 'Native VLAN', definition: 'The one VLAN on a trunk that is NOT tagged. By default, this is VLAN 1. Frames on the native VLAN are sent untagged across the trunk. Both sides of the trunk must agree on the native VLAN, or traffic gets misrouted.' },
          { type: 'callout', variant: 'warning', text: 'Native VLAN mismatch is a common misconfiguration. If Switch A has native VLAN 1 and Switch B has native VLAN 10, untagged frames will end up in the wrong VLAN. Always verify with "show interfaces trunk".' },
          { type: 'heading', level: 2, text: 'Configuring a Trunk' },
          { type: 'code-block', code: 'Switch(config)# interface gi0/1\nSwitch(config-if)# switchport mode trunk\nSwitch(config-if)# switchport trunk allowed vlan 10,20,30\nSwitch(config-if)# switchport trunk native vlan 99\nSwitch(config-if)# exit\n\n! Verify trunk configuration\nSwitch# show interfaces trunk\nPort        Mode         Encapsulation  Status        Native vlan\nGi0/1       on           802.1q         trunking      99\n\nPort        Vlans allowed on trunk\nGi0/1       10,20,30\n\nPort        Vlans allowed and active in management domain\nGi0/1       10,20,30' },
          { type: 'comparison-table', headers: ['Feature', 'Access Port', 'Trunk Port'], rows: [
            ['VLANs carried', 'One VLAN only', 'Multiple VLANs'],
            ['Tagging', 'No tags (device unaware)', '802.1Q tags on frames'],
            ['Connected to', 'End devices (PCs, servers)', 'Switches, routers'],
            ['Configuration', 'switchport mode access', 'switchport mode trunk'],
            ['Default', 'VLAN 1', 'All VLANs allowed'],
          ] },
          { type: 'callout', variant: 'tip', text: 'Best practice: Only allow the VLANs you actually need on a trunk. Use "switchport trunk allowed vlan" to prune unnecessary VLANs. This improves security and reduces broadcast traffic.' },
        ],
      },
    },
    {
      id: 'm04-l04',
      title: 'VLAN Configuration Commands',
      order: 4,
      type: 'theory',
      estimatedMinutes: 8,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'VLAN Configuration — Command Reference' },
          { type: 'paragraph', text: 'This lesson brings together all the VLAN commands you need. Memorize these — they are essential for labs and real-world configuration.' },
          { type: 'heading', level: 2, text: 'Creating and Naming VLANs' },
          { type: 'code-block', code: 'Switch(config)# vlan 10                  ! Create VLAN 10\nSwitch(config-vlan)# name Engineering     ! Give it a meaningful name\nSwitch(config-vlan)# exit\n\nSwitch(config)# vlan 20\nSwitch(config-vlan)# name Sales\nSwitch(config-vlan)# exit\n\nSwitch(config)# vlan 99\nSwitch(config-vlan)# name Management\nSwitch(config-vlan)# exit' },
          { type: 'heading', level: 2, text: 'Assigning Ports to VLANs' },
          { type: 'code-block', code: '! Assign a single port to a VLAN\nSwitch(config)# interface fa0/1\nSwitch(config-if)# switchport mode access\nSwitch(config-if)# switchport access vlan 10\n\n! Assign a range of ports to a VLAN\nSwitch(config)# interface range fa0/1 - 12\nSwitch(config-if-range)# switchport mode access\nSwitch(config-if-range)# switchport access vlan 10\n\n! Assign another range to a different VLAN\nSwitch(config)# interface range fa0/13 - 24\nSwitch(config-if-range)# switchport mode access\nSwitch(config-if-range)# switchport access vlan 20' },
          { type: 'heading', level: 2, text: 'Verification Commands' },
          { type: 'code-block', code: 'Switch# show vlan brief\nVLAN Name                             Status    Ports\n---- -------------------------------- --------- --------------------\n1    default                          active    Gi0/1, Gi0/2\n10   Engineering                      active    Fa0/1, Fa0/2, Fa0/3\n20   Sales                            active    Fa0/13, Fa0/14\n99   Management                       active\n\nSwitch# show interfaces trunk\nSwitch# show interfaces fa0/1 switchport' },
          { type: 'comparison-table', headers: ['Command', 'Purpose'], rows: [
            ['show vlan brief', 'List all VLANs and their assigned ports'],
            ['show interfaces trunk', 'Show trunk ports, allowed VLANs, native VLAN'],
            ['show interfaces <port> switchport', 'Show VLAN assignment and mode for a specific port'],
            ['show mac address-table', 'Show MAC-to-port mappings per VLAN'],
          ] },
          { type: 'callout', variant: 'tip', text: '"show vlan brief" is your go-to command for verifying VLAN assignments. Run it after every change to confirm ports are in the right VLAN.' },
          { type: 'heading', level: 2, text: 'Common Mistakes' },
          { type: 'bullet-list', items: [
            'Forgetting to create the VLAN before assigning ports — the port goes to a non-existent VLAN and stops working',
            'Not setting the port to "switchport mode access" — it may negotiate trunk mode unexpectedly',
            'Native VLAN mismatch on trunk links — causes traffic to cross VLANs incorrectly',
            'Forgetting "switchport trunk allowed vlan" — all VLANs are allowed by default, which is a security risk',
          ] },
          { type: 'callout', variant: 'key-concept', text: 'The VLAN workflow: (1) Create the VLAN with a name, (2) Assign access ports to the VLAN, (3) Configure trunks between switches, (4) Verify with "show vlan brief" and "show interfaces trunk".' },
        ],
      },
    },
    {
      id: 'm04-l05',
      title: 'Lab: Multi-Device Network',
      order: 5,
      type: 'lab',
      labId: 'lab-04-multi-device',
      estimatedMinutes: 15,
    },
    {
      id: 'm04-l06',
      title: 'Lab: VLAN Configuration',
      order: 6,
      type: 'lab',
      labId: 'lab-06-vlans',
      estimatedMinutes: 15,
    },
  ],
  quiz: {
    id: 'quiz-module-04',
    moduleId: 'module-04',
    passingScore: 70,
    questions: [
      {
        id: 'q04-01', text: 'What does a switch do when it receives a frame with an unknown destination MAC address?',
        options: [
          { id: 'a', text: 'Drops the frame', correct: false },
          { id: 'b', text: 'Sends it back to the source', correct: false },
          { id: 'c', text: 'Floods it to all ports except the source port', correct: true },
          { id: 'd', text: 'Sends it to the default gateway', correct: false },
        ],
        explanation: 'When the destination MAC is not in the MAC address table, the switch performs an unknown unicast flood — sending the frame out all ports except the one it arrived on.',
      },
      {
        id: 'q04-02', text: 'A switch learns MAC addresses by examining which field of incoming frames?',
        options: [
          { id: 'a', text: 'Destination MAC address', correct: false },
          { id: 'b', text: 'Source MAC address', correct: true },
          { id: 'c', text: 'IP address', correct: false },
          { id: 'd', text: 'VLAN tag', correct: false },
        ],
        explanation: 'Switches learn from the SOURCE MAC address. When a frame arrives on a port, the switch records: "This source MAC is reachable via this port."',
      },
      {
        id: 'q04-03', text: 'What is the default VLAN on a Cisco switch?',
        options: [
          { id: 'a', text: 'VLAN 0', correct: false },
          { id: 'b', text: 'VLAN 1', correct: true },
          { id: 'c', text: 'VLAN 10', correct: false },
          { id: 'd', text: 'VLAN 100', correct: false },
        ],
        explanation: 'VLAN 1 is the default VLAN. All ports are in VLAN 1 by default. It cannot be deleted or renamed.',
      },
      {
        id: 'q04-04', text: 'Can two devices in different VLANs communicate without a router?',
        options: [
          { id: 'a', text: 'Yes, if they are on the same switch', correct: false },
          { id: 'b', text: 'Yes, if they use the same subnet', correct: false },
          { id: 'c', text: 'No, a Layer 3 device is required', correct: true },
          { id: 'd', text: 'Yes, through the trunk port', correct: false },
        ],
        explanation: 'VLANs create separate broadcast domains. Traffic between VLANs must be routed by a Layer 3 device (router or Layer 3 switch). This is called inter-VLAN routing.',
      },
      {
        id: 'q04-05', text: 'What IEEE standard defines VLAN tagging on trunk ports?',
        options: [
          { id: 'a', text: '802.11', correct: false },
          { id: 'b', text: '802.3', correct: false },
          { id: 'c', text: '802.1Q', correct: true },
          { id: 'd', text: '802.1X', correct: false },
        ],
        explanation: '802.1Q is the standard for VLAN tagging on trunks. 802.11 is Wi-Fi. 802.3 is Ethernet. 802.1X is port-based authentication.',
      },
      {
        id: 'q04-06', text: 'What is the native VLAN on a trunk port?',
        options: [
          { id: 'a', text: 'The VLAN that blocks all traffic', correct: false },
          { id: 'b', text: 'The VLAN whose frames are sent untagged', correct: true },
          { id: 'c', text: 'The VLAN used only for management', correct: false },
          { id: 'd', text: 'The VLAN with the highest priority', correct: false },
        ],
        explanation: 'The native VLAN is the one VLAN on a trunk whose frames are sent without an 802.1Q tag. By default, this is VLAN 1. Both sides of a trunk must agree on the native VLAN.',
      },
      {
        id: 'q04-07', text: 'Which command assigns port Fa0/5 to VLAN 20?',
        options: [
          { id: 'a', text: 'switchport vlan 20', correct: false },
          { id: 'b', text: 'vlan 20 port fa0/5', correct: false },
          { id: 'c', text: 'switchport access vlan 20', correct: true },
          { id: 'd', text: 'set vlan 20', correct: false },
        ],
        explanation: 'The correct command is "switchport access vlan 20" in interface configuration mode. You should also set "switchport mode access" first.',
      },
      {
        id: 'q04-08', text: 'What command shows all VLANs and their port assignments?',
        options: [
          { id: 'a', text: 'show running-config', correct: false },
          { id: 'b', text: 'show vlan brief', correct: true },
          { id: 'c', text: 'show interfaces status', correct: false },
          { id: 'd', text: 'show trunk', correct: false },
        ],
        explanation: '"show vlan brief" displays a clean table of all VLANs, their names, status, and assigned ports. It is the most useful VLAN verification command.',
      },
    ],
  },
  badge: {
    id: 'badge-module-04',
    name: 'Switch Commander',
    description: 'Completed Module 4: Switching & VLANs. You understand how switches forward frames and how VLANs segment networks.',
    icon: '🔀',
    color: '#aa44ff',
    tier: 'silver',
  },
};
