import type { BootcampModule } from '../types.js';

export const module01: BootcampModule = {
  id: 'module-01',
  number: 1,
  title: 'What is Networking?',
  description: 'Learn the fundamentals — what networks are, the OSI model, TCP/IP, and how data travels between devices.',
  color: '#00bceb',
  tier: 'bronze',
  prerequisites: [],
  labIds: ['lab-01-basic-connectivity'],
  lessons: [
    {
      id: 'm01-l01',
      title: 'What is a Network?',
      order: 1,
      type: 'theory',
      estimatedMinutes: 5,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'What is a Network?' },
          { type: 'analogy', text: 'Imagine a postal system. Every house has an address, and mail carriers know how to deliver letters between them. A computer network works the same way — every device has an address (IP address), and routers act as mail carriers.' },
          { type: 'paragraph', text: 'A network is two or more devices connected together so they can share data. That\'s it. Your home Wi-Fi is a network. The internet is the biggest network ever built.' },
          { type: 'diagram', diagram: { type: 'network-topology', data: { devices: [{ label: 'PC', x: 60, y: 80, type: 'pc' }, { label: 'Switch', x: 200, y: 80, type: 'switch' }, { label: 'Router', x: 340, y: 80, type: 'router' }, { label: 'Server', x: 480, y: 80, type: 'server' }], links: [[0, 1], [1, 2], [2, 3]] }, caption: 'A simple network: PC connects to a Switch, which connects to a Router, which reaches a Server.' } },
          { type: 'heading', level: 2, text: 'Types of Networks' },
          { type: 'key-term', term: 'LAN (Local Area Network)', definition: 'A network within a single building or campus. Your office or home network is a LAN. Covers a small geographic area.' },
          { type: 'key-term', term: 'WAN (Wide Area Network)', definition: 'A network that spans cities or countries. The internet is the largest WAN. Connects multiple LANs together.' },
          { type: 'key-term', term: 'MAN (Metropolitan Area Network)', definition: 'A network covering a city or large campus. Bigger than a LAN, smaller than a WAN.' },
          { type: 'callout', variant: 'key-concept', text: 'Everything in networking comes down to three things: ADDRESSING (where to send), SWITCHING (local delivery), and ROUTING (long-distance delivery).' },
          { type: 'heading', level: 2, text: 'Why Learn Networking?' },
          { type: 'bullet-list', items: [
            'Every company needs someone who understands networks',
            'Cloud computing, cybersecurity, and IT all require networking knowledge',
            'It\'s the foundation for certifications like CCNA, CompTIA Network+, and AWS',
            'Average network engineer salary: $80,000 - $120,000',
          ] },
        ],
      },
    },
    {
      id: 'm01-l02',
      title: 'The OSI Model',
      order: 2,
      type: 'theory',
      estimatedMinutes: 10,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'The OSI Model — 7 Layers of Networking' },
          { type: 'paragraph', text: 'The OSI (Open Systems Interconnection) model breaks networking into 7 layers. Each layer has a specific job. Think of it like building a house — you need a foundation (physical layer) before you can add walls (data link) and a roof (application).' },
          { type: 'diagram', diagram: { type: 'osi-layers', data: {}, caption: 'The 7 Layers of the OSI Model — from Physical (bottom) to Application (top)' } },
          { type: 'callout', variant: 'tip', text: 'Mnemonic to remember the layers (bottom to top): "Please Do Not Throw Sausage Pizza Away" — Physical, Data Link, Network, Transport, Session, Presentation, Application' },
          { type: 'comparison-table', headers: ['Layer', 'Name', 'What It Does', 'Example'], rows: [
            ['7', 'Application', 'User interface, web browsers', 'HTTP, HTTPS, FTP, DNS'],
            ['6', 'Presentation', 'Data formatting, encryption', 'SSL/TLS, JPEG, ASCII'],
            ['5', 'Session', 'Manages connections', 'NetBIOS, RPC'],
            ['4', 'Transport', 'Reliable delivery, ports', 'TCP, UDP'],
            ['3', 'Network', 'IP addressing, routing', 'IP, ICMP, OSPF'],
            ['2', 'Data Link', 'MAC addressing, switching', 'Ethernet, Wi-Fi'],
            ['1', 'Physical', 'Cables, signals, bits', 'Copper, Fiber, Radio'],
          ] },
          { type: 'heading', level: 2, text: 'The Layers That Matter Most (For Now)' },
          { type: 'paragraph', text: 'For this bootcamp, you will work mostly with Layers 1-4:' },
          { type: 'numbered-list', items: [
            'Layer 1 (Physical) — The cables you plug in',
            'Layer 2 (Data Link) — Switches that forward frames using MAC addresses',
            'Layer 3 (Network) — Routers that forward packets using IP addresses',
            'Layer 4 (Transport) — TCP/UDP that ensure data arrives correctly',
          ] },
          { type: 'callout', variant: 'key-concept', text: 'Layer 2 = Switches = MAC addresses. Layer 3 = Routers = IP addresses. This is the most important distinction in networking.' },
        ],
      },
    },
    {
      id: 'm01-l03',
      title: 'TCP/IP Model',
      order: 3,
      type: 'theory',
      estimatedMinutes: 7,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'TCP/IP — The Real-World Model' },
          { type: 'paragraph', text: 'While the OSI model is great for learning, the internet actually runs on the TCP/IP model. It has 4 layers instead of 7, and it maps to real protocols you will use every day.' },
          { type: 'comparison-table', headers: ['TCP/IP Layer', 'OSI Layers', 'Protocols'], rows: [
            ['Application', '7, 6, 5', 'HTTP, DNS, DHCP, FTP, SSH'],
            ['Transport', '4', 'TCP (reliable), UDP (fast)'],
            ['Internet', '3', 'IP, ICMP, ARP, OSPF'],
            ['Network Access', '2, 1', 'Ethernet, Wi-Fi, PPP'],
          ] },
          { type: 'heading', level: 2, text: 'TCP vs UDP' },
          { type: 'key-term', term: 'TCP (Transmission Control Protocol)', definition: 'Reliable delivery. Guarantees data arrives in order. Used for web, email, file transfer. Like sending a registered letter — you get confirmation.' },
          { type: 'key-term', term: 'UDP (User Datagram Protocol)', definition: 'Fast but unreliable. No guarantee of delivery. Used for video streaming, gaming, DNS. Like shouting across a room — fast but might miss some words.' },
          { type: 'callout', variant: 'info', text: 'When you ping a device, you use ICMP (Internet Control Message Protocol) — part of the Internet layer. That is what our simulator does when you type "ping".' },
        ],
      },
    },
    {
      id: 'm01-l04',
      title: 'How Data Travels',
      order: 4,
      type: 'theory',
      estimatedMinutes: 8,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'How Data Travels Across a Network' },
          { type: 'analogy', text: 'Sending data across a network is like sending a package through FedEx. Your data gets wrapped in boxes (encapsulation) — first a transport box (TCP segment), then a shipping label (IP packet), then a local delivery wrapper (Ethernet frame), and finally converted to signals on a wire (bits).' },
          { type: 'heading', level: 2, text: 'Encapsulation — Data Gets Wrapped' },
          { type: 'numbered-list', items: [
            'Application creates data (e.g., you type a URL)',
            'Transport layer wraps it in a SEGMENT (adds port numbers)',
            'Network layer wraps it in a PACKET (adds IP addresses)',
            'Data Link layer wraps it in a FRAME (adds MAC addresses)',
            'Physical layer converts it to BITS (electrical/light signals)',
          ] },
          { type: 'diagram', diagram: { type: 'packet-flow', data: {}, caption: 'Each layer adds its own header — this is encapsulation' } },
          { type: 'callout', variant: 'key-concept', text: 'At each layer, a HEADER is added. This is called encapsulation. When the data arrives, each layer removes its header (de-encapsulation). It is like unwrapping a package inside a package inside a package.' },
          { type: 'heading', level: 2, text: 'Key Terms' },
          { type: 'key-term', term: 'Segment', definition: 'Transport layer data unit. Has source and destination PORT numbers.' },
          { type: 'key-term', term: 'Packet', definition: 'Network layer data unit. Has source and destination IP ADDRESSES.' },
          { type: 'key-term', term: 'Frame', definition: 'Data Link layer data unit. Has source and destination MAC ADDRESSES.' },
          { type: 'callout', variant: 'tip', text: 'You are now ready to build your first network! The next lesson is a hands-on lab where you will connect devices and see data flow.' },
        ],
      },
    },
    {
      id: 'm01-l05',
      title: 'Lab: Your First Network',
      order: 5,
      type: 'lab',
      labId: 'lab-01-basic-connectivity',
      estimatedMinutes: 10,
    },
  ],
  quiz: {
    id: 'quiz-module-01',
    moduleId: 'module-01',
    passingScore: 70,
    questions: [
      {
        id: 'q01-01', text: 'What does LAN stand for?',
        options: [
          { id: 'a', text: 'Large Area Network', correct: false },
          { id: 'b', text: 'Local Area Network', correct: true },
          { id: 'c', text: 'Long Access Network', correct: false },
          { id: 'd', text: 'Linked Application Node', correct: false },
        ],
        explanation: 'LAN = Local Area Network. It covers a small area like an office or home.',
      },
      {
        id: 'q01-02', text: 'Which OSI layer do Routers operate at?',
        options: [
          { id: 'a', text: 'Layer 1 (Physical)', correct: false },
          { id: 'b', text: 'Layer 2 (Data Link)', correct: false },
          { id: 'c', text: 'Layer 3 (Network)', correct: true },
          { id: 'd', text: 'Layer 4 (Transport)', correct: false },
        ],
        explanation: 'Routers operate at Layer 3 (Network). They forward packets based on IP addresses.',
      },
      {
        id: 'q01-03', text: 'Which protocol is used when you "ping" a device?',
        options: [
          { id: 'a', text: 'TCP', correct: false },
          { id: 'b', text: 'UDP', correct: false },
          { id: 'c', text: 'ICMP', correct: true },
          { id: 'd', text: 'HTTP', correct: false },
        ],
        explanation: 'Ping uses ICMP (Internet Control Message Protocol) to send echo requests and receive replies.',
      },
      {
        id: 'q01-04', text: 'What is the correct order of data encapsulation (top to bottom)?',
        options: [
          { id: 'a', text: 'Data → Segment → Packet → Frame → Bits', correct: true },
          { id: 'b', text: 'Data → Packet → Frame → Segment → Bits', correct: false },
          { id: 'c', text: 'Bits → Frame → Packet → Segment → Data', correct: false },
          { id: 'd', text: 'Data → Frame → Packet → Segment → Bits', correct: false },
        ],
        explanation: 'Encapsulation goes: Data → Segment (Transport) → Packet (Network) → Frame (Data Link) → Bits (Physical).',
      },
      {
        id: 'q01-05', text: 'Which device operates at Layer 2 and uses MAC addresses?',
        options: [
          { id: 'a', text: 'Router', correct: false },
          { id: 'b', text: 'Switch', correct: true },
          { id: 'c', text: 'Firewall', correct: false },
          { id: 'd', text: 'Server', correct: false },
        ],
        explanation: 'Switches operate at Layer 2 (Data Link) and forward frames based on MAC addresses.',
      },
      {
        id: 'q01-06', text: 'TCP is reliable while UDP is fast. Which one does video streaming typically use?',
        options: [
          { id: 'a', text: 'TCP', correct: false },
          { id: 'b', text: 'UDP', correct: true },
          { id: 'c', text: 'Both equally', correct: false },
          { id: 'd', text: 'Neither', correct: false },
        ],
        explanation: 'Video streaming uses UDP because speed matters more than reliability. A few dropped frames are acceptable.',
      },
      {
        id: 'q01-07', text: 'How many layers does the TCP/IP model have?',
        options: [
          { id: 'a', text: '4', correct: true },
          { id: 'b', text: '5', correct: false },
          { id: 'c', text: '7', correct: false },
          { id: 'd', text: '3', correct: false },
        ],
        explanation: 'TCP/IP has 4 layers: Application, Transport, Internet, Network Access. The OSI model has 7.',
      },
      {
        id: 'q01-08', text: 'A WAN covers which area?',
        options: [
          { id: 'a', text: 'A single room', correct: false },
          { id: 'b', text: 'A single building', correct: false },
          { id: 'c', text: 'A city or country', correct: true },
          { id: 'd', text: 'A single computer', correct: false },
        ],
        explanation: 'WAN (Wide Area Network) spans large geographic areas — cities, countries, or even continents. The internet is the largest WAN.',
      },
      {
        id: 'q01-09', text: 'What type of address does Layer 3 (Network) use?',
        options: [
          { id: 'a', text: 'MAC address', correct: false },
          { id: 'b', text: 'IP address', correct: true },
          { id: 'c', text: 'Port number', correct: false },
          { id: 'd', text: 'URL', correct: false },
        ],
        explanation: 'Layer 3 uses IP addresses for routing. Layer 2 uses MAC addresses. Layer 4 uses port numbers.',
      },
      {
        id: 'q01-10', text: 'The mnemonic "Please Do Not Throw Sausage Pizza Away" helps you remember what?',
        options: [
          { id: 'a', text: 'TCP/IP layers', correct: false },
          { id: 'b', text: 'OSI model layers (bottom to top)', correct: true },
          { id: 'c', text: 'Network cable types', correct: false },
          { id: 'd', text: 'IP address classes', correct: false },
        ],
        explanation: 'Physical, Data Link, Network, Transport, Session, Presentation, Application — the 7 OSI layers from bottom to top.',
      },
    ],
  },
  badge: {
    id: 'badge-module-01',
    name: 'Network Novice',
    description: 'Completed Module 1: What is Networking? You understand the fundamentals of how networks work.',
    icon: '🌐',
    color: '#00bceb',
    tier: 'bronze',
  },
};
