import type { BootcampModule } from '../types.js';

export const module10: BootcampModule = {
  id: 'module-10',
  number: 10,
  title: 'Capstone Projects',
  description: 'Build real-world networks: SOHO, enterprise, multi-site. Apply everything you have learned across all modules.',
  color: '#ffcc00',
  tier: 'platinum',
  prerequisites: ['module-09'],
  labIds: ['lab-15-wireless-network', 'lab-17-office-network', 'lab-18-security-audit'],
  lessons: [
    {
      id: 'm10-l01',
      title: 'Putting It All Together',
      order: 1,
      type: 'theory',
      estimatedMinutes: 15,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'Putting It All Together' },
          { type: 'paragraph', text: 'Congratulations — you have made it to the final module. Over the past nine modules, you have gone from "what is a network?" to configuring OSPF, designing hierarchical networks, and troubleshooting like a professional. Now it is time to tie it all together.' },
          { type: 'analogy', text: 'You have learned to use every tool in the toolbox — the hammer (physical layer), the measuring tape (IP addressing), the level (VLANs), the drill (routing), the lock (ACLs and security), the door (NAT), the GPS (OSPF), and the blueprint (network design). Now you build the house.' },
          { type: 'heading', level: 2, text: 'What You Have Learned' },
          { type: 'comparison-table', headers: ['Module', 'Topic', 'Key Skill'], rows: [
            ['1', 'What is Networking?', 'OSI/TCP-IP models, encapsulation, how data travels'],
            ['2', 'Physical Layer', 'Cables, devices, ports, CLI basics'],
            ['3', 'IP Addressing & Subnetting', 'IPv4 structure, subnet math, VLSM, private vs public'],
            ['4', 'Switching & VLANs', 'Layer 2 forwarding, VLAN segmentation, trunk ports'],
            ['5', 'Routing Fundamentals', 'Static routes, default gateway, routing decisions'],
            ['6', 'ACLs & Security', 'Standard/extended ACLs, packet filtering, defense in depth'],
            ['7', 'NAT & Internet Access', 'Static NAT, dynamic NAT, PAT, inside/outside interfaces'],
            ['8', 'Dynamic Routing (OSPF)', 'Link-state protocol, areas, neighbor adjacency, cost metric'],
            ['9', 'Design & Troubleshooting', 'Three-tier model, IP planning, systematic troubleshooting'],
          ] },
          { type: 'heading', level: 2, text: 'Real-World Network Scenarios' },
          { type: 'paragraph', text: 'In production environments, you will encounter these common scenarios that combine multiple skills:' },
          { type: 'heading', level: 2, text: 'Scenario 1: Small Office / Home Office (SOHO)' },
          { type: 'bullet-list', items: [
            '1 router, 1 switch, 5-20 devices',
            'Single subnet (e.g., 192.168.1.0/24)',
            'NAT/PAT for internet access through the ISP',
            'DHCP on the router for automatic IP assignment',
            'Basic ACL to block unwanted inbound traffic',
            'Wi-Fi via an access point connected to the switch',
          ] },
          { type: 'heading', level: 2, text: 'Scenario 2: Medium Enterprise Campus' },
          { type: 'bullet-list', items: [
            'Core switch, 2 distribution switches, 10+ access switches',
            'Multiple VLANs: Engineering, Sales, HR, Servers, Management, Guest',
            'Inter-VLAN routing at the distribution layer (router-on-a-stick or L3 switch)',
            'OSPF between core and distribution routers for dynamic routing',
            'ACLs to restrict guest VLAN from accessing internal servers',
            'NAT at the edge router for internet access',
            'Redundant links with STP or L3 ECMP',
            'DHCP server for each VLAN with proper relay agents',
          ] },
          { type: 'heading', level: 2, text: 'Scenario 3: Multi-Site WAN' },
          { type: 'bullet-list', items: [
            'Headquarters + 3 branch offices connected via WAN links',
            'OSPF across all sites with proper area design (Area 0 at HQ)',
            'Summarization at ABRs to keep routing tables small',
            'NAT at each site for local internet breakout',
            'VPN tunnels between sites for secure communication',
            'Centralized servers at HQ with branches accessing them over WAN',
            'QoS policies to prioritize voice and video traffic',
          ] },
          { type: 'callout', variant: 'key-concept', text: 'Every real network uses a combination of the technologies you have learned. The difference between a junior and senior engineer is not knowing more commands — it is knowing how to combine them into a coherent design.' },
          { type: 'heading', level: 2, text: 'Design Process Recap' },
          { type: 'numbered-list', items: [
            'Gather requirements: How many users? What applications? What is the budget? Growth plans?',
            'Design the topology: Choose a hierarchical model, place devices, plan redundancy',
            'Plan IP addressing: Allocate subnets per VLAN, plan for VLSM, document everything',
            'Configure Layer 2: Set up VLANs, trunks, port security, STP',
            'Configure Layer 3: Set up inter-VLAN routing, OSPF, static routes to ISP',
            'Configure security: ACLs, NAT, firewall rules, management access restrictions',
            'Test and verify: Ping end-to-end, verify routing tables, test failover',
            'Document: Network diagrams, IP spreadsheet, configuration backups, runbooks',
          ] },
        ],
      },
    },
    {
      id: 'm10-l02',
      title: 'Career Paths in Networking',
      order: 2,
      type: 'theory',
      estimatedMinutes: 10,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'Career Paths in Networking' },
          { type: 'paragraph', text: 'Completing this bootcamp gives you a solid foundation, but the learning never stops. Networking is a broad field with many specializations and career paths. Here is where you can go from here.' },
          { type: 'heading', level: 2, text: 'Industry Certifications' },
          { type: 'paragraph', text: 'Certifications validate your skills and are often required (or strongly preferred) by employers. Here are the most valuable certifications to pursue next:' },
          { type: 'key-term', term: 'CompTIA Network+ (N10-009)', definition: 'Vendor-neutral networking certification. Covers networking concepts, infrastructure, security, and troubleshooting. Great first certification — recognized globally. Ideal if you work with multiple vendors.' },
          { type: 'key-term', term: 'Cisco CCNA (200-301)', definition: 'The gold standard for networking careers. Covers everything in this bootcamp and more: IPv6, wireless, automation, security fundamentals. Required for most network engineering roles. Valid for 3 years.' },
          { type: 'key-term', term: 'Cisco CCNP Enterprise', definition: 'Advanced Cisco certification. Deep dive into enterprise networking: advanced routing (EIGRP, OSPF, BGP), SD-WAN, wireless, automation with Python. Requires passing two exams.' },
          { type: 'comparison-table', headers: ['Certification', 'Level', 'Focus', 'Salary Impact'], rows: [
            ['CompTIA Network+', 'Entry', 'Vendor-neutral networking fundamentals', '$55K - $75K'],
            ['Cisco CCNA', 'Associate', 'Cisco networking, routing, switching, security', '$65K - $95K'],
            ['Cisco CCNP Enterprise', 'Professional', 'Advanced enterprise networking', '$90K - $130K'],
            ['Cisco CCIE', 'Expert', 'Top-tier network architecture', '$120K - $200K+'],
            ['AWS Solutions Architect', 'Associate', 'Cloud networking and architecture', '$100K - $150K'],
          ] },
          { type: 'callout', variant: 'tip', text: 'Start with CCNA. The content you have learned in this bootcamp covers roughly 60-70% of the CCNA exam topics. Add IPv6, wireless basics, and automation, and you are ready to sit for the exam.' },
          { type: 'heading', level: 2, text: 'Career Tracks' },
          { type: 'bullet-list', items: [
            'Network Engineer — Design, implement, and maintain enterprise networks. The most direct path from this bootcamp.',
            'Network Administrator — Day-to-day management of network infrastructure, monitoring, and user support.',
            'Security Engineer — Specialize in firewalls, IDS/IPS, VPNs, and security architecture. Build on ACL and NAT knowledge.',
            'Cloud Network Engineer — Design networking in AWS, Azure, or GCP. VPCs, load balancers, hybrid connectivity.',
            'DevOps / NetOps Engineer — Automate network configuration with Python, Ansible, Terraform. The future of networking.',
            'Wireless Engineer — Specialize in Wi-Fi design, site surveys, and wireless security. Growing demand everywhere.',
            'Network Architect — Senior role designing large-scale networks from scratch. Requires years of experience.',
          ] },
          { type: 'heading', level: 2, text: 'Skills to Develop Next' },
          { type: 'numbered-list', items: [
            'IPv6 addressing and routing — the next generation of IP, increasingly required',
            'Network automation with Python and Ansible — manual CLI configuration is being replaced',
            'Cloud networking (AWS VPC, Azure VNet) — nearly every company uses cloud',
            'Wireless networking (802.11ax, controller-based) — Wi-Fi is everywhere',
            'Security fundamentals — every network engineer needs security awareness',
            'Linux basics — most servers, firewalls, and network tools run on Linux',
          ] },
          { type: 'callout', variant: 'info', text: 'The networking field is evolving rapidly. Traditional CLI-based networking is being augmented by software-defined networking (SDN), intent-based networking (IBN), and infrastructure as code. Learning automation alongside traditional skills makes you extremely valuable.' },
          { type: 'heading', level: 2, text: 'What Makes a Great Network Engineer' },
          { type: 'bullet-list', items: [
            'Systematic thinking — break complex problems into layers and work through them methodically',
            'Attention to detail — one wrong subnet mask bit can bring down a network',
            'Documentation habits — if it is not documented, it does not exist',
            'Continuous learning — technology changes constantly, and so should your knowledge',
            'Communication skills — you need to explain technical problems to non-technical people',
          ] },
        ],
      },
    },
    {
      id: 'm10-lab1',
      title: 'Capstone: Wireless Network Setup',
      order: 3,
      type: 'lab',
      labId: 'lab-15-wireless-network',
      estimatedMinutes: 20,
    },
    {
      id: 'm10-lab2',
      title: 'Capstone: Complete Office Network',
      order: 4,
      type: 'lab',
      labId: 'lab-17-office-network',
      estimatedMinutes: 30,
    },
    {
      id: 'm10-lab3',
      title: 'Capstone: Security Audit',
      order: 5,
      type: 'lab',
      labId: 'lab-18-security-audit',
      estimatedMinutes: 25,
    },
  ],
  quiz: {
    id: 'quiz-module-10',
    moduleId: 'module-10',
    passingScore: 70,
    questions: [
      {
        id: 'q10-01', text: 'Which OSI layer do switches primarily operate at?',
        options: [
          { id: 'a', text: 'Layer 1 (Physical)', correct: false },
          { id: 'b', text: 'Layer 2 (Data Link)', correct: true },
          { id: 'c', text: 'Layer 3 (Network)', correct: false },
          { id: 'd', text: 'Layer 4 (Transport)', correct: false },
        ],
        explanation: 'Switches operate at Layer 2 (Data Link) and forward frames based on MAC addresses. Layer 3 switches can also route, but traditional switching is Layer 2.',
      },
      {
        id: 'q10-02', text: 'What is the subnet mask for a /27 network, and how many usable hosts does it provide?',
        options: [
          { id: 'a', text: '255.255.255.224 — 30 hosts', correct: true },
          { id: 'b', text: '255.255.255.192 — 62 hosts', correct: false },
          { id: 'c', text: '255.255.255.240 — 14 hosts', correct: false },
          { id: 'd', text: '255.255.255.128 — 126 hosts', correct: false },
        ],
        explanation: '/27 = 255.255.255.224. Host bits = 32 - 27 = 5. Usable hosts = 2^5 - 2 = 30.',
      },
      {
        id: 'q10-03', text: 'What is the purpose of a trunk port on a switch?',
        options: [
          { id: 'a', text: 'Connect end-user PCs', correct: false },
          { id: 'b', text: 'Carry traffic for multiple VLANs between switches', correct: true },
          { id: 'c', text: 'Provide Power over Ethernet', correct: false },
          { id: 'd', text: 'Block broadcast traffic', correct: false },
        ],
        explanation: 'Trunk ports carry traffic for multiple VLANs using 802.1Q tagging. They connect switches to switches, switches to routers (router-on-a-stick), and switches to servers that need multiple VLAN access.',
      },
      {
        id: 'q10-04', text: 'A static route has an administrative distance of 1. What is the AD of OSPF?',
        options: [
          { id: 'a', text: '90', correct: false },
          { id: 'b', text: '100', correct: false },
          { id: 'c', text: '110', correct: true },
          { id: 'd', text: '120', correct: false },
        ],
        explanation: 'Administrative Distances: Connected = 0, Static = 1, EIGRP = 90, OSPF = 110, RIP = 120. Lower AD is more trusted. OSPF routes are preferred over RIP but not over static.',
      },
      {
        id: 'q10-05', text: 'An extended ACL can filter traffic based on which of the following?',
        options: [
          { id: 'a', text: 'Source IP address only', correct: false },
          { id: 'b', text: 'Source IP, destination IP, protocol, and port number', correct: true },
          { id: 'c', text: 'MAC address only', correct: false },
          { id: 'd', text: 'VLAN number', correct: false },
        ],
        explanation: 'Extended ACLs (numbered 100-199) can filter on source IP, destination IP, protocol (TCP/UDP/ICMP), and port numbers. Standard ACLs (1-99) can only filter on source IP.',
      },
      {
        id: 'q10-06', text: 'What type of NAT allows multiple internal hosts to share a single public IP address using different port numbers?',
        options: [
          { id: 'a', text: 'Static NAT', correct: false },
          { id: 'b', text: 'Dynamic NAT', correct: false },
          { id: 'c', text: 'PAT (Port Address Translation)', correct: true },
          { id: 'd', text: 'NAT64', correct: false },
        ],
        explanation: 'PAT (also called NAT overload) maps multiple private IPs to a single public IP by using unique source port numbers to track each session. This is what most home routers and small businesses use.',
      },
      {
        id: 'q10-07', text: 'In OSPF, what must match between two routers for them to become neighbors?',
        options: [
          { id: 'a', text: 'Hostname and process ID', correct: false },
          { id: 'b', text: 'Hello/dead timers, area ID, subnet mask, and authentication', correct: true },
          { id: 'c', text: 'Router ID and IP address', correct: false },
          { id: 'd', text: 'Only the area ID', correct: false },
        ],
        explanation: 'OSPF neighbor requirements: matching hello/dead timers, same area ID, same subnet mask on the shared link, and matching authentication settings. Process ID does NOT need to match.',
      },
      {
        id: 'q10-08', text: 'You ping a server and get a response. At which OSI layer is the problem if the web page still will not load?',
        options: [
          { id: 'a', text: 'Layer 1 (Physical)', correct: false },
          { id: 'b', text: 'Layer 2 (Data Link)', correct: false },
          { id: 'c', text: 'Layer 3 (Network)', correct: false },
          { id: 'd', text: 'Above Layer 3 (Transport or Application)', correct: true },
        ],
        explanation: 'If ping works, Layers 1-3 are functioning. The problem is above Layer 3 — likely the application (web server down), DNS resolution, a firewall blocking TCP port 80/443, or the service not listening.',
      },
      {
        id: 'q10-09', text: 'Which private IP range provides the most addresses?',
        options: [
          { id: 'a', text: '192.168.0.0/16', correct: false },
          { id: 'b', text: '172.16.0.0/12', correct: false },
          { id: 'c', text: '10.0.0.0/8', correct: true },
          { id: 'd', text: 'They all provide the same number', correct: false },
        ],
        explanation: '10.0.0.0/8 provides approximately 16.7 million addresses. 172.16.0.0/12 provides about 1 million. 192.168.0.0/16 provides about 65,000. The /8 is the largest private block.',
      },
      {
        id: 'q10-10', text: 'In the three-tier hierarchical model, a "collapsed core" design combines which two layers?',
        options: [
          { id: 'a', text: 'Access and Distribution', correct: false },
          { id: 'b', text: 'Core and Distribution', correct: true },
          { id: 'c', text: 'Core and Access', correct: false },
          { id: 'd', text: 'Distribution and Transport', correct: false },
        ],
        explanation: 'A collapsed core merges the core and distribution layers into a single layer. This is common in small to medium networks where a separate core layer is not cost-justified.',
      },
    ],
  },
  badge: {
    id: 'badge-module-10',
    name: 'NetX Certified Professional',
    description: 'Completed Module 10: Capstone Projects. You have mastered the full NetX Networking Bootcamp curriculum.',
    icon: '🎓',
    color: '#ffcc00',
    tier: 'platinum',
  },
};
