import type { BootcampModule } from '../types.js';

export const module02: BootcampModule = {
  id: 'module-02',
  number: 2,
  title: 'Physical Layer',
  description: 'Cables, devices, ports, and your first CLI commands.',
  color: '#22cc88',
  tier: 'bronze',
  prerequisites: ['module-01'],
  labIds: ['lab-01-basic-connectivity', 'lab-19-cable-crimping'],
  lessons: [
    {
      id: 'm02-l01',
      title: 'Cables and Media Types',
      order: 1,
      type: 'theory',
      estimatedMinutes: 7,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'Cables and Media Types' },
          { type: 'paragraph', text: 'Every network needs a way to physically move data between devices. That medium can be copper wire, glass fiber, or radio waves. Each has tradeoffs in speed, distance, and cost.' },
          { type: 'heading', level: 2, text: 'Copper Cables (Ethernet)' },
          { type: 'key-term', term: 'UTP (Unshielded Twisted Pair)', definition: 'The most common cable in LANs. Uses 4 pairs of twisted copper wires inside a plastic jacket. Categories: Cat5e (1 Gbps), Cat6 (10 Gbps short distance), Cat6a (10 Gbps 100m).' },
          { type: 'key-term', term: 'Straight-Through Cable', definition: 'Connects DIFFERENT device types: PC→Switch, Switch→Router. Both ends wired the same way.' },
          { type: 'key-term', term: 'Crossover Cable', definition: 'Connects SAME device types: Switch→Switch, PC→PC, Router→Router. Transmit and receive pairs are swapped.' },
          { type: 'callout', variant: 'tip', text: 'Modern devices have Auto-MDIX which automatically detects the cable type and adjusts. But for exams, you need to know the difference!' },
          { type: 'heading', level: 2, text: 'Fiber Optic Cables' },
          { type: 'key-term', term: 'Single-Mode Fiber (SMF)', definition: 'One beam of light, travels very far (up to 100km). Used for WAN links and long campus runs. More expensive.' },
          { type: 'key-term', term: 'Multi-Mode Fiber (MMF)', definition: 'Multiple beams of light, shorter distance (up to 2km). Used inside buildings and data centers. Cheaper than single-mode.' },
          { type: 'callout', variant: 'key-concept', text: 'Fiber is immune to electromagnetic interference (EMI) and is much faster over long distances. When you need speed + distance, fiber wins.' },
          { type: 'heading', level: 2, text: 'Wireless' },
          { type: 'paragraph', text: 'Wi-Fi uses radio waves. No cables needed, but speed and reliability are lower than wired connections. Common standards: 802.11n (Wi-Fi 4), 802.11ac (Wi-Fi 5), 802.11ax (Wi-Fi 6).' },
          { type: 'comparison-table', headers: ['Media', 'Speed', 'Max Distance', 'Cost', 'Use Case'], rows: [
            ['Cat5e Copper', '1 Gbps', '100m', 'Low', 'Office LANs'],
            ['Cat6a Copper', '10 Gbps', '100m', 'Medium', 'Data centers'],
            ['Multi-Mode Fiber', '10+ Gbps', '2km', 'Medium', 'Campus backbone'],
            ['Single-Mode Fiber', '100+ Gbps', '100km', 'High', 'WAN, ISP links'],
            ['Wi-Fi 6', '~1 Gbps', '~50m indoor', 'Medium', 'Mobile devices'],
          ] },
        ],
      },
    },
    {
      id: 'm02-l02',
      title: 'Network Devices Explained',
      order: 2,
      type: 'theory',
      estimatedMinutes: 8,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'Network Devices — What Each One Does' },
          { type: 'paragraph', text: 'Each device in a network has a specific job. Understanding what they do is the foundation of everything else you will learn.' },
          { type: 'key-term', term: 'Hub', definition: 'The dumbest device. Receives data on one port and broadcasts it to ALL other ports. Every device sees every packet. No intelligence. Obsolete but important to understand why switches replaced them.' },
          { type: 'key-term', term: 'Switch', definition: 'Smart device. Learns which MAC address is on which port and only sends data to the correct port. Operates at Layer 2. Creates separate collision domains per port. This is what you use in every modern LAN.' },
          { type: 'key-term', term: 'Router', definition: 'Connects different networks together. Operates at Layer 3 using IP addresses. Makes forwarding decisions based on routing tables. Your home router connects your LAN to the internet (WAN).' },
          { type: 'key-term', term: 'Firewall', definition: 'Security device that filters traffic based on rules (ACLs). Can block or allow specific IPs, ports, or protocols. Sits between trusted (inside) and untrusted (outside) networks.' },
          { type: 'key-term', term: 'Wireless Access Point (AP)', definition: 'Bridges wireless clients to the wired network. Like a switch for Wi-Fi devices. Connects to a switch via Ethernet cable.' },
          { type: 'key-term', term: 'Server', definition: 'A computer that provides services to other devices: web hosting, email, DNS, DHCP, file sharing. Has the same network interfaces as a PC but runs server software.' },
          { type: 'callout', variant: 'key-concept', text: 'Hub = broadcast everything (dumb). Switch = send to correct port (smart, Layer 2). Router = connect different networks (smartest, Layer 3).' },
          { type: 'comparison-table', headers: ['Device', 'OSI Layer', 'Uses', 'Intelligence'], rows: [
            ['Hub', 'Layer 1', 'Physical signals', 'None — broadcasts all'],
            ['Switch', 'Layer 2', 'MAC addresses', 'Learns ports → MAC mapping'],
            ['Router', 'Layer 3', 'IP addresses', 'Routing table, forwarding decisions'],
            ['Firewall', 'Layer 3-7', 'IP, ports, protocols', 'ACL rules, stateful inspection'],
            ['AP', 'Layer 2', 'Wi-Fi → Ethernet bridge', 'SSID, authentication'],
          ] },
        ],
      },
    },
    {
      id: 'm02-l03',
      title: 'Ports and Interfaces',
      order: 3,
      type: 'theory',
      estimatedMinutes: 6,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'Ports and Interfaces' },
          { type: 'paragraph', text: 'Every network device has physical ports where you plug in cables. In Cisco IOS, these ports are called "interfaces" and each has a name.' },
          { type: 'heading', level: 2, text: 'Common Interface Types' },
          { type: 'key-term', term: 'FastEthernet (Fa)', definition: '100 Mbps Ethernet port. Common on older switches. Named like Fa0/1, Fa0/2, etc.' },
          { type: 'key-term', term: 'GigabitEthernet (Gi)', definition: '1 Gbps Ethernet port. Standard on modern devices. Named like Gi0/0, Gi0/1.' },
          { type: 'key-term', term: 'Serial (S)', definition: 'WAN port for router-to-router connections. Slower, used for leased lines. Named like S0/0/0.' },
          { type: 'key-term', term: 'Console', definition: 'Management port. Connect a laptop directly to configure the device. Uses a rollover cable. Not for network traffic.' },
          { type: 'callout', variant: 'info', text: 'Interface naming: "GigabitEthernet0/0" means GigabitEthernet type, slot 0, port 0. You can abbreviate it as "gi0/0" in the CLI.' },
          { type: 'heading', level: 2, text: 'Interface Status' },
          { type: 'paragraph', text: 'Every interface has two states:' },
          { type: 'bullet-list', items: [
            'Line protocol (physical layer): Is the cable plugged in and working?',
            'Interface status (admin): Has the admin enabled this port with "no shutdown"?',
          ] },
          { type: 'code-block', code: 'Router# show ip interface brief\nInterface              IP-Address      OK? Method Status                Protocol\nGigabitEthernet0/0     192.168.1.1     YES manual up                    up\nGigabitEthernet0/1     unassigned      YES unset  administratively down down\nSerial0/0/0            unassigned      YES unset  administratively down down' },
          { type: 'callout', variant: 'key-concept', text: '"administratively down" means YOU need to type "no shutdown" to enable the port. "up/up" means the port is working. "up/down" means cable problem.' },
        ],
      },
    },
    {
      id: 'm02-l04',
      title: 'The CLI: Your First Commands',
      order: 4,
      type: 'theory',
      estimatedMinutes: 8,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'Cisco CLI — Your First Commands' },
          { type: 'paragraph', text: 'Cisco devices are configured through a Command Line Interface (CLI). There is no graphical interface. You type commands, and the device responds. This is how real network engineers work.' },
          { type: 'heading', level: 2, text: 'CLI Modes' },
          { type: 'paragraph', text: 'The CLI has different modes, each with different privileges:' },
          { type: 'comparison-table', headers: ['Mode', 'Prompt', 'How to Enter', 'What You Can Do'], rows: [
            ['User EXEC', 'Router>', 'Default on login', 'Basic show commands, ping'],
            ['Privileged EXEC', 'Router#', 'Type: enable', 'All show commands, save config'],
            ['Global Config', 'Router(config)#', 'Type: configure terminal', 'Change device settings'],
            ['Interface Config', 'Router(config-if)#', 'Type: interface gi0/0', 'Configure a specific port'],
          ] },
          { type: 'heading', level: 2, text: 'Essential Commands' },
          { type: 'code-block', code: 'Router> enable                          ! Enter privileged mode\nRouter# configure terminal              ! Enter config mode\nRouter(config)# hostname MyRouter       ! Set device name\nMyRouter(config)# interface gi0/0       ! Select an interface\nMyRouter(config-if)# ip address 192.168.1.1 255.255.255.0  ! Set IP\nMyRouter(config-if)# no shutdown        ! Enable the interface\nMyRouter(config-if)# exit               ! Go back one level\nMyRouter(config)# exit                  ! Back to privileged mode\nMyRouter# show ip interface brief       ! Check your work\nMyRouter# show running-config           ! See full config' },
          { type: 'callout', variant: 'tip', text: 'You can abbreviate commands: "conf t" = "configure terminal", "sh ip int br" = "show ip interface brief", "int gi0/0" = "interface GigabitEthernet0/0".' },
          { type: 'callout', variant: 'warning', text: 'Always type "no shutdown" after configuring an interface! By default, Cisco interfaces are SHUT DOWN. Forgetting this is the #1 beginner mistake.' },
          { type: 'heading', level: 2, text: 'Getting Help' },
          { type: 'bullet-list', items: [
            'Type ? at any point to see available commands',
            'Type a partial command + ? to see options (e.g., "show ?" shows all show commands)',
            'If you make a typo: "% Invalid input detected at \'^\' marker" — the ^ shows where the error is',
          ] },
        ],
      },
    },
    {
      id: 'm02-l05',
      title: 'Ethernet Cable Standards — T-568A & T-568B',
      order: 5,
      type: 'theory',
      estimatedMinutes: 10,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'Ethernet Cable Standards — T-568A & T-568B' },
          { type: 'paragraph', text: 'Inside every Ethernet cable are 8 wires (4 twisted pairs). The order in which these wires connect to the RJ45 plug determines whether the cable works. Two standards define this order: T-568A and T-568B.' },

          { type: 'heading', level: 2, text: 'The 8 Wires (4 Pairs)' },
          { type: 'paragraph', text: 'The wires come in 4 color-coded twisted pairs:' },
          { type: 'comparison-table', headers: ['Pair', 'Colors', 'Function (100Mbps)'], rows: [
            ['Pair 1', 'Blue + Blue-White', 'Unused (or PoE)'],
            ['Pair 2', 'Orange + Orange-White', 'Transmit Data (TX)'],
            ['Pair 3', 'Green + Green-White', 'Receive Data (RX)'],
            ['Pair 4', 'Brown + Brown-White', 'Unused (or PoE)'],
          ] },

          { type: 'heading', level: 2, text: 'T-568B Pin Order (Most Common)' },
          { type: 'paragraph', text: 'T-568B is the most widely used standard in the US and most commercial installations:' },
          { type: 'code-block', code: '  Pin 1: Orange-White     (Transmit +)\n  Pin 2: Orange            (Transmit -)\n  Pin 3: Green-White       (Receive +)\n  Pin 4: Blue              (unused)\n  Pin 5: Blue-White        (unused)\n  Pin 6: Green             (Receive -)\n  Pin 7: Brown-White       (unused)\n  Pin 8: Brown             (unused)' },
          { type: 'callout', variant: 'tip', text: 'Memory trick for T-568B: "OO-GBB-GBrBr" — Orange pair first, then Green-White, Blue pair, Green, Brown pair. The split green pair is what makes it confusing!' },

          { type: 'heading', level: 2, text: 'T-568A Pin Order' },
          { type: 'paragraph', text: 'T-568A swaps the orange and green pairs. Required by US government installations:' },
          { type: 'code-block', code: '  Pin 1: Green-White      (Receive +)\n  Pin 2: Green             (Receive -)\n  Pin 3: Orange-White      (Transmit +)\n  Pin 4: Blue              (unused)\n  Pin 5: Blue-White        (unused)\n  Pin 6: Orange            (Transmit -)\n  Pin 7: Brown-White       (unused)\n  Pin 8: Brown             (unused)' },

          { type: 'heading', level: 2, text: 'Straight-Through vs Crossover vs Rollover' },
          { type: 'comparison-table', headers: ['Cable Type', 'End A', 'End B', 'Used For'], rows: [
            ['Straight-Through', 'T-568B', 'T-568B', 'PC→Switch, Switch→Router (different devices)'],
            ['Crossover', 'T-568A', 'T-568B', 'PC→PC, Switch→Switch (same devices)'],
            ['Rollover', 'Pin 1→8, 2→7...', 'Reversed', 'Console cable (laptop→router console port)'],
          ] },
          { type: 'callout', variant: 'key-concept', text: 'Modern devices have Auto-MDIX which auto-detects the cable type. But for exams and certifications, you MUST know the difference. And in the field, you will crimp cables yourself.' },

          { type: 'heading', level: 2, text: 'Practice: Cable Crimping Simulator' },
          { type: 'paragraph', text: 'We have a built-in cable crimping simulator where you can practice arranging wires in the correct order, crimping them, and testing with a virtual cable tester. Click the button below to try it:' },
          { type: 'callout', variant: 'tip', text: 'Click "Crimping" in the toolbar or navigate to the Cable Crimping Simulator to practice making real Ethernet cables!' },
        ],
      },
    },
    {
      id: 'm02-lab-crimping',
      title: 'Lab: Cable Crimping Challenge',
      order: 6,
      type: 'lab',
      labId: 'lab-19-cable-crimping',
      estimatedMinutes: 5,
    },
    {
      id: 'm02-l06',
      title: 'Fiber Optic Cables & Connectors',
      order: 7,
      type: 'theory',
      estimatedMinutes: 8,
      content: {
        sections: [
          { type: 'heading', level: 1, text: 'Fiber Optic Cables' },
          { type: 'paragraph', text: 'Fiber optic cables use light instead of electricity to transmit data. They are faster, go farther, and are immune to electromagnetic interference (EMI). Every data center backbone, ISP link, and campus uplink uses fiber.' },

          { type: 'heading', level: 2, text: 'Single-Mode vs Multi-Mode' },
          { type: 'comparison-table', headers: ['Feature', 'Single-Mode (SMF)', 'Multi-Mode (MMF)'], rows: [
            ['Core Size', '9 μm (tiny)', '50 or 62.5 μm (larger)'],
            ['Light Source', 'Laser', 'LED or VCSEL'],
            ['Distance', 'Up to 100 km', 'Up to 2 km'],
            ['Speed', '100+ Gbps', '10-100 Gbps'],
            ['Cost', 'Higher (laser + precision)', 'Lower'],
            ['Color Code', 'Yellow jacket', 'Orange or aqua jacket'],
            ['Use Case', 'WAN, ISP, long campus runs', 'Data center, building backbone'],
          ] },

          { type: 'heading', level: 2, text: 'Fiber Connector Types' },
          { type: 'key-term', term: 'LC (Lucent Connector)', definition: 'Small form factor, most common in data centers. Push-pull latch. Often used in pairs (duplex LC).' },
          { type: 'key-term', term: 'SC (Subscriber Connector)', definition: 'Square shape, push-pull. Common in telecom and older installations.' },
          { type: 'key-term', term: 'ST (Straight Tip)', definition: 'Round, bayonet-style twist-lock. Older standard, still found in legacy networks.' },
          { type: 'key-term', term: 'MTP/MPO', definition: 'Multi-fiber connector (12 or 24 fibers). Used for high-density data center connections (40G/100G).' },

          { type: 'heading', level: 2, text: 'Fiber vs Copper — When to Use Which' },
          { type: 'comparison-table', headers: ['Scenario', 'Use Copper', 'Use Fiber'], rows: [
            ['Office desk → Switch', '✅ Cat6 (cheap, easy)', '❌ Overkill'],
            ['Switch → Switch (same room)', '✅ Cat6a', '✅ If >55m or 10G'],
            ['Building → Building', '❌ 100m limit', '✅ Fiber (distance)'],
            ['ISP backbone', '❌', '✅ Always fiber'],
            ['PoE devices (cameras, APs)', '✅ Copper carries power', '❌ Fiber has no power'],
          ] },

          { type: 'callout', variant: 'key-concept', text: 'Rule of thumb: Copper for the last 100 meters (desk to switch). Fiber for everything between switches, buildings, and beyond.' },

          { type: 'heading', level: 2, text: 'SFP Modules — Plugging Fiber into Switches' },
          { type: 'paragraph', text: 'Switches and routers have SFP (Small Form-factor Pluggable) slots. You insert an SFP module that matches your fiber type, then plug the fiber cable into the SFP. This is how fiber connects to network devices.' },
          { type: 'bullet-list', items: [
            'SFP = 1 Gbps',
            'SFP+ = 10 Gbps',
            'SFP28 = 25 Gbps',
            'QSFP+ = 40 Gbps',
            'QSFP28 = 100 Gbps',
          ] },
        ],
      },
    },
    {
      id: 'm02-l07',
      title: 'Lab: Your First Network',
      order: 8,
      type: 'lab',
      labId: 'lab-01-basic-connectivity',
      estimatedMinutes: 10,
    },
  ],
  quiz: {
    id: 'quiz-module-02',
    moduleId: 'module-02',
    passingScore: 70,
    questions: [
      {
        id: 'q02-01', text: 'Which cable type connects DIFFERENT devices (e.g., PC to Switch)?',
        options: [
          { id: 'a', text: 'Crossover cable', correct: false },
          { id: 'b', text: 'Straight-through cable', correct: true },
          { id: 'c', text: 'Rollover cable', correct: false },
          { id: 'd', text: 'Fiber optic cable', correct: false },
        ],
        explanation: 'Straight-through cables connect different device types (PC→Switch, Switch→Router). Crossover cables connect same types (Switch→Switch).',
      },
      {
        id: 'q02-02', text: 'What is the main advantage of fiber optic over copper?',
        options: [
          { id: 'a', text: 'Cheaper cost', correct: false },
          { id: 'b', text: 'Easier to install', correct: false },
          { id: 'c', text: 'Longer distance and immune to EMI', correct: true },
          { id: 'd', text: 'Thicker cable', correct: false },
        ],
        explanation: 'Fiber uses light instead of electricity, so it is immune to electromagnetic interference and can travel much farther (up to 100km for single-mode).',
      },
      {
        id: 'q02-03', text: 'A Hub receives data on one port and ___.',
        options: [
          { id: 'a', text: 'Sends it only to the destination port', correct: false },
          { id: 'b', text: 'Broadcasts it to ALL other ports', correct: true },
          { id: 'c', text: 'Drops it', correct: false },
          { id: 'd', text: 'Encrypts it first', correct: false },
        ],
        explanation: 'Hubs are "dumb" — they broadcast every frame to every port. Switches are smarter and send frames only to the correct port.',
      },
      {
        id: 'q02-04', text: 'What command enables a Cisco interface that is shut down?',
        options: [
          { id: 'a', text: 'enable', correct: false },
          { id: 'b', text: 'start interface', correct: false },
          { id: 'c', text: 'no shutdown', correct: true },
          { id: 'd', text: 'interface up', correct: false },
        ],
        explanation: '"no shutdown" enables a Cisco interface. By default, all interfaces are administratively shut down.',
      },
      {
        id: 'q02-05', text: 'What does "Router(config-if)#" mean?',
        options: [
          { id: 'a', text: 'You are in user EXEC mode', correct: false },
          { id: 'b', text: 'You are configuring a specific interface', correct: true },
          { id: 'c', text: 'You are in privileged mode', correct: false },
          { id: 'd', text: 'The router is rebooting', correct: false },
        ],
        explanation: '(config-if) means interface configuration mode. You entered it with "interface <name>" and can configure IP addresses, shutdown state, etc.',
      },
      {
        id: 'q02-06', text: 'Which command shows all interfaces and their IP/status in a compact table?',
        options: [
          { id: 'a', text: 'show interfaces', correct: false },
          { id: 'b', text: 'show ip interface brief', correct: true },
          { id: 'c', text: 'show running-config', correct: false },
          { id: 'd', text: 'show status', correct: false },
        ],
        explanation: '"show ip interface brief" shows a compact table with interface names, IPs, and up/down status. It is the #1 troubleshooting command.',
      },
      {
        id: 'q02-07', text: 'GigabitEthernet operates at what speed?',
        options: [
          { id: 'a', text: '10 Mbps', correct: false },
          { id: 'b', text: '100 Mbps', correct: false },
          { id: 'c', text: '1 Gbps (1000 Mbps)', correct: true },
          { id: 'd', text: '10 Gbps', correct: false },
        ],
        explanation: 'GigabitEthernet = 1 Gbps = 1000 Mbps. FastEthernet = 100 Mbps. 10GbE = 10 Gbps.',
      },
      {
        id: 'q02-08', text: 'Serial interfaces are used for which type of connection?',
        options: [
          { id: 'a', text: 'LAN connections (PC to Switch)', correct: false },
          { id: 'b', text: 'WAN connections (Router to Router)', correct: true },
          { id: 'c', text: 'Wireless connections', correct: false },
          { id: 'd', text: 'Console management', correct: false },
        ],
        explanation: 'Serial interfaces are used for WAN links — connecting routers across long distances via leased lines from ISPs.',
      },
      {
        id: 'q02-09', text: 'In T-568B, what color wire is on Pin 1?',
        options: [
          { id: 'a', text: 'Green-White', correct: false },
          { id: 'b', text: 'Orange-White', correct: true },
          { id: 'c', text: 'Blue', correct: false },
          { id: 'd', text: 'Brown-White', correct: false },
        ],
        explanation: 'T-568B starts with Orange-White on Pin 1, then Orange on Pin 2. T-568A starts with Green-White. This is the most important difference to memorize.',
      },
      {
        id: 'q02-10', text: 'A crossover cable uses which standards on each end?',
        options: [
          { id: 'a', text: 'T-568B on both ends', correct: false },
          { id: 'b', text: 'T-568A on one end, T-568B on the other', correct: true },
          { id: 'c', text: 'T-568A on both ends', correct: false },
          { id: 'd', text: 'No standard — random order', correct: false },
        ],
        explanation: 'Crossover cables swap transmit and receive pairs by using T-568A on one end and T-568B on the other. Used for connecting same device types (switch→switch).',
      },
      {
        id: 'q02-11', text: 'What color jacket indicates single-mode fiber?',
        options: [
          { id: 'a', text: 'Orange', correct: false },
          { id: 'b', text: 'Aqua', correct: false },
          { id: 'c', text: 'Yellow', correct: true },
          { id: 'd', text: 'Blue', correct: false },
        ],
        explanation: 'Yellow = single-mode fiber (long distance, laser). Orange = multi-mode fiber (short distance, LED). Aqua = OM3/OM4 multi-mode (10G+ optimized).',
      },
      {
        id: 'q02-12', text: 'Which connector type is most common in modern data centers for fiber?',
        options: [
          { id: 'a', text: 'ST (Straight Tip)', correct: false },
          { id: 'b', text: 'SC (Subscriber Connector)', correct: false },
          { id: 'c', text: 'LC (Lucent Connector)', correct: true },
          { id: 'd', text: 'RJ45', correct: false },
        ],
        explanation: 'LC connectors are the standard in modern data centers — small form factor, duplex, push-pull. ST is legacy. SC is telecom. RJ45 is for copper.',
      },
    ],
  },
  badge: {
    id: 'badge-module-02',
    name: 'Hardware Specialist',
    description: 'Completed Module 2: Physical Layer',
    icon: '🔌',
    color: '#22cc88',
    tier: 'bronze',
  },
};
