import type { Lab } from './lab-types.js';

export const LABS: Lab[] = [
  // ============================================================
  // BEGINNER LABS (1-3): Learn the basics — no CLI needed for Lab 1
  // ============================================================
  {
    id: 'lab-01-basic-connectivity',
    title: 'Lab 1: Your First Network',
    difficulty: 'beginner',
    description: 'Learn the basics — add devices and connect them with a cable. No CLI configuration needed.',
    instructions: [
      '--- START WITH A CLEAN CANVAS (use "Clear All" button if needed) ---',
      '',
      'STEP 1: Add devices',
      '  • Drag a PC from the left palette onto the canvas',
      '  • Drag a Switch from the left palette onto the canvas',
      '',
      'STEP 2: Connect them',
      '  • Click a blue port dot on the PC',
      '  • A dashed line follows your cursor',
      '  • Click a blue port dot on the Switch',
      '  • A solid cable appears — you connected them!',
      '',
      'DONE! You just built your first network.',
      'Next: Lab 2 teaches you how to configure IP addresses.',
    ],
    objectives: [
      {
        id: 'add-pc',
        description: 'Add a PC to the canvas',
        type: 'device-exists',
        params: { deviceType: 'pc' },
        hint: 'Drag "PC" from the left panel onto the canvas.',
      },
      {
        id: 'add-switch',
        description: 'Add a Switch to the canvas',
        type: 'device-exists',
        params: { deviceType: 'switch' },
        hint: 'Drag "Switch" from the left panel onto the canvas.',
      },
      {
        id: 'connect-them',
        description: 'Connect the PC to the Switch with a cable',
        type: 'connection-exists',
        params: {},
        hint: 'Click a blue port dot on the PC, then click a port on the Switch.',
      },
    ],
  },
  {
    id: 'lab-02-ip-addressing',
    title: 'Lab 2: IP Addressing',
    difficulty: 'beginner',
    description: 'Configure IP addresses on a Router and PC, then verify they can communicate with ping.',
    instructions: [
      '--- START WITH A CLEAN CANVAS ---',
      '',
      'STEP 1: Build the topology',
      '  • Drag 1 Router and 1 PC onto the canvas',
      '  • Connect them: click a port on the Router → click a port on the PC',
      '',
      'STEP 2: Configure the Router',
      '  • Double-click the Router to open its CLI terminal',
      '  • Type these commands one by one:',
      '    enable',
      '    configure terminal',
      '    interface gi0/0',
      '    ip address 192.168.1.1 255.255.255.0',
      '    no shutdown',
      '    exit',
      '    exit',
      '',
      'STEP 3: Configure the PC',
      '  • Double-click the PC to open its CLI terminal',
      '  • Type:',
      '    enable',
      '    configure terminal',
      '    interface e0',
      '    ip address 192.168.1.2 255.255.255.0',
      '    no shutdown',
      '    exit',
      '    exit',
      '',
      'STEP 4: Test connectivity',
      '  • In the PC terminal, type:',
      '    ping 192.168.1.1',
      '  • Check the Packet Log (right panel) — it should say "5/5 packets"',
      '',
      'CONGRATULATIONS! You just configured your first IP network.',
    ],
    objectives: [
      {
        id: 'add-router',
        description: 'Add a Router to the canvas',
        type: 'device-exists',
        params: { deviceType: 'router' },
      },
      {
        id: 'add-pc',
        description: 'Add a PC to the canvas',
        type: 'device-exists',
        params: { deviceType: 'pc' },
      },
      {
        id: 'connect',
        description: 'Connect the Router and PC with a cable',
        type: 'connection-exists',
        params: {},
        hint: 'Click a port on the Router, then a port on the PC.',
      },
      {
        id: 'ip-router',
        description: 'Configure IP 192.168.1.1 on the Router',
        type: 'ip-configured',
        params: { deviceType: 'router' },
        hint: 'Double-click Router → enable → conf t → int gi0/0 → ip address 192.168.1.1 255.255.255.0 → no shut',
      },
      {
        id: 'ip-pc',
        description: 'Configure IP 192.168.1.2 on the PC',
        type: 'ip-configured',
        params: { deviceType: 'pc' },
        hint: 'Double-click PC → enable → conf t → int e0 → ip address 192.168.1.2 255.255.255.0 → no shut',
      },
      {
        id: 'ping-success',
        description: 'Ping the Router from the PC successfully',
        type: 'ping-success',
        params: {},
        hint: 'In PC terminal: ping 192.168.1.1',
      },
    ],
  },
  {
    id: 'lab-03-subnetting',
    title: 'Lab 3: Same Subnet, Same Team',
    difficulty: 'beginner',
    description: 'Connect 3 PCs to a Switch and make them all communicate. Learn why they must be on the same subnet.',
    instructions: [
      '--- START WITH A CLEAN CANVAS ---',
      '',
      'STEP 1: Build the topology',
      '  • Drag 1 Switch and 3 PCs onto the canvas',
      '  • Connect all 3 PCs to the Switch (3 cables total)',
      '',
      'STEP 2: Configure all PCs on the SAME subnet (10.10.10.0/24)',
      '  • Double-click PC1 → CLI:',
      '    enable → conf t → int e0 → ip address 10.10.10.10 255.255.255.0 → no shut → exit → exit',
      '  • Double-click PC2 → CLI:',
      '    enable → conf t → int e0 → ip address 10.10.10.20 255.255.255.0 → no shut → exit → exit',
      '  • Double-click PC3 → CLI:',
      '    enable → conf t → int e0 → ip address 10.10.10.30 255.255.255.0 → no shut → exit → exit',
      '',
      'STEP 3: Test',
      '  • From PC1: ping 10.10.10.20 (should succeed)',
      '  • From PC1: ping 10.10.10.30 (should succeed)',
      '',
      'CHALLENGE: Change PC3 to 10.10.20.30 (different subnet). Ping fails! Why?',
      'Answer: Devices must share the same subnet to communicate directly.',
    ],
    objectives: [
      {
        id: 'devices',
        description: 'Add 1 Switch and 3 PCs (4 devices total)',
        type: 'device-count',
        params: { deviceType: 'any', count: 4 },
      },
      {
        id: 'connections',
        description: 'Connect all 3 PCs to the Switch (3 cables)',
        type: 'connection-count',
        params: { count: 3 },
      },
      {
        id: 'ip-pcs',
        description: 'Configure IP addresses on all 3 PCs',
        type: 'ip-configured',
        params: { deviceType: 'pc' },
        hint: 'Each PC: enable → conf t → int e0 → ip address 10.10.10.X 255.255.255.0 → no shut',
      },
      {
        id: 'ping',
        description: 'Successfully ping between PCs',
        type: 'ping-success',
        params: {},
        hint: 'From PC1: ping 10.10.10.20',
      },
    ],
  },

  // ============================================================
  // INTERMEDIATE LABS (4-6): Multi-device networks + VLANs
  // ============================================================
  {
    id: 'lab-04-multi-device',
    title: 'Lab 4: Multi-Device Network',
    difficulty: 'intermediate',
    description: 'Build a network with a Router, Switch, and multiple PCs. Set custom hostnames and verify full connectivity.',
    instructions: [
      '--- START WITH A CLEAN CANVAS ---',
      '',
      'STEP 1: Build the topology',
      '  • Drag: 1 Router, 1 Switch, 2 PCs',
      '  • Connect: Router→Switch, Switch→PC1, Switch→PC2',
      '',
      'STEP 2: Configure the Router',
      '  • Double-click Router → CLI:',
      '    enable',
      '    configure terminal',
      '    hostname CoreRouter',
      '    interface gi0/0',
      '    ip address 10.0.0.1 255.255.255.0',
      '    no shutdown',
      '    exit',
      '    exit',
      '',
      'STEP 3: Configure PCs',
      '  • Double-click PC1 → CLI:',
      '    enable → conf t → int e0 → ip address 10.0.0.10 255.255.255.0 → no shut → exit → exit',
      '  • Double-click PC2 → CLI:',
      '    enable → conf t → int e0 → ip address 10.0.0.20 255.255.255.0 → no shut → exit → exit',
      '',
      'STEP 4: Test from any PC',
      '  • ping 10.0.0.1 (Router)',
      '  • The Switch does NOT need an IP — it operates at Layer 2.',
    ],
    objectives: [
      {
        id: 'devices',
        description: 'Add at least 4 devices (Router + Switch + 2 PCs)',
        type: 'device-count',
        params: { deviceType: 'any', count: 4 },
      },
      {
        id: 'connections',
        description: 'Create at least 3 cable connections',
        type: 'connection-count',
        params: { count: 3 },
      },
      {
        id: 'hostname',
        description: 'Set a custom hostname on the Router (not "Router")',
        type: 'hostname-set',
        params: { deviceType: 'router' },
        hint: 'Router CLI: enable → conf t → hostname CoreRouter',
      },
      {
        id: 'ip-router',
        description: 'Configure IP on the Router',
        type: 'ip-configured',
        params: { deviceType: 'router' },
      },
      {
        id: 'ip-pcs',
        description: 'Configure IPs on both PCs',
        type: 'ip-configured',
        params: { deviceType: 'pc' },
      },
      {
        id: 'ping',
        description: 'Successfully ping the Router from a PC',
        type: 'ping-success',
        params: {},
        hint: 'From any PC: ping 10.0.0.1',
      },
    ],
  },
  {
    id: 'lab-05-server-network',
    title: 'Lab 5: Server Infrastructure',
    difficulty: 'intermediate',
    description: 'Build a client-server network with a Server, Router, Switch, and PCs.',
    instructions: [
      '--- START WITH A CLEAN CANVAS ---',
      '',
      'STEP 1: Build the topology',
      '  • Drag: 1 Router, 1 Switch, 1 Server, 2 PCs',
      '  • Connect all to the Switch: Router→Switch, Server→Switch, PC1→Switch, PC2→Switch',
      '',
      'STEP 2: Configure the Router',
      '  • Double-click Router → CLI:',
      '    enable → conf t → int gi0/0 → ip address 172.16.0.1 255.255.255.0 → no shut → exit → exit',
      '',
      'STEP 3: Configure the Server',
      '  • Double-click Server → CLI:',
      '    enable → conf t → int e0 → ip address 172.16.0.100 255.255.255.0 → no shut → exit → exit',
      '',
      'STEP 4: Configure PCs',
      '  • PC1: ip address 172.16.0.10 255.255.255.0',
      '  • PC2: ip address 172.16.0.20 255.255.255.0',
      '  • (same steps: enable → conf t → int e0 → ip address ... → no shut)',
      '',
      'STEP 5: Test — from any PC:',
      '  • ping 172.16.0.100 (Server)',
      '  • ping 172.16.0.1 (Router)',
    ],
    objectives: [
      {
        id: 'server',
        description: 'Add a Server',
        type: 'device-exists',
        params: { deviceType: 'server' },
      },
      {
        id: 'devices',
        description: 'Add at least 5 devices total',
        type: 'device-count',
        params: { deviceType: 'any', count: 5 },
      },
      {
        id: 'connections',
        description: 'Create at least 4 cables',
        type: 'connection-count',
        params: { count: 4 },
      },
      {
        id: 'ip-router',
        description: 'Configure IP on the Router',
        type: 'ip-configured',
        params: { deviceType: 'router' },
      },
      {
        id: 'ip-server',
        description: 'Configure IP on the Server',
        type: 'ip-configured',
        params: { deviceType: 'server' },
      },
      {
        id: 'ip-pcs',
        description: 'Configure IPs on both PCs',
        type: 'ip-configured',
        params: { deviceType: 'pc' },
      },
      {
        id: 'ping',
        description: 'Successfully ping the Server from a PC',
        type: 'ping-success',
        params: {},
        hint: 'From any PC: ping 172.16.0.100',
      },
    ],
  },
  {
    id: 'lab-06-vlans',
    title: 'Lab 6: VLANs — Separating Traffic',
    difficulty: 'intermediate',
    description: 'Create VLANs on a switch to separate departments. Discover why devices on different subnets cannot ping each other.',
    instructions: [
      '--- START WITH A CLEAN CANVAS ---',
      '',
      'CONCEPT: VLANs logically divide a switch into separate networks.',
      'Devices on different VLANs/subnets cannot communicate without a router.',
      '',
      'STEP 1: Build the topology',
      '  • Drag 1 Switch and 3 PCs onto the canvas',
      '  • Connect all 3 PCs to the Switch',
      '',
      'STEP 2: Configure PCs on TWO different subnets',
      '  • PC1 (HR): enable → conf t → int e0 → ip address 192.168.10.1 255.255.255.0 → no shut',
      '  • PC2 (HR): enable → conf t → int e0 → ip address 192.168.10.2 255.255.255.0 → no shut',
      '  • PC3 (Eng): enable → conf t → int e0 → ip address 192.168.20.1 255.255.255.0 → no shut',
      '',
      'STEP 3: Create VLANs on the Switch',
      '  • Double-click Switch → CLI:',
      '    enable',
      '    configure terminal',
      '    vlan 10',
      '    name HR',
      '    exit',
      '    vlan 20',
      '    name Engineering',
      '    exit',
      '    exit',
      '',
      'STEP 4: Test',
      '  • From PC1: ping 192.168.10.2 → SUCCEEDS (same subnet)',
      '  • From PC1: ping 192.168.20.1 → FAILS (different subnet, no router)',
      '',
      'KEY LESSON: Same subnet = can talk. Different subnet = need a router.',
    ],
    objectives: [
      {
        id: 'devices',
        description: 'Add 1 Switch and 3 PCs',
        type: 'device-count',
        params: { deviceType: 'any', count: 4 },
      },
      {
        id: 'connections',
        description: 'Connect all 3 PCs to the Switch',
        type: 'connection-count',
        params: { count: 3 },
      },
      {
        id: 'ip-pcs',
        description: 'Configure IPs on all 3 PCs (two subnets)',
        type: 'ip-configured',
        params: { deviceType: 'pc' },
        hint: 'PC1: 192.168.10.1, PC2: 192.168.10.2, PC3: 192.168.20.1',
      },
      {
        id: 'ping',
        description: 'Successfully ping between PCs on the same subnet',
        type: 'ping-success',
        params: {},
        hint: 'From PC1: ping 192.168.10.2 (same /24 subnet)',
      },
    ],
  },

  // ============================================================
  // ADVANCED LABS (7-8): Routing + Troubleshooting
  // ============================================================
  {
    id: 'lab-07-static-routing',
    title: 'Lab 7: Static Routing Between Networks',
    difficulty: 'advanced',
    description: 'Connect two separate networks through a Router. Learn how routers forward traffic between subnets.',
    instructions: [
      '--- START WITH A CLEAN CANVAS ---',
      '',
      'TOPOLOGY: PC1 ─── Switch1 ─── Router ─── Switch2 ─── PC2',
      'Network A: 192.168.1.0/24 (left side)',
      'Network B: 192.168.2.0/24 (right side)',
      '',
      'STEP 1: Build it',
      '  • Drag: 1 Router, 2 Switches, 2 PCs',
      '  • Connect: PC1→Switch1→Router→Switch2→PC2 (4 cables)',
      '  • Use Router port gi0/0 for Switch1, gi0/1 for Switch2',
      '',
      'STEP 2: Configure the Router with TWO interfaces',
      '  • Double-click Router → CLI:',
      '    enable',
      '    configure terminal',
      '    hostname GatewayRouter',
      '    interface gi0/0',
      '    ip address 192.168.1.1 255.255.255.0',
      '    no shutdown',
      '    exit',
      '    interface gi0/1',
      '    ip address 192.168.2.1 255.255.255.0',
      '    no shutdown',
      '    exit',
      '    exit',
      '',
      'STEP 3: Configure PCs on DIFFERENT networks',
      '  • PC1: enable → conf t → int e0 → ip address 192.168.1.10 255.255.255.0 → no shut',
      '  • PC2: enable → conf t → int e0 → ip address 192.168.2.10 255.255.255.0 → no shut',
      '',
      'STEP 4: Test cross-network communication',
      '  • From PC1: ping 192.168.2.10',
      '  • The Router forwards the packet between networks!',
      '',
      'KEY LESSON: A Router with one interface on each subnet acts as a gateway.',
    ],
    objectives: [
      {
        id: 'devices',
        description: 'Add 5 devices (1 Router + 2 Switches + 2 PCs)',
        type: 'device-count',
        params: { deviceType: 'any', count: 5 },
      },
      {
        id: 'connections',
        description: 'Create 4 cable connections',
        type: 'connection-count',
        params: { count: 4 },
      },
      {
        id: 'ip-router',
        description: 'Configure TWO IPs on the Router (one per network)',
        type: 'ip-configured',
        params: { deviceType: 'router' },
        hint: 'gi0/0 = 192.168.1.1 and gi0/1 = 192.168.2.1',
      },
      {
        id: 'ip-pcs',
        description: 'Configure PCs on different subnets',
        type: 'ip-configured',
        params: { deviceType: 'pc' },
        hint: 'PC1 = 192.168.1.10, PC2 = 192.168.2.10',
      },
      {
        id: 'ping',
        description: 'Ping from PC1 to PC2 across the Router',
        type: 'ping-success',
        params: {},
        hint: 'From PC1: ping 192.168.2.10',
      },
    ],
  },
  {
    id: 'lab-08-troubleshooting',
    title: 'Lab 8: Troubleshooting Challenge',
    difficulty: 'advanced',
    description: 'Build a network with an intentional mistake, diagnose it using CLI commands, and fix it.',
    instructions: [
      '--- START WITH A CLEAN CANVAS ---',
      '',
      'In this lab, you will intentionally break something, then fix it.',
      'This is how real network engineers troubleshoot!',
      '',
      'STEP 1: Build the topology',
      '  • Drag: 1 Router, 1 Switch, 1 PC',
      '  • Connect: PC → Switch → Router (2 cables)',
      '',
      'STEP 2: Configure the Router correctly',
      '  • Double-click Router → CLI:',
      '    enable',
      '    configure terminal',
      '    hostname MainRouter',
      '    interface gi0/0',
      '    ip address 10.0.0.1 255.255.255.0',
      '    no shutdown',
      '    exit',
      '    exit',
      '',
      'STEP 3: Configure the PC with a WRONG IP (on purpose!)',
      '  • Double-click PC → CLI:',
      '    enable',
      '    configure terminal',
      '    interface e0',
      '    ip address 10.0.1.100 255.255.255.0',
      '    no shutdown',
      '    exit',
      '    exit',
      '  • Notice: 10.0.1.100 — that is subnet 10.0.1.0, NOT 10.0.0.0!',
      '',
      'STEP 4: Test — ping should FAIL',
      '  • ping 10.0.0.1 → FAILS because subnets don\'t match',
      '',
      'STEP 5: Diagnose',
      '  • Type: show ip interface brief',
      '  • Compare IPs: Router is 10.0.0.1/24, PC is 10.0.1.100/24',
      '  • They are on DIFFERENT subnets! That is the bug.',
      '',
      'STEP 6: Fix it',
      '  • configure terminal',
      '  • interface e0',
      '  • ip address 10.0.0.100 255.255.255.0',
      '  • exit',
      '  • exit',
      '',
      'STEP 7: Test again',
      '  • ping 10.0.0.1 → SUCCEEDS!',
      '',
      'KEY LESSON: "show ip interface brief" is your #1 troubleshooting tool.',
      'Always check that devices on the same link share the same subnet.',
    ],
    objectives: [
      {
        id: 'devices',
        description: 'Add a Router, Switch, and PC (3 devices)',
        type: 'device-count',
        params: { deviceType: 'any', count: 3 },
      },
      {
        id: 'connections',
        description: 'Connect: PC → Switch → Router (2 cables)',
        type: 'connection-count',
        params: { count: 2 },
      },
      {
        id: 'ip-router',
        description: 'Configure Router with IP 10.0.0.1/24',
        type: 'ip-configured',
        params: { deviceType: 'router' },
      },
      {
        id: 'ip-pc',
        description: 'Configure an IP on the PC',
        type: 'ip-configured',
        params: { deviceType: 'pc' },
        hint: 'Start with 10.0.1.100 (wrong), then fix to 10.0.0.100',
      },
      {
        id: 'hostname',
        description: 'Set custom hostname on the Router',
        type: 'hostname-set',
        params: { deviceType: 'router' },
        hint: 'hostname MainRouter',
      },
      {
        id: 'ping',
        description: 'Successfully ping after fixing the problem',
        type: 'ping-success',
        params: {},
        hint: 'Fix PC IP to 10.0.0.100, then ping 10.0.0.1',
      },
    ],
  },

  // ============================================================
  // ADVANCED LABS (9-12): ACLs, NAT, OSPF
  // ============================================================
  {
    id: 'lab-09-acl-basics',
    title: 'Lab 9: Access Control Lists (ACLs)',
    difficulty: 'advanced',
    description: 'Use ACLs to block specific traffic while allowing everything else. Traffic MUST pass through the Router for ACLs to work!',
    instructions: [
      '--- START WITH A CLEAN CANVAS ---',
      '',
      'SCENARIO: PCs are on one network, Server is on another.',
      'All traffic must go through the Router. You will block PC2 using an ACL.',
      '',
      'IMPORTANT: ACLs only filter traffic that passes THROUGH the device.',
      'If devices are on the same switch/subnet, traffic goes directly — the Router never sees it.',
      'That is why we put the Server on a SEPARATE network behind the Router.',
      '',
      'TOPOLOGY:',
      '  PC1 ─┐',
      '       ├── Switch1 ─── Router ─── Switch2 ─── Server',
      '  PC2 ─┘',
      '  (192.168.1.0/24)              (10.0.0.0/24)',
      '',
      'STEP 1: Build the topology',
      '  • Drag: 1 Router, 2 Switches, 1 Server, 2 PCs',
      '  • Connect:',
      '    - PC1 → Switch1',
      '    - PC2 → Switch1',
      '    - Switch1 → Router (gi0/0)',
      '    - Router (gi0/1) → Switch2',
      '    - Switch2 → Server',
      '',
      'STEP 2: Configure the Router (gateway between both networks)',
      '  • Double-click Router → CLI:',
      '    enable',
      '    configure terminal',
      '    hostname ACLRouter',
      '    interface gi0/0',
      '    ip address 192.168.1.1 255.255.255.0',
      '    no shutdown',
      '    exit',
      '    interface gi0/1',
      '    ip address 10.0.0.1 255.255.255.0',
      '    no shutdown',
      '    exit',
      '    exit',
      '',
      'STEP 3: Configure PCs (on 192.168.1.0/24)',
      '  • PC1: enable → conf t → int e0 → ip address 192.168.1.10 255.255.255.0 → no shut',
      '  • PC2: enable → conf t → int e0 → ip address 192.168.1.20 255.255.255.0 → no shut',
      '',
      'STEP 4: Configure Server (on 10.0.0.0/24)',
      '  • Server: enable → conf t → int e0 → ip address 10.0.0.100 255.255.255.0 → no shut',
      '',
      'STEP 5: Test — BOTH PCs should reach the Server',
      '  • PC1: ping 10.0.0.100 → should succeed (traffic goes through Router)',
      '  • PC2: ping 10.0.0.100 → should succeed',
      '',
      'STEP 6: Now add an ACL to BLOCK PC2',
      '  • Double-click Router → CLI:',
      '    enable',
      '    configure terminal',
      '    access-list 10 deny 192.168.1.20 0.0.0.0',
      '    access-list 10 permit any',
      '    interface gi0/0',
      '    ip access-group 10 in',
      '    exit',
      '    exit',
      '',
      'STEP 7: Test again',
      '  • PC1: ping 10.0.0.100 → STILL WORKS (permitted by "permit any")',
      '  • PC2: ping 10.0.0.100 → BLOCKED! (denied by ACL 10)',
      '',
      'STEP 8: Verify',
      '  • On Router: show access-lists',
      '',
      'KEY LESSONS:',
      '  1. ACLs only work on traffic passing THROUGH the device',
      '  2. "deny" blocks matching source IPs',
      '  3. "permit any" at the end allows everything else',
      '  4. Without "permit any", there is an IMPLICIT DENY ALL',
      '  5. Traffic between devices on the same switch never hits the Router',
    ],
    objectives: [
      {
        id: 'devices',
        description: 'Add 6 devices (Router + 2 Switches + Server + 2 PCs)',
        type: 'device-count',
        params: { deviceType: 'any', count: 6 },
      },
      {
        id: 'connections',
        description: 'Create at least 5 cable connections',
        type: 'connection-count',
        params: { count: 5 },
      },
      {
        id: 'ip-router',
        description: 'Configure 2 IPs on the Router (one per network)',
        type: 'ip-configured',
        params: { deviceType: 'router' },
        hint: 'gi0/0 = 192.168.1.1, gi0/1 = 10.0.0.1',
      },
      {
        id: 'ip-server',
        description: 'Configure IP on the Server (10.0.0.100)',
        type: 'ip-configured',
        params: { deviceType: 'server' },
      },
      {
        id: 'ip-pcs',
        description: 'Configure IPs on both PCs (192.168.1.x)',
        type: 'ip-configured',
        params: { deviceType: 'pc' },
      },
      {
        id: 'hostname',
        description: 'Set hostname on the Router',
        type: 'hostname-set',
        params: { deviceType: 'router' },
        hint: 'hostname ACLRouter',
      },
      {
        id: 'ping',
        description: 'Successfully ping the Server from PC1 (the permitted PC)',
        type: 'ping-success',
        params: {},
        hint: 'From PC1: ping 10.0.0.100',
      },
    ],
  },
  {
    id: 'lab-10-nat-concepts',
    title: 'Lab 10: NAT — Network Address Translation',
    difficulty: 'advanced',
    description: 'Learn NAT concepts by configuring a Router that connects a private network to a public network. Configure NAT commands and understand the translation.',
    instructions: [
      '--- START WITH A CLEAN CANVAS ---',
      '',
      'CONCEPT: NAT translates private IPs (192.168.x.x) to public IPs (203.0.113.x)',
      'so internal devices can reach the internet.',
      '',
      'TOPOLOGY:',
      '  Server ─── Switch1 ─── Router ─── Switch2 ─── PC (simulates internet)',
      '  (Private: 192.168.1.0/24)      (Public: 203.0.113.0/24)',
      '',
      'STEP 1: Build the topology',
      '  • Drag: 1 Router, 2 Switches, 1 Server, 1 PC',
      '  • Connect: Server→Switch1→Router(gi0/0)→(gi0/1)Router→Switch2→PC',
      '',
      'STEP 2: Configure the Router',
      '  • Double-click Router → CLI:',
      '    enable',
      '    configure terminal',
      '    hostname NATRouter',
      '    interface gi0/0',
      '    ip address 192.168.1.1 255.255.255.0',
      '    ip nat inside',
      '    no shutdown',
      '    exit',
      '    interface gi0/1',
      '    ip address 203.0.113.1 255.255.255.0',
      '    ip nat outside',
      '    no shutdown',
      '    exit',
      '    ip nat inside source static 192.168.1.100 203.0.113.10',
      '    exit',
      '',
      'STEP 3: Configure devices',
      '  • Server: enable → conf t → int e0 → ip address 192.168.1.100 255.255.255.0 → no shut',
      '  • PC:     enable → conf t → int e0 → ip address 203.0.113.50 255.255.255.0 → no shut',
      '',
      'STEP 4: Verify NAT config',
      '  • On Router: show ip nat translations',
      '  • You should see: 192.168.1.100 → 203.0.113.10',
      '',
      'STEP 5: Test connectivity (Router has both subnets, so ping works)',
      '  • From Server: ping 203.0.113.1 (Router outside)',
      '  • From PC: ping 192.168.1.1 (Router inside — Router routes between both)',
      '',
      'NOTE: In our simulator, the Router forwards between subnets because it has',
      'interfaces on both networks. In real life, NAT would translate the source IP',
      'before forwarding. The key takeaway is the NAT configuration commands.',
      '',
      'KEY LESSONS:',
      '  • "ip nat inside" = private network side',
      '  • "ip nat outside" = public network side',
      '  • "ip nat inside source static <private> <public>" = 1-to-1 mapping',
      '  • show ip nat translations = verify your NAT table',
    ],
    objectives: [
      {
        id: 'devices',
        description: 'Add 5 devices (Router + 2 Switches + Server + PC)',
        type: 'device-count',
        params: { deviceType: 'any', count: 5 },
      },
      {
        id: 'connections',
        description: 'Create 4 cable connections',
        type: 'connection-count',
        params: { count: 4 },
      },
      {
        id: 'ip-router',
        description: 'Configure 2 IPs on the Router (inside + outside)',
        type: 'ip-configured',
        params: { deviceType: 'router' },
      },
      {
        id: 'hostname',
        description: 'Set hostname on Router',
        type: 'hostname-set',
        params: { deviceType: 'router' },
      },
      {
        id: 'ping',
        description: 'Successfully ping between networks through the Router',
        type: 'ping-success',
        params: {},
        hint: 'From Server: ping 203.0.113.1 (or from PC: ping 192.168.1.1)',
      },
    ],
  },
  {
    id: 'lab-11-ospf-routing',
    title: 'Lab 11: OSPF Dynamic Routing',
    difficulty: 'advanced',
    description: 'Configure OSPF on two routers so they automatically learn each other\'s networks. No static routes needed!',
    instructions: [
      '--- START WITH A CLEAN CANVAS ---',
      '',
      'TOPOLOGY:',
      '  PC1 ─── Switch1 ─── Router1 ─── Router2 ─── Switch2 ─── PC2',
      '  Network A: 10.0.1.0/24         Link: 10.0.0.0/30         Network B: 10.0.2.0/24',
      '',
      'STEP 1: Build the topology',
      '  • Drag: 2 Routers, 2 Switches, 2 PCs',
      '  • Connect: PC1→Switch1→Router1→Router2→Switch2→PC2',
      '  • Use gi0/0 on each Router for the Switch side',
      '  • Use gi0/1 on each Router for the Router-to-Router link',
      '',
      'STEP 2: Configure Router1',
      '  • Double-click Router1 → CLI:',
      '    enable',
      '    configure terminal',
      '    hostname R1',
      '    interface gi0/0',
      '    ip address 10.0.1.1 255.255.255.0',
      '    no shutdown',
      '    exit',
      '    interface gi0/1',
      '    ip address 10.0.0.1 255.255.255.252',
      '    no shutdown',
      '    exit',
      '    router ospf 1',
      '    network 10.0.1.0 0.0.0.255 area 0',
      '    network 10.0.0.0 0.0.0.3 area 0',
      '    exit',
      '    exit',
      '',
      'STEP 3: Configure Router2',
      '  • Double-click Router2 → CLI:',
      '    enable',
      '    configure terminal',
      '    hostname R2',
      '    interface gi0/0',
      '    ip address 10.0.2.1 255.255.255.0',
      '    no shutdown',
      '    exit',
      '    interface gi0/1',
      '    ip address 10.0.0.2 255.255.255.252',
      '    no shutdown',
      '    exit',
      '    router ospf 1',
      '    network 10.0.2.0 0.0.0.255 area 0',
      '    network 10.0.0.0 0.0.0.3 area 0',
      '    exit',
      '    exit',
      '',
      'STEP 4: Configure PCs',
      '  • PC1: 10.0.1.10 255.255.255.0 → no shut',
      '  • PC2: 10.0.2.10 255.255.255.0 → no shut',
      '',
      'STEP 5: Test',
      '  • From PC1: ping 10.0.2.10',
      '  • From Router1: show ip ospf',
      '',
      'KEY LESSON: OSPF automatically advertises connected networks.',
      'Both routers learn about each other\'s networks without static routes.',
      'This is how large enterprise networks scale.',
    ],
    objectives: [
      {
        id: 'devices',
        description: 'Add 6 devices (2 Routers + 2 Switches + 2 PCs)',
        type: 'device-count',
        params: { deviceType: 'any', count: 6 },
      },
      {
        id: 'connections',
        description: 'Create 5 cable connections',
        type: 'connection-count',
        params: { count: 5 },
      },
      {
        id: 'ip-routers',
        description: 'Configure IPs on both Routers',
        type: 'ip-configured',
        params: { deviceType: 'router' },
      },
      {
        id: 'ip-pcs',
        description: 'Configure IPs on both PCs',
        type: 'ip-configured',
        params: { deviceType: 'pc' },
      },
      {
        id: 'hostname',
        description: 'Set custom hostnames on the Routers',
        type: 'hostname-set',
        params: { deviceType: 'router' },
      },
      {
        id: 'ping',
        description: 'Ping from PC1 to PC2 across both Routers (via OSPF)',
        type: 'ping-success',
        params: {},
        hint: 'From PC1: ping 10.0.2.10',
      },
    ],
  },
  {
    id: 'lab-12-firewall-dmz',
    title: 'Lab 12: Firewall with DMZ',
    difficulty: 'advanced',
    description: 'Set up a Firewall to protect an internal network while allowing access to a DMZ server.',
    instructions: [
      '--- START WITH A CLEAN CANVAS ---',
      '',
      'TOPOLOGY:',
      '  Internet PC ─── Firewall ─── Internal Switch ─── Internal PC',
      '                     │',
      '                  DMZ Switch ─── Web Server',
      '',
      'STEP 1: Build the topology',
      '  • Drag: 1 Firewall, 2 Switches, 1 Server, 2 PCs',
      '  • Connect:',
      '    - "Internet PC" → Firewall (Outside port)',
      '    - Firewall (Inside port) → Switch1 → "Internal PC"',
      '    - Firewall (DMZ port) → Switch2 → Server',
      '',
      'STEP 2: Configure the Firewall',
      '  • Double-click Firewall → CLI:',
      '    enable',
      '    configure terminal',
      '    hostname FW1',
      '    interface Outside',
      '    ip address 203.0.113.1 255.255.255.0',
      '    no shutdown',
      '    exit',
      '    interface Inside',
      '    ip address 192.168.1.1 255.255.255.0',
      '    no shutdown',
      '    exit',
      '    interface DMZ',
      '    ip address 172.16.0.1 255.255.255.0',
      '    no shutdown',
      '    exit',
      '',
      'STEP 3: Configure ACL — block outside traffic from reaching inside network.',
      '  The ACL goes on the OUTSIDE interface INBOUND (filtering traffic as it enters):',
      '    access-list 100 permit 203.0.113.0 0.0.0.255',
      '    (This permits outside traffic — we will block it from reaching Inside)',
      '',
      '  Now create an ACL on the Inside interface OUTBOUND to block outside sources:',
      '    access-list 110 deny 203.0.113.0 0.0.0.255',
      '    access-list 110 permit any',
      '    interface Inside',
      '    ip access-group 110 out',
      '    exit',
      '    exit',
      '',
      '  This means: traffic going OUT of the Inside interface (toward internal PCs)',
      '  is denied if it came from 203.0.113.0/24 (the outside network).',
      '  But traffic to the DMZ is NOT blocked because it goes out the DMZ interface.',
      '',
      'STEP 4: Configure devices',
      '  • Internet PC: enable → conf t → int e0 → ip address 203.0.113.50 255.255.255.0 → no shut',
      '  • Internal PC: enable → conf t → int e0 → ip address 192.168.1.10 255.255.255.0 → no shut',
      '  • Web Server:  enable → conf t → int e0 → ip address 172.16.0.100 255.255.255.0 → no shut',
      '',
      'STEP 5: Test',
      '  • Internet PC → ping 172.16.0.100 (DMZ Server) → should WORK',
      '    (traffic: Outside→Firewall→DMZ — no ACL blocking this path)',
      '  • Internet PC → ping 192.168.1.10 (Internal) → should be BLOCKED',
      '    (traffic: Outside→Firewall→Inside — ACL 110 denies 203.0.113.x outbound on Inside)',
      '',
      'STEP 6: Verify',
      '  • On Firewall: show access-lists',
      '',
      'KEY LESSONS:',
      '  • Firewalls separate networks into zones (Outside/Inside/DMZ)',
      '  • ACLs control traffic between zones',
      '  • DMZ hosts public services (web servers) accessible from outside',
      '  • Inside network is protected — outside cannot reach it',
      '  • ACL direction matters: "in" = entering interface, "out" = leaving interface',
    ],
    objectives: [
      {
        id: 'firewall',
        description: 'Add a Firewall device',
        type: 'device-exists',
        params: { deviceType: 'firewall' },
      },
      {
        id: 'devices',
        description: 'Add at least 6 devices total',
        type: 'device-count',
        params: { deviceType: 'any', count: 6 },
      },
      {
        id: 'connections',
        description: 'Create at least 5 cable connections',
        type: 'connection-count',
        params: { count: 5 },
      },
      {
        id: 'hostname',
        description: 'Set hostname on the Firewall',
        type: 'hostname-set',
        params: { deviceType: 'firewall' },
        hint: 'hostname FW1',
      },
      {
        id: 'ping',
        description: 'Successfully ping the DMZ server',
        type: 'ping-success',
        params: {},
        hint: 'From any PC: ping 172.16.0.100',
      },
    ],
  },

  // ============================================================
  // PFSENSE & TP-LINK LABS
  // ============================================================
  {
    id: 'lab-13-pfsense-firewall',
    title: 'Lab 13: pfSense Firewall Setup',
    difficulty: 'intermediate',
    description: 'Configure a pfSense firewall using the Web GUI. Set up WAN/LAN interfaces, create firewall rules to block specific traffic, and enable DHCP.',
    instructions: [
      '--- START WITH A CLEAN CANVAS ---',
      '',
      'TOPOLOGY:',
      '  Internet PC ─── pfSense (WAN) ─── (LAN) pfSense ─── Switch ─── PC1',
      '                                                          └── PC2',
      '',
      'STEP 1: Build the topology',
      '  • Drag: 1 pfSense, 1 Switch, 2 PCs, 1 extra PC (as "Internet")',
      '  • Connect:',
      '    - "Internet PC" → pfSense WAN port',
      '    - pfSense LAN port → Switch',
      '    - PC1 → Switch',
      '    - PC2 → Switch',
      '',
      'STEP 2: Configure pfSense (double-click to open Web GUI)',
      '  • Go to Interfaces tab:',
      '    - WAN: IP = 203.0.113.1, Mask = 255.255.255.0, Enable ✓',
      '    - LAN: IP = 192.168.1.1, Mask = 255.255.255.0, Enable ✓',
      '  • Go to DHCP tab:',
      '    - Enable DHCP Server on LAN ✓',
      '    - Range: 192.168.1.100 - 192.168.1.200',
      '',
      'STEP 3: Configure the Internet PC (double-click for CLI)',
      '  • enable → conf t → int e0 → ip address 203.0.113.50 255.255.255.0 → no shut',
      '',
      'STEP 4: Configure internal PCs',
      '  • PC1: enable → conf t → int e0 → ip address 192.168.1.10 255.255.255.0 → no shut',
      '  • PC2: enable → conf t → int e0 → ip address 192.168.1.20 255.255.255.0 → no shut',
      '  • Or use: ipconfig /renew (to get IP from pfSense DHCP)',
      '',
      'STEP 5: Test — both PCs should ping pfSense LAN',
      '  • From PC1: ping 192.168.1.1 → should succeed',
      '',
      'STEP 6: Add a firewall rule to BLOCK PC2',
      '  • Open pfSense Web GUI → Firewall Rules tab',
      '  • Click "+ Add Block Rule"',
      '  • Set: Interface = LAN, Source = 192.168.1.20, Destination = any',
      '  • Add description: "Block PC2"',
      '',
      'STEP 7: Test again',
      '  • PC1: ping 192.168.1.1 → still works',
      '  • PC2: ping 192.168.1.1 → BLOCKED!',
      '',
      'KEY LESSON: pfSense firewall rules work the same as Cisco ACLs,',
      'but with a visual interface. First matching rule wins. Implicit deny at the end.',
    ],
    objectives: [
      {
        id: 'pfsense-device',
        description: 'Add a pfSense device',
        type: 'device-exists',
        params: { deviceType: 'pfsense' },
      },
      {
        id: 'devices',
        description: 'Add at least 5 devices total',
        type: 'device-count',
        params: { deviceType: 'any', count: 5 },
      },
      {
        id: 'connections',
        description: 'Create at least 4 cable connections',
        type: 'connection-count',
        params: { count: 4 },
      },
      {
        id: 'ip-pcs',
        description: 'Configure IP addresses on the PCs',
        type: 'ip-configured',
        params: { deviceType: 'pc' },
      },
      {
        id: 'ping',
        description: 'Successfully ping through the pfSense',
        type: 'ping-success',
        params: {},
        hint: 'From PC1: ping 192.168.1.1',
      },
    ],
  },
  {
    id: 'lab-14-tplink-home-network',
    title: 'Lab 14: Home Network with TP-Link Router',
    difficulty: 'beginner',
    description: 'Set up a home network using a TP-Link router. Configure internet access, WiFi, DHCP, and port forwarding — just like setting up your real home router.',
    instructions: [
      '--- START WITH A CLEAN CANVAS ---',
      '',
      'TOPOLOGY: Simulating a home network',
      '  ISP Router ─── TP-Link (WAN) ─── (LAN ports) ─── PC (desktop)',
      '                                                  ─── Server (home server)',
      '',
      'STEP 1: Build the topology',
      '  • Drag: 1 TP-Link Router, 1 Router (as ISP), 1 PC, 1 Server',
      '  • Connect:',
      '    - ISP Router → TP-Link WAN port',
      '    - PC → TP-Link LAN1 port',
      '    - Server → TP-Link LAN2 port',
      '',
      'STEP 2: Configure the ISP Router (simulates your internet provider)',
      '  • Double-click ISP Router → CLI:',
      '    enable → conf t → int gi0/0 → ip address 203.0.113.1 255.255.255.0 → no shut',
      '',
      'STEP 3: Configure TP-Link (double-click to open Web GUI)',
      '  • Internet tab:',
      '    - WAN IP: 203.0.113.10',
      '    - Subnet: 255.255.255.0',
      '    - Gateway: 203.0.113.1',
      '    - DNS: 8.8.8.8',
      '  • Wireless tab:',
      '    - SSID: MyHomeWiFi',
      '    - Password: SecurePass123',
      '  • LAN/DHCP tab:',
      '    - Router IP: 192.168.0.1',
      '    - DHCP: Enabled ✓',
      '    - Pool: 192.168.0.100 - 192.168.0.200',
      '',
      'STEP 4: Configure home devices',
      '  • PC: enable → conf t → int e0 → ip address 192.168.0.10 255.255.255.0 → no shut',
      '  • Server: enable → conf t → int e0 → ip address 192.168.0.50 255.255.255.0 → no shut',
      '  • Or use: ipconfig /renew',
      '',
      'STEP 5: Test',
      '  • From PC: ping 192.168.0.1 (TP-Link) → should work',
      '  • From PC: ping 192.168.0.50 (Server) → should work',
      '',
      'STEP 6: Set up port forwarding for the home server',
      '  • Open TP-Link GUI → Forwarding tab',
      '  • Add rule: External Port 80 → Internal IP 192.168.0.50, Port 80',
      '  • Now external traffic to your public IP on port 80 reaches your server!',
      '',
      'KEY LESSON: This is exactly how you set up your home WiFi router.',
      'Same concepts as enterprise: WAN, LAN, DHCP, NAT, port forwarding.',
    ],
    objectives: [
      {
        id: 'tplink-device',
        description: 'Add a TP-Link router',
        type: 'device-exists',
        params: { deviceType: 'tplink' },
      },
      {
        id: 'devices',
        description: 'Add at least 4 devices',
        type: 'device-count',
        params: { deviceType: 'any', count: 4 },
      },
      {
        id: 'connections',
        description: 'Create at least 3 cable connections',
        type: 'connection-count',
        params: { count: 3 },
      },
      {
        id: 'ping',
        description: 'Successfully ping between devices',
        type: 'ping-success',
        params: {},
        hint: 'From PC: ping 192.168.0.1',
      },
    ],
  },

  // ============================================================
  // WIRELESS, NAS, & ADVANCED TOPOLOGY LABS
  // ============================================================
  {
    id: 'lab-15-wireless-network',
    title: 'Lab 15: Wireless Network — Laptop via WiFi',
    difficulty: 'intermediate',
    description: 'Connect a Laptop to the network wirelessly through a TP-Link router. Configure WiFi, connect via SSID, and test connectivity.',
    instructions: [
      '--- START WITH A CLEAN CANVAS ---',
      '',
      'TOPOLOGY:',
      '  Internet Router ─── TP-Link (WAN) ─── (LAN) ─── PC (wired)',
      '                                   ~~~~~~~~ Laptop (wireless)',
      '',
      'STEP 1: Build the wired part',
      '  • Drag: 1 Router (ISP), 1 TP-Link, 1 PC',
      '  • Connect: Router → TP-Link WAN port',
      '  • Connect: PC → TP-Link LAN1 port',
      '',
      'STEP 2: Add a Laptop (DO NOT cable it — it will connect wirelessly)',
      '  • Drag a Laptop onto the canvas',
      '  • Leave it unconnected for now',
      '',
      'STEP 3: Configure the ISP Router',
      '  • Double-click Router → CLI:',
      '    enable → conf t → int gi0/0 → ip address 203.0.113.1 255.255.255.0 → no shut',
      '',
      'STEP 4: Configure TP-Link',
      '  • Double-click TP-Link → Web GUI:',
      '  • Internet tab: WAN IP = 203.0.113.10, Gateway = 203.0.113.1',
      '  • Wireless tab: Enable WiFi ✓, SSID = "HomeWiFi", Password = "test1234"',
      '  • LAN/DHCP tab: LAN IP = 192.168.0.1, DHCP Enabled ✓',
      '',
      'STEP 5: Configure the wired PC',
      '  • Double-click PC → CLI:',
      '    enable → conf t → int e0 → ip address 192.168.0.10 255.255.255.0 → no shut',
      '',
      'STEP 6: Connect the Laptop via WiFi',
      '  • Double-click the Laptop → WiFi dialog opens',
      '  • You should see "HomeWiFi" in the available networks',
      '  • Click Connect → enter password "test1234" → click Join',
      '  • A dashed blue line appears between Laptop and TP-Link = wireless connection!',
      '',
      'STEP 7: Configure Laptop IP',
      '  • The Laptop needs an IP. Use the CLI toolbar button to open CLI for the Laptop:',
      '    enable → conf t → int e0 → ip address 192.168.0.20 255.255.255.0 → no shut',
      '  • Or use: ipconfig /renew (to get IP from DHCP)',
      '',
      'STEP 8: Test connectivity',
      '  • From Laptop: ping 192.168.0.1 (TP-Link) → should work',
      '  • From Laptop: ping 192.168.0.10 (wired PC) → should work',
      '  • Both wired and wireless devices are on the same LAN!',
      '',
      'KEY LESSON: WiFi and wired devices share the same LAN.',
      'The TP-Link bridges wireless clients to the LAN — they get the same subnet.',
    ],
    objectives: [
      {
        id: 'tplink',
        description: 'Add a TP-Link router',
        type: 'device-exists',
        params: { deviceType: 'tplink' },
      },
      {
        id: 'devices',
        description: 'Add at least 4 devices',
        type: 'device-count',
        params: { deviceType: 'any', count: 4 },
      },
      {
        id: 'connections',
        description: 'Create at least 2 connections (wired + wireless)',
        type: 'connection-count',
        params: { count: 2 },
      },
      {
        id: 'ping',
        description: 'Successfully ping between wired and wireless devices',
        type: 'ping-success',
        params: {},
        hint: 'From Laptop: ping 192.168.0.10',
      },
    ],
  },
  {
    id: 'lab-16-nas-file-server',
    title: 'Lab 16: NAS File Server Setup',
    difficulty: 'intermediate',
    description: 'Set up a Synology NAS on the network. Configure its IP, shared folders, file services, and verify that PCs can reach it.',
    instructions: [
      '--- START WITH A CLEAN CANVAS ---',
      '',
      'TOPOLOGY:',
      '  PC1 ─── Switch ─── NAS',
      '  PC2 ───┘',
      '',
      'STEP 1: Build the topology',
      '  • Drag: 1 Switch, 1 NAS, 2 PCs',
      '  • Connect: PC1 → Switch, PC2 → Switch, NAS → Switch',
      '',
      'STEP 2: Configure PCs',
      '  • PC1: enable → conf t → int e0 → ip address 192.168.1.10 255.255.255.0 → no shut',
      '  • PC2: enable → conf t → int e0 → ip address 192.168.1.20 255.255.255.0 → no shut',
      '',
      'STEP 3: Configure the NAS (double-click to open Synology DSM)',
      '  • Go to Network tab:',
      '    - LAN 1: IP = 192.168.1.200, Mask = 255.255.255.0, Gateway = 192.168.1.1',
      '    - LAN 2: Optionally enable for redundancy',
      '  • Go to Shared Folders tab:',
      '    - Verify "shared" folder exists (Read/Write)',
      '    - Create a new folder called "projects" (Read/Write)',
      '  • Go to File Services tab:',
      '    - Enable SMB (Windows File Sharing) ✓',
      '    - Optionally enable NFS for Linux clients',
      '  • Go to Users tab:',
      '    - Verify "admin" user exists',
      '    - Create a user "employee1"',
      '',
      'STEP 4: Test connectivity',
      '  • From PC1: ping 192.168.1.200 → should work',
      '  • From PC2: ping 192.168.1.200 → should work',
      '',
      'STEP 5: Review on the NAS Overview tab',
      '  • Check that IP shows as configured',
      '  • Check that SMB shows as "Enabled"',
      '  • Check storage usage',
      '',
      'In real life, PC1 and PC2 would now access \\\\192.168.1.200\\shared',
      'in Windows Explorer or mount the NFS share on Linux.',
      '',
      'KEY LESSON: NAS devices are configured through a web GUI (like Synology DSM).',
      'They provide file sharing via SMB/NFS/FTP to all devices on the network.',
    ],
    objectives: [
      {
        id: 'nas',
        description: 'Add a NAS device',
        type: 'device-exists',
        params: { deviceType: 'nas' },
      },
      {
        id: 'devices',
        description: 'Add at least 4 devices',
        type: 'device-count',
        params: { deviceType: 'any', count: 4 },
      },
      {
        id: 'connections',
        description: 'Create at least 3 connections',
        type: 'connection-count',
        params: { count: 3 },
      },
      {
        id: 'ping',
        description: 'Successfully ping the NAS from a PC',
        type: 'ping-success',
        params: {},
        hint: 'From PC1: ping 192.168.1.200',
      },
    ],
  },
  {
    id: 'lab-17-office-network',
    title: 'Lab 17: Complete Office Network',
    difficulty: 'advanced',
    description: 'Build a realistic small office network with all device types: pfSense firewall, managed switch, NAS, PCs, IP Phone, Printer, and WiFi for laptops.',
    instructions: [
      '--- START WITH A CLEAN CANVAS ---',
      '',
      'SCENARIO: You are setting up the network for a small company.',
      'They need: internet access, WiFi for laptops, file storage, printing, and IP phones.',
      '',
      'TOPOLOGY:',
      '  Internet (Router) ─── pfSense (WAN)',
      '                        pfSense (LAN) ─── Switch 24-port',
      '                                          ├── PC1 (Accounting)',
      '                                          ├── PC2 (Sales)',
      '                                          ├── IP Phone → PC3 (Reception)',
      '                                          ├── Printer',
      '                                          ├── NAS',
      '                                          └── TP-Link AP (WiFi for laptops)',
      '                                               ~~~~~~~~ Laptop',
      '',
      'STEP 1: Build the topology',
      '  • Drag all devices onto the canvas',
      '  • Connect in order:',
      '    1. Router → pfSense WAN',
      '    2. pfSense LAN → Switch 24-port',
      '    3. PC1 → Switch',
      '    4. PC2 → Switch',
      '    5. IP Phone (SW port) → Switch',
      '    6. Printer → Switch',
      '    7. NAS → Switch',
      '    8. TP-Link (WAN) → Switch',
      '  • Leave Laptop unconnected (it will use WiFi)',
      '',
      'STEP 2: Configure ISP Router',
      '  • enable → conf t → int gi0/0 → ip address 203.0.113.1 255.255.255.0 → no shut',
      '',
      'STEP 3: Configure pfSense (double-click → Web GUI)',
      '  • Interfaces: WAN = 203.0.113.10/24, Gateway = 203.0.113.1',
      '  • Interfaces: LAN = 192.168.1.1/24',
      '  • DHCP: Enable on LAN, range 192.168.1.100 - 192.168.1.200',
      '  • Firewall: Default "Pass LAN to any" rule (already there)',
      '',
      'STEP 4: Configure all devices with static IPs on 192.168.1.0/24:',
      '  • PC1: 192.168.1.10',
      '  • PC2: 192.168.1.11',
      '  • Printer: configure via its web panel if available, or assign 192.168.1.50',
      '  • NAS: 192.168.1.200 (via Synology DSM → Network tab)',
      '  • TP-Link: LAN IP = 192.168.1.1 → NO! Change to 192.168.1.2 to avoid conflict with pfSense',
      '    WAN IP = leave empty (gets from pfSense DHCP or static)',
      '    WiFi: SSID = "OfficeWiFi", Password = "Company2024"',
      '',
      'STEP 5: Connect Laptop via WiFi',
      '  • Double-click Laptop → WiFi dialog → connect to "OfficeWiFi"',
      '  • Assign IP: 192.168.1.30',
      '',
      'STEP 6: Test everything',
      '  • From PC1: ping 192.168.1.200 (NAS) → works',
      '  • From Laptop: ping 192.168.1.10 (PC1) → works',
      '  • From PC2: ping 192.168.1.1 (pfSense gateway) → works',
      '',
      'STEP 7: Configure NAS shared folders',
      '  • Open NAS DSM → Shared Folders',
      '  • Create: "accounting" (Read/Write), "sales" (Read/Write), "company" (Read Only)',
      '  • Enable SMB file sharing',
      '',
      'CONGRATULATIONS! You just built a complete office network.',
      'This is exactly what a junior network admin does on their first day.',
    ],
    objectives: [
      {
        id: 'pfsense',
        description: 'Add a pfSense firewall',
        type: 'device-exists',
        params: { deviceType: 'pfsense' },
      },
      {
        id: 'nas',
        description: 'Add a NAS',
        type: 'device-exists',
        params: { deviceType: 'nas' },
      },
      {
        id: 'devices',
        description: 'Add at least 9 devices',
        type: 'device-count',
        params: { deviceType: 'any', count: 9 },
      },
      {
        id: 'connections',
        description: 'Create at least 7 connections (wired + wireless)',
        type: 'connection-count',
        params: { count: 7 },
      },
      {
        id: 'ip-pcs',
        description: 'Configure IPs on the PCs',
        type: 'ip-configured',
        params: { deviceType: 'pc' },
      },
      {
        id: 'ping',
        description: 'Successfully ping across the network',
        type: 'ping-success',
        params: {},
        hint: 'From any PC: ping 192.168.1.200 (NAS)',
      },
    ],
  },
  {
    id: 'lab-18-security-audit',
    title: 'Lab 18: Security Audit — Lock Down the Network',
    difficulty: 'advanced',
    description: 'Start with an open network and progressively lock it down using pfSense firewall rules, TP-Link SPI, and proper network segmentation.',
    instructions: [
      '--- START WITH A CLEAN CANVAS ---',
      '',
      'SCENARIO: Your company network is WIDE OPEN. Anyone on any segment',
      'can reach anything. Your job: lock it down properly.',
      '',
      'STEP 1: Build a network with 2 segments',
      '  • pfSense with WAN and LAN configured',
      '  • LAN side: Switch → Server (192.168.1.100), PC1 (192.168.1.10), PC2 (192.168.1.20)',
      '  • WAN side: TP-Link (simulating guest WiFi) → Laptop (via WiFi)',
      '',
      'STEP 2: Verify everything is open',
      '  • PC1 can ping Server → works',
      '  • PC2 can ping Server → works',
      '  • If laptop configured on WAN side → can it reach the server?',
      '',
      'STEP 3: Security Rule 1 — Block PC2 from Server',
      '  • Open pfSense → Firewall Rules',
      '  • Add Block Rule: Interface=LAN, Source=192.168.1.20, Dest=192.168.1.100',
      '  • Make sure "Pass LAN to any" rule is BELOW the block rule',
      '  • Test: PC1 → Server = works, PC2 → Server = BLOCKED',
      '',
      'STEP 4: Security Rule 2 — Disable WAN ping on TP-Link',
      '  • Open TP-Link → Security tab',
      '  • Enable SPI Firewall ✓',
      '  • Disable "Allow Ping from WAN" ✗',
      '  • Test: devices on WAN side cannot ping TP-Link',
      '',
      'STEP 5: Verify your security',
      '  • PC1 → Server: ALLOWED',
      '  • PC2 → Server: BLOCKED',
      '  • WAN → TP-Link: ping BLOCKED',
      '  • PC1 → pfSense: ALLOWED (needed for gateway)',
      '',
      'KEY LESSON: Defense in depth — use multiple layers of security.',
      'Firewall rules (pfSense) + SPI (TP-Link) + proper segmentation.',
    ],
    objectives: [
      {
        id: 'pfsense',
        description: 'Add a pfSense firewall',
        type: 'device-exists',
        params: { deviceType: 'pfsense' },
      },
      {
        id: 'tplink',
        description: 'Add a TP-Link router',
        type: 'device-exists',
        params: { deviceType: 'tplink' },
      },
      {
        id: 'server',
        description: 'Add a Server',
        type: 'device-exists',
        params: { deviceType: 'server' },
      },
      {
        id: 'devices',
        description: 'Add at least 6 devices',
        type: 'device-count',
        params: { deviceType: 'any', count: 6 },
      },
      {
        id: 'connections',
        description: 'Create at least 5 connections',
        type: 'connection-count',
        params: { count: 5 },
      },
      {
        id: 'ping',
        description: 'Successfully ping (from allowed PC to server)',
        type: 'ping-success',
        params: {},
        hint: 'From PC1: ping 192.168.1.100',
      },
    ],
  },

  // ============================================================
  // CRIMPING LAB (19): Hands-on cable crimping — no guidance
  // ============================================================
  {
    id: 'lab-19-cable-crimping',
    title: 'Lab 19: Cable Crimping Challenge',
    difficulty: 'beginner',
    description: 'Prove your knowledge of Ethernet cable standards. Crimp an RJ45 connector using the correct T-568B wire order — no hints, no guides, just what you learned.',
    instructions: [
      '--- CABLE CRIMPING LAB ---',
      '',
      'This lab opens the Cable Crimping Simulator.',
      'You must arrange all 8 wires in the correct order and crimp the cable.',
      '',
      'RULES:',
      '  • No hints or reference guides — use what you learned in the lessons',
      '  • Select the T-568B standard (most common in real-world)',
      '  • Pick each wire and place it in the correct pin slot',
      '  • Crimp the cable when all 8 wires are placed',
      '  • Test the cable — all 8 pins must pass',
      '',
      'RECALL: T-568B pin order from left to right (pin 1 → pin 8):',
      '  You should know this by now!',
      '',
      'If you fail, reset and try again until you can do it from memory.',
      'A real network technician can crimp a cable in under 30 seconds.',
    ],
    objectives: [
      {
        id: 'crimp-pass',
        description: 'Crimp an RJ45 cable and pass the cable test with 8/8 pins correct',
        type: 'custom',
        params: { target: 'crimping-simulator' },
        hint: 'Open the Crimping Simulator and arrange the wires in T-568B order.',
      },
    ],
  },
];
