import type { Lab } from './lab-types.js';

export const LABS: Lab[] = [
  {
    id: 'lab-01-basic-connectivity',
    title: 'Lab 1: Basic Connectivity',
    difficulty: 'beginner',
    description: 'Learn the basics — add devices to the canvas and connect them with a cable.',
    instructions: [
      'Add a PC and a Switch to the canvas using the device palette or toolbar.',
      'Connect the PC to the Switch by clicking a port on the PC, then clicking a port on the Switch.',
      'Verify the cable appears between the two devices.',
    ],
    objectives: [
      {
        id: 'add-pc',
        description: 'Add a PC to the canvas',
        type: 'device-exists',
        params: { deviceType: 'pc' },
        hint: 'Click "PC" in the left panel or toolbar to add one.',
      },
      {
        id: 'add-switch',
        description: 'Add a Switch to the canvas',
        type: 'device-exists',
        params: { deviceType: 'switch' },
        hint: 'Click "Switch" in the left panel or toolbar.',
      },
      {
        id: 'connect-them',
        description: 'Connect the PC to the Switch with a cable',
        type: 'connection-exists',
        params: {},
        hint: 'Click a blue port dot on the PC, then click a port on the Switch.',
      },
    ],
  },
  {
    id: 'lab-02-ip-addressing',
    title: 'Lab 2: IP Addressing',
    difficulty: 'beginner',
    description: 'Configure IP addresses on a PC and Router so they can communicate.',
    instructions: [
      'Add a Router and a PC to the canvas.',
      'Connect them with an Ethernet cable.',
      'Click the Router to open its CLI. Configure an IP on GigabitEthernet0/0:',
      '  enable → configure terminal → interface gi0/0 → ip address 192.168.1.1 255.255.255.0 → no shutdown',
      'Click the PC and configure its Ethernet0 interface:',
      '  enable → configure terminal → interface e0 → ip address 192.168.1.2 255.255.255.0 → no shutdown',
      'From the PC, ping the Router: ping 192.168.1.1',
    ],
    objectives: [
      {
        id: 'add-router',
        description: 'Add a Router to the canvas',
        type: 'device-exists',
        params: { deviceType: 'router' },
      },
      {
        id: 'add-pc',
        description: 'Add a PC to the canvas',
        type: 'device-exists',
        params: { deviceType: 'pc' },
      },
      {
        id: 'connect',
        description: 'Connect the Router and PC with a cable',
        type: 'connection-exists',
        params: {},
        hint: 'Click a port on the Router, then a port on the PC.',
      },
      {
        id: 'ip-router',
        description: 'Configure an IP address on the Router',
        type: 'ip-configured',
        params: { deviceType: 'router' },
        hint: 'In the Router CLI: enable → conf t → int gi0/0 → ip address 192.168.1.1 255.255.255.0 → no shut',
      },
      {
        id: 'ip-pc',
        description: 'Configure an IP address on the PC',
        type: 'ip-configured',
        params: { deviceType: 'pc' },
        hint: 'In the PC CLI: enable → conf t → int e0 → ip address 192.168.1.2 255.255.255.0 → no shut',
      },
      {
        id: 'ping-success',
        description: 'Successfully ping between the devices',
        type: 'ping-success',
        params: {},
        hint: 'From the PC CLI: ping 192.168.1.1',
      },
    ],
  },
  {
    id: 'lab-03-multi-device-network',
    title: 'Lab 3: Multi-Device Network',
    difficulty: 'intermediate',
    description: 'Build a small network with a Router, Switch, and multiple PCs. Configure IPs and verify connectivity.',
    instructions: [
      '1. Add 1 Router, 1 Switch, and 2 PCs to the canvas.',
      '2. Connect: Router → Switch, PC1 → Switch, PC2 → Switch (3 cables total).',
      '3. Click the Router, open CLI and type:',
      '   enable',
      '   configure terminal',
      '   hostname CoreRouter',
      '   interface gi0/0',
      '   ip address 10.0.0.1 255.255.255.0',
      '   no shutdown',
      '   exit',
      '   exit',
      '4. Click PC1 (first PC), open CLI and type:',
      '   enable',
      '   configure terminal',
      '   interface e0',
      '   ip address 10.0.0.10 255.255.255.0',
      '   no shutdown',
      '   exit',
      '   exit',
      '5. Click PC2 (second PC), open CLI and type:',
      '   enable',
      '   configure terminal',
      '   interface e0',
      '   ip address 10.0.0.20 255.255.255.0',
      '   no shutdown',
      '   exit',
      '   exit',
      '6. From any PC, ping the Router:',
      '   ping 10.0.0.1',
      'Note: The Switch does not need an IP address — it operates at Layer 2.',
    ],
    objectives: [
      {
        id: 'devices',
        description: 'Add at least 4 devices (1 Router + 1 Switch + 2 PCs)',
        type: 'device-count',
        params: { deviceType: 'any', count: 4 },
      },
      {
        id: 'connections',
        description: 'Create at least 3 cable connections',
        type: 'connection-count',
        params: { count: 3 },
        hint: 'Router→Switch, Switch→PC1, Switch→PC2',
      },
      {
        id: 'hostname',
        description: 'Set a custom hostname on the Router',
        type: 'hostname-set',
        params: { deviceType: 'router' },
        hint: 'In Router CLI: enable → conf t → hostname CoreRouter',
      },
      {
        id: 'ip-router',
        description: 'Configure an IP address on the Router',
        type: 'ip-configured',
        params: { deviceType: 'router' },
        hint: 'Router CLI: enable → conf t → int gi0/0 → ip address 10.0.0.1 255.255.255.0 → no shut',
      },
      {
        id: 'ip-pcs',
        description: 'Configure IP addresses on both PCs',
        type: 'ip-configured',
        params: { deviceType: 'pc' },
        hint: 'PC CLI: enable → conf t → int e0 → ip address 10.0.0.10 255.255.255.0 → no shut',
      },
      {
        id: 'interfaces-up',
        description: 'Bring Router and PC interfaces up (no shutdown)',
        type: 'interface-up',
        params: { deviceType: 'router' },
        hint: 'Inside interface config mode: no shutdown',
      },
      {
        id: 'ping',
        description: 'Successfully ping the Router from a PC',
        type: 'ping-success',
        params: {},
        hint: 'From any PC CLI: ping 10.0.0.1',
      },
    ],
  },
  {
    id: 'lab-04-server-network',
    title: 'Lab 4: Server Infrastructure',
    difficulty: 'intermediate',
    description: 'Build a network with a Server, Router, and PCs. Simulate a basic client-server topology.',
    instructions: [
      '1. Add 1 Router, 1 Switch, 1 Server, and 2 PCs.',
      '2. Connect: Server→Switch, Router→Switch, PC1→Switch, PC2→Switch (4 cables).',
      '3. Click the Router, open CLI:',
      '   enable',
      '   configure terminal',
      '   interface gi0/0',
      '   ip address 172.16.0.1 255.255.255.0',
      '   no shutdown',
      '   exit',
      '   exit',
      '4. Click the Server, open CLI:',
      '   enable',
      '   configure terminal',
      '   interface e0',
      '   ip address 172.16.0.100 255.255.255.0',
      '   no shutdown',
      '   exit',
      '   exit',
      '5. Click PC1, open CLI:',
      '   enable',
      '   configure terminal',
      '   interface e0',
      '   ip address 172.16.0.10 255.255.255.0',
      '   no shutdown',
      '   exit',
      '   exit',
      '6. Click PC2, open CLI:',
      '   enable',
      '   configure terminal',
      '   interface e0',
      '   ip address 172.16.0.20 255.255.255.0',
      '   no shutdown',
      '   exit',
      '   exit',
      '7. From any PC, ping the Server:',
      '   ping 172.16.0.100',
      'Note: The Switch does not need IP configuration — it forwards traffic at Layer 2.',
    ],
    objectives: [
      {
        id: 'server',
        description: 'Add a Server to the network',
        type: 'device-exists',
        params: { deviceType: 'server' },
      },
      {
        id: 'devices',
        description: 'Add at least 5 devices total',
        type: 'device-count',
        params: { deviceType: 'any', count: 5 },
      },
      {
        id: 'connections',
        description: 'Create at least 4 cable connections',
        type: 'connection-count',
        params: { count: 4 },
      },
      {
        id: 'ip-router',
        description: 'Configure an IP address on the Router',
        type: 'ip-configured',
        params: { deviceType: 'router' },
        hint: 'Router CLI: int gi0/0 → ip address 172.16.0.1 255.255.255.0 → no shut',
      },
      {
        id: 'ip-server',
        description: 'Configure an IP address on the Server',
        type: 'ip-configured',
        params: { deviceType: 'server' },
        hint: 'Server CLI: int e0 → ip address 172.16.0.100 255.255.255.0 → no shut',
      },
      {
        id: 'ip-pcs',
        description: 'Configure IP addresses on both PCs',
        type: 'ip-configured',
        params: { deviceType: 'pc' },
        hint: 'PC CLI: int e0 → ip address 172.16.0.10 255.255.255.0 → no shut',
      },
      {
        id: 'ping',
        description: 'Successfully ping the Server from a PC',
        type: 'ping-success',
        params: {},
        hint: 'From any PC CLI: ping 172.16.0.100',
      },
    ],
  },
];
